### PR TITLE
#23440 retain categories if header no present and test

### LINKED ISSUE #23440: Categories being removed from content items when updating content via CSV file upload
### Describe the bug
I tested on 5.3.8.10 this is a feature but from 22.03.XX when uploading multiple content items via CSV file upload, those content items will be stripped of their categories (unless keeping those columns in the CSV file upload).

### To Reproduce
1. Create test content type with categories as field
2. Create few contents let with categories e.g Age/Gender (Boyes, Girls)
3. Export those content lets as CSV
4. strip categories column
5: Import now these contents
6:Categories will be gone

### Expected behavior
Should be passed as lists:
- Any list -> we will overwrite them.
- Empty list -> will delete all entries.

If the column is not present -> will keep the same.

### Additional context
 Will quoted:
 "Our pattern with checking in content with Categories, Relationships is pretty simple.  Both of these properties should be passed in as lists.  So the rule is this - if you pass any list in, we overwrite what is there - and this includes an empty list, which should basically delete all entries.  If you do not include the category/relationship property, we should just maintain what was there previously."
 
 Related Ticket: https://dotcms.zendesk.com/agent/tickets/109228

### PR DESCRIPTION
**Pull request by erickgonzalez**
### Proposed Changes
Retain categories if header is not present, by getting the categories of the current working contentlet.
Only run this, if there is a category field in the content type and it's not present in the headers.
Created test.

### CODE REVIEW

**Review by jcastro-dotcms — APPROVED** [review]

**Review by freddyucv — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java [hunk 1]
```diff
@@ -1517,7 +1520,7 @@ private static void importLine ( String[] line, String currentHostId, Structure
     }
 
     private static Contentlet runWorkflowIfCould(final User user, final List<Permission> contentTypePermissions,
-                                                 final Set<Category> categories, final Contentlet contentlet,
+                                                 final List<Category> categories, final Contentlet contentlet,
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java:1523]: why changing from Set to List?

Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java:1523]: the list of categories already comes ready to process, in that method we're only converting to a list when passing to the following methods, so it's better to receive a list.

Comment (dsilvam) [reply dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java:1523]: But the Set avoids duplicates. Is that something we want to keep?

Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java:1523]: I know, but as I said the list comes ready to this method, meaning without duplicates. We're not adding more categories inside this method, so there is no really an advantage to use Set, since the other methods are waiting for a list.

**Review by dsilvam — APPROVED** [review]
