### PR TITLE
#21632 adding test when not attrs only name id

### LINKED ISSUE #21632: Allow SAML assertions without any attributes in the claims
**Describe the bug**
Some SAML configurations may not include any attributes. If the user is fully managed (created with name, ID, email, username, groups) within dotCMS, then the only relevant piece of data in the assertion may be the subject. 

Currently if there are no attributes in the claim then it just fails to parse upon login.

**To Reproduce**
Hard to specifically reproduce, but can be done with an IDP like ADFS where you only send the samAccountName
1. Set the company to UserID for auth
2. Create a user with an ID that matches the samAccountName
3. Configure your claims mapping with strictly the samAccountName as the only attribute
4. Attempt to log in 

You will receive a 500 error from dotCMS

**Expected behavior**
You should be able to log in to dotCMS with only the Subject set as long as the subject matches the UserID of an existing user.

### PR DESCRIPTION
**Pull request by jdotcms**
This PR allows the creation of the user without email, lastname or name from the SAML  attributes

### CODE REVIEW

File: dotCMS/src/integration-test/java/com/dotcms/auth/providers/saml/v1/SAMLHelperTest.java [hunk 1]
```diff
@@ -284,4 +286,59 @@ public void test_getRoleKeySubstitution_processReplacement_doing_substitution()
...
+
+        company.setAuthType(Company.AUTH_TYPE_EA);
+        when(companyAPI.getDefaultCompany()).thenReturn(company);
+        final IdentityProviderConfiguration identityProviderConfiguration = mock(IdentityProviderConfiguration.class);
+        final Attributes attrs = new Attributes.Builder().nameID(UUID.randomUUID()).build();
+
+        final User user = samlHelper.createNewUser(APILocator.systemUser(), attrs, identityProviderConfiguration);
+
+        Assert.assertNotNull(user);
+        Assert.assertEquals(samlHelper.hashIt(attrs.getNameID().toString()), user.getUserId());
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotcms/auth/providers/saml/v1/SAMLHelperTest.java:311]: should we check here the others attribute?, for example check that the email is really null

File: dotCMS/src/integration-test/java/com/dotcms/auth/providers/saml/v1/SAMLHelperTest.java [hunk 2]
```diff
@@ -284,4 +286,59 @@ public void test_getRoleKeySubstitution_processReplacement_doing_substitution()
...
+    }
+
+    /**
+     * Method to test: {@link SAMLHelper#createNewUser(User, Attributes, IdentityProviderConfiguration)}
+     * Given Scenario: creates an user only with name id
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotcms/auth/providers/saml/v1/SAMLHelperTest.java:316]: I think that the doc it not right for this test

Comment (jdotcms) [reply dotCMS/src/integration-test/java/com/dotcms/auth/providers/saml/v1/SAMLHelperTest.java:316]: thx you right

**Review by erickgonzalez — APPROVED** [review]

**Review by freddyucv — APPROVED** [review]
