### PR TITLE
Fix: Correct various TypeScript type definitions in SDK

### LINKED ISSUE #32229: SDK: Adjust Types
### Problem statement

We found some minor issues on the Types that we need to fix across all libraries.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Task List

- [X] In `DotCMSBasicContentlet` type  we should make `url` property optional and remove the `[key: string]: any;` wild-card to make TypeScript break if they are trying to access a non-existent property.
- [X] `DotcmsNavigationItem` has wrong Casing, it should be `DotCMSNavigationItem`
- [X] On Angular SDK, `DotCMSEditablePageService` has a type mismatch, it accepts `page | undefined` but returns `page | null`
- [X] Hook `useEditablePage` and Angular homologate should take `DotCMSComposedPageResponse` to ensure type matching with `client` method
- [X] Navigation API is returning unknown even though we have a type for it `DotcmsNavigationItem`
- [X] Expose `graphql` section of `DotCMSPageRequestParams` to type params
- [X] In `DotCMSPageRequestParams` the `mode` property should be typed as `UVE_MODE`
- [X] Change the type on `initUVE` to receive the `pageResponse` type from the `client`

### PR DESCRIPTION
**Pull request by fmontes**
https://github.com/user-attachments/assets/c64befec-12b3-490e-8588-f1426ea5d4e1

This PR introduces a better DX for types on DotCMSEditable components

on Components:

https://github.com/user-attachments/assets/b77a1887-ed57-4220-b34a-ae2dd7a19e3a

And on exported functions:

https://github.com/user-attachments/assets/f11f79b2-9be0-48e7-a6fd-4304fefdf428

This commit addresses several type inconsistencies and improvements across the SDK libraries as per the issue:

- In `DotCMSBasicContentlet`:
    - Made the `url` property optional.
    - Removed the wildcard index signature `[key: string]: any;`.
- Renamed `DotcmsNavigationItem` to `DotCMSNavigationItem` and updated all its usages.
- In the Angular SDK's `DotCMSEditablePageService`:
    - Fixed a type mismatch in the `listen` method, changing its return type from `Observable<DotCMSPageResponse | null>` to `Observable<DotCMSPageResponse | undefined>`.
- In the React SDK's `useEditablePage` hook (`useEditableDotCMSPage`):
    - Changed the input parameter type from `DotCMSPageResponse` to `DotCMSComposedPageResponse`.
- For the Navigation API client:
    - Corrected the return type of the `get` method from `Promise<unknown>` to `Promise<DotCMSNavigationItem[]>`.
    - Verified that the `mode` property's existing type (`'EDIT_MODE' | 'PREVIEW_MODE' | 'LIVE'`) fulfills the `UVE_MODE` requirement.

This pull request introduces several updates across the codebase, focusing on improving type safety, aligning naming conventions, and enhancing the functionality of DotCMS-related components and services. The most significant changes include the replacement of `null` with `undefined` for optional types, the introduction of new generics to improve type specificity, and updates to interfaces and methods for better alignment with the DotCMS data model.

### Type Safety Improvements:
* Updated `DotCMSPageResponse` and related types to use `undefined` instead of `null`, ensuring consistency across observables and services (`dotcms-editable-page.service.ts`, `dotcms-editable-page.service.spec.ts`). [[1]](diffhunk://#diff-9e99be6093c44be0c1ff531e7f2eee75185a56c63cd07e9ec60b8db26d98ccf4L77-R77) [[2]](diffhunk://#diff-08ba5e2ca6377757a25ae71539af956c5b47f9f6b918a74bdca06a1e23b7438dL19-R33) [[3]](diffhunk://#diff-08ba5e2ca6377757a25ae71539af956c5b47f9f6b918a74bdca06a1e23b7438dL60-R71)
* Enhanced type safety in `DotCMSEditableTextComponent` and `DotCMSEditableText` by explicitly casting field names as `keyof DotCMSBasicContentlet` (`dotcms-editable-text.component.ts`, `DotCMSEditableText.tsx`). [[1]](diffhunk://#diff-13b3fa13c52c84acbf35b8d1e8edeb3621d0b7c9c22242d4fbc592d005c13ac8L182-R182) [[2]](diffhunk://#diff-a9f5ce3b51841e32f21318ae90f875b8a8926768c19cd34d147aec96f8cdd049L47-R49) [[3]](diffhunk://#diff-a9f5ce3b51841e32f21318ae90f875b8a8926768c19cd34d147aec96f8cdd049L80-R82)

### Interface and Model Updates:
* Introduced new `DotCMSGraphQLParams` interface and replaced inline GraphQL configuration in `DotCMSPageRequestParams` with this new interface for better modularity (`public.ts`). [[1]](diffhunk://#diff-7a1c0cdeb52d19fcb8cb822cbef4604df7d9d86b6912541a46680fd92dd043adR1-R29) [[2]](diffhunk://#diff-7a1c0cdeb52d19fcb8cb822cbef4604df7d9d86b6912541a46680fd92dd043adL48-R74)
* Updated `DotCMSBasicContentlet` to make `url` optional and added a `_map` property for additional metadata (`page/public.ts`).

### Naming and Typing Alignments:
* Corrected naming inconsistencies by replacing `DotcmsNavigationItem` with `DotCMSNavigationItem` across the codebase (`dotcms.model.ts`, `navigation-api.ts`, `page/public.ts`). [[1]](diffhunk://#diff-e538e4158603875314fa11f911c67958e5e2ee7cd744954f8972c540dd368903L137-R140) [[2]](diffhunk://#diff-ccca05575b5095ec6e63c7a7d3be4723cc9ed76a5ddf12197c6ad456b5785dc7L1-R6) [[3]](diffhunk://#diff-bd581f50b01e2c5349a94fffc2e262e2897d118f34472c379b1d08c5bbf6c6e4L381-R384)

### Enhancements to Generics:
* Added generics to `useEditableDotCMSPage` and `listen` methods to allow more precise typing for extended page responses (`useEditableDotCMSPage.ts`, `dotcms-editable-page.service.ts`). [[1]](diffhunk://#diff-f78890dec62f8ed6dd903e01e0931c541d5d291a854248d84f43c429aabf33a4L94-R102) [[2]](diffhunk://#diff-08ba5e2ca6377757a25ae71539af956c5b47f9f6b918a74bdca06a1e23b7438dL60-R71)

### Test and Mock Updates:
* Updated test cases and mocks to align with type changes, including casting mocks to new or updated interfaces (`testing.utils.ts`, `public.spec.ts`). [[1]](diffhunk://#diff-f7e12b7d718596e0107fff0bf72efa13aaf7654b4ad50221a8160c0ce0f10749L73-R73) [[2]](diffhunk://#diff-fde0f0510ae802a367b483d0fa3a73b8a18a1fcf79b8ba931847faa7518cad7aL133-R149)

These changes collectively improve the maintainability, readability, and robustness of the codebase by ensuring stricter type checks and better alignment with the DotCMS data model.

### CODE REVIEW

File: core-web/libs/sdk/react/src/lib/next/components/DotCMSEditableText/DotCMSEditableText.tsx [hunk 1]
```diff
@@ -44,7 +44,9 @@ export function DotCMSEditableText({
     const editorRef = useRef<Editor['editor'] | null>(null);
     const [scriptSrc, setScriptSrc] = useState('');
     const [initEditor, setInitEditor] = useState(false);
-    const [content, setContent] = useState(contentlet?.[fieldName] || '');
+    const [content, setContent] = useState(
+        contentlet?.[fieldName as keyof DotCMSBasicContentlet] || ''
```
Comment (zJaaal) [inline core-web/libs/sdk/react/src/lib/next/components/DotCMSEditableText/DotCMSEditableText.tsx:48]: I think you can type the prop, to avoid doing the `as` 
try this in angular too

File: core-web/libs/sdk/uve/src/lib/editor/public.ts [hunk 2]
```diff
@@ -125,7 +125,7 @@ export function enableBlockEditorInline(
     contentlet: DotCMSBasicContentlet,
     fieldName: string
```
Comment (zJaaal) [inline core-web/libs/sdk/uve/src/lib/editor/public.ts:126]: try typing this fieldName, instead of string. Test it out, I think it can be disruptive for the user when passing the value, so if it will give trouble to them, leave the `as` this apply to my comment related above

Comment (zJaaal) [reply core-web/libs/sdk/uve/src/lib/editor/public.ts:126]: The thing with typing, is that we probably will need to make it generic, because sometimes the field is not part of the base contentlet, but a custom property

File: core-web/libs/sdk/angular/next/services/dotcms-editable-page.service.ts [hunk 3]
```diff
@@ -57,11 +62,13 @@ export class DotCMSEditablePageService {
...
-     * @returns Observable that emits the updated page data or null
+     * @returns Observable that emits the updated page data or undefined
      */
-    listen(response?: DotCMSPageResponse): Observable<DotCMSPageResponse | null> {
+    listen<T extends DotCMSExtendedPageResponse>(
+        response?: DotCMSComposedPageResponse<T>
+    ): Observable<DotCMSComposedPageResponse<T> | undefined> {
         if (!getUVEState()) {
-            return of(response || null);
+            return of(response || undefined);
```
Comment (zJaaal) [inline core-web/libs/sdk/angular/next/services/dotcms-editable-page.service.ts:71]: do we need the or? I think we don't, test it out just in case

I think we did that to force the null for type reasons, because it can be `undefined` but not `null`

**Review by zJaaal — CHANGES_REQUESTED** [review]
Nice, I just have some suggestions

**Review by rjvelazco — APPROVED** [review]

File: core-web/libs/sdk/angular/next/services/dotcms-editable-page.service.ts (hunk 3 above)
Comment (KevinDavilaDotCMS) [reply core-web/libs/sdk/angular/next/services/dotcms-editable-page.service.ts:71]: Removed!

**Review by zJaaal — APPROVED** [review]
