### PR TITLE
Fixes #7064

### LINKED ISSUE #7064: The reorder does not working in the side nav/ menu bar
Related to #7023 

After this fix now the top menu bar, works fine when you try to reorder the menu, but if you try to reorder the menu of the side nav, using the theme with side nav, this does not working...

Also if you create some page using the side nav theme, and here you select some special side nav order and save the changes, the reorder is not working, and if you go to the page properties and enable the show on menu option to the html page, and go back to try to reorder again, you will have a "Opsss error message"....

You can see here: http://screencast.com/t/ckehzyTCpr

Tested on nightly build 2015-01-22 // H2 // FF

### PR DESCRIPTION
**Pull request by maurizo**

### CODE REVIEW

File: src/com/dotmarketing/portlets/folders/action/OrderMenuAction.java [hunk 1]
```diff
@@ -110,10 +110,11 @@ public void processAction(
 						CacheLocator.getNavToolCache().removeNavByPath(id.getHostId(), id.getPath());
 					}
 					Folder folder = APILocator.getFolderAPI().findParentFolder(treeable, user, false);
-					String folderId = (folder==null) ? FolderAPI.SYSTEM_FOLDER : folder.getIdentifier();
-					CacheLocator.getNavToolCache().removeNav(id.getHostId(), folderId);
+					String folderInode = (folder==null) ? FolderAPI.SYSTEM_FOLDER : folder.getInode();
+					CacheLocator.getNavToolCache().removeNav(id.getHostId(), folderInode);
 				}
 				
+				CacheLocator.getNavToolCache().clearCache();
```
Comment (jtesser) [inline src/com/dotmarketing/portlets/folders/action/OrderMenuAction.java]: Maurice please get me a new pull request with the fix
