### PR TITLE
#19939 Allow to show DotAsset Image into a Page

### LINKED ISSUE #19939: Images uploaded to an Image Field via Drag-and-Drop from a file manager will not display as images
As reported in https://dotcms.zendesk.com/agent/tickets/103549 and recreated on current Demo v21.x

Images uploaded to an Image Field via Drag-and-Drop from a file manager will not display as images.

The files do not get saved as "Files"  - they become 'dotAsset' files.

This breaks the display of the contentlet. 

In the example from demo (see screenshots) the entire contentlet - even the fields that are not Image Fields - will fail to display

**To Reproduce**
1. Create a new content type with an Image Field or add an Image Field to an existing content type.
2. Add a contentlet including an image in the Image Field via browse/upload instead of drag/drop
3. Add contentlet to a page. It should display as normal. 
4. Edit the contentlet by inserting a new image by dragging a file from a local file explorer to the field.
5. Save/publish

**Expected behavior**
Image should display as normal.

**Actual Behavior**
None of the contentlet's fields display. Content appears blank.

CONTENTLET - IMAGE ADDED NORMALLY
image

NORMAL CONTENTLET DISPLAY ON FE
image

REPLACE IMAGE VIA DRAG AND DROP
image

CONTENTLET EDIT SCREEN AFTER DRAG AND DROP
image

PAGE EDIT SCREEN AFTER CHANGING IMAGE
image

FRONT END VIEW OF THE PAGE AFTER CHANGING IMAGE (NOTE ALL FIELDS MISSING)
image

CONTENT->SEARCH - IMAGE WAS UPLOADED AS dotASSET, NOT FILE
Note that the first image was uploaded as a "File" and the drag/dropped file was uploaded as a "dotAsset"
image

### PR DESCRIPTION
**Pull request by freddyucv**
Create a new methods in FileTool to support the DotAsset contents.
Also Support the DotAsset content in ShortyServlet

### CODE REVIEW

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/FileTool.java [hunk 1]
```diff
@@ -56,6 +75,18 @@ public String getURI(FileAsset file, long languageId){
 			return "";
 		}
 	}
+
+	public String getURI(final Contentlet contentlet, long languageId){
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/FileTool.java:79]: You can avoid last ugly else doing such as
```
String uri = StringPool.BLANK;


if (contentlet instanceof FileAsset) {
			uri = getURI((FileAsset) contentlet, languageId);
		} else if (contentlet.isDotAsset()){
			uri = UtilMethods.espaceForVelocity(
					String.format("dA/%s", contentlet.getIdentifier())
			);
		}
return uri;
```

**Review by jdotcms — APPROVED** [review]

**Comment by erickgonzalez** [comment]
Postman tests that were created for this are failing https://raw.githack.com/dotCMS/test-results/issue-19939-Images-uploaded-to-an-Image-Field-via-Drag-and-Drop-from-a-file-manager-will-not-display-as--images/projects/core/current/curl/postgres/reports/html/Image.html , besides that looks good

**Review by erickgonzalez — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/FileTool.java (hunk 1 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/FileTool.java:80]: done https://github.com/dotCMS/core/pull/20116/commits/c2de26da737fbd57ed7d67a22425f7cd16a99955
