### PR TITLE
#21583 make MimeTypeUtils more robust

### LINKED ISSUE #21583: MimeUtils should catch a throwable
We have cases where the tika bundle we ship with does not contain the right libraries to parse certain files - which is ok, we can't do everything.  The issue is that Tika throws a `Throwable` `java.lang.NoClassDefFoundError` error which we should catch and handle more gracefully.  This is causing some asset metadata generation to fail.

```
16:32:55.985  ERROR reindex.ReindexThread - ReindexThread Exception
java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.ooxml.util.DocumentHelper
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.parseContentTypesFile(ContentTypeManager.java:392) ~[?:?]
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.<init>(ContentTypeManager.java:104) ~[?:?]
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.<init>(ZipContentTypeManager.java:54) ~[?:?]
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:258) ~[?:?]
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:725) ~[?:?]
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:199) ~[?:?]
	at org.apache.tika.parser.pkg.ZipContainerDetector.detectOPCBased(ZipContainerDetector.java:253) ~[?:?]
	at org.apache.tika.parser.pkg.ZipContainerDetector.detectZipFormat(ZipContainerDetector.java:173) ~[?:?]
	at org.apache.tika.parser.pkg.ZipContainerDetector.detect(ZipContainerDetector.java:110) ~[?:?]
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84) ~[?:?]
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84) ~[?:?]
	at org.apache.tika.Tika.detect(Tika.java:156) ~[?:?]
	at org.apache.tika.Tika.detect(Tika.java:288) ~[?:?]
	at com.dotcms.osgi.tika.TikaProxy.detect(TikaProxy.java:71) ~[?:?]
	at com.dotcms.tika.TikaUtils.detect(TikaUtils.java:662) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.util.MimeTypeUtils.getMimeType(MimeTypeUtils.java:48) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.storage.FileStorageAPIImpl.generateBasicMetaData(FileStorageAPIImpl.java:130) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.storage.FileStorageAPIImpl.generateMetaData(FileStorageAPIImpl.java:254) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.storage.FileMetadataAPIImpl.generateBasicMetadata(FileMetadataAPIImpl.java:167) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.storage.FileMetadataAPIImpl.generateContentletMetadata(FileMetadataAPIImpl.java:115) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.storage.FileMetadataAPIImpl.generateContentletMetadata(FileMetadataAPIImpl.java:276) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.writeMetadata(ESMappingAPIImpl.java:430) ~[dotcms_21.06.5_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap_aroundBody0(ESMappingAPIImpl.java:398) ~
```

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
for some reason, the Tika Bundle somehow's missing. Classes should have been loaded via OSGI from whatever path is instructed in the Felix install-dir /bundle 
Whenever that happens we must be prepared for failure and catch Throwables

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/util/MimeTypeUtils.java [hunk 1]
```diff
@@ -46,8 +42,9 @@ public static String getMimeType (final File binary) {
             if( !UtilMethods.isSet(mimeType)){
                 try {
                     mimeType = new TikaUtils().detect(binary);
-                } catch(Exception e) {
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/util/MimeTypeUtils.java:49]: What if these throw a throwable?  I am not sure `Sneeky.sneek` handles throwables. 
```
        final Path path = binary.toPath();
        String mimeType = Sneaky.sneak(() -> Files.probeContentType(path));
```

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/util/MimeTypeUtils.java:49]: Rats!! they don't!

**Review by nollymar — APPROVED** [review]

**Review by dsilvam — APPROVED** [review]
