### PR TITLE
#adding fixes when no id, inode or CT, support temp file

### LINKED ISSUE #20060: Allow multiple contents to be put via API
dotCMS has REST apis for saving content in the system, most notably, the content and workflowAPIs.  This allows for single pieces of content to be put one at a time in dotCMS.

In addition to these endpoints, we need another endpoint that can take multiple contents/assets.  The format for these puts should be similar to our current workflow API put, where you can specify a workflow and a contentlet as a json object - but instead it should take a workflow and then array of content objects and loop over them (perhaps multithreaded?) and ingest them in dotCMS.   Each content object created would get pushed through the same workflow step/process.

If we mutlithreaded, we should 1. make that configurable and 2. start with say 4 threads.

### PR DESCRIPTION
**Pull request by erickgonzalez**
mock request to be able to access temp files.
if no id, inode nor CT is passed throw error.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/mock/request/DotCMSMockRequestWithSession.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
+package com.dotcms.mock.request;
+
+import javax.servlet.http.HttpSession;
+
+/**
+ * Pretty much the same of {@link DotCMSMockRequest} but includes a session
+ */
+public class DotCMSMockRequestWithSession extends DotCMSMockRequest {
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotcms/mock/request/DotCMSMockRequestWithSession.java:8]: is it not possible add just a constructor in DotCMSMockRequest?

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java [hunk 2]
```diff
@@ -1705,18 +1711,19 @@ private void saveMultipleContentletsByDefaultAction(final List<Map<String, Objec
...
                     fireTransactionalAction(systemAction, singleFireActionForm, request, mode,
                             initDataObject, resultMap, inode, identifier, languageId, user, indexPolicy);
                 } catch (Exception e) {
 
-                    final String id = UtilMethods.isSet(identifier)?identifier:inode;
+                    final String id = UtilMethods.isSet(identifier) ? identifier :
+                            (UtilMethods.isSet(inode) ? inode:
+                                    null != singleFireActionForm && null != singleFireActionForm.getContentletFormData() ?
+                                            singleFireActionForm.getContentletFormData().toString() :
+                                            "unknown contentlet" + System.currentTimeMillis());
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java:1726]: is not need any curl-test for this change?

Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java:1726]: yup working on it

**Review by freddyucv — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]
