### PR TITLE
#22391 Avoid NPE on null story block with when saving and retrieving …

### LINKED ISSUE #22391: GraphQL not working with block editor field
**Describe the bug**
GraphQL query that include a block editor field is throwing an error and not returning the content of the block editor field.

**To Reproduce**
1. Go to GraphQL playground
2. Run this query
```
query PostBySlug {
  BlogCollection(
    query: "+urlmap:/blog/post/ecotourism-in-costa-rica"
    limit: 1
  ) {
    title
    urlTitle
    blogContent {
      json
    }
  }
}
```
3. See error and the logs

```
13:05:56.648  WARN  execution.SimpleDataFetcherExceptionHandler - Exception while fetching data (/BlogCollection[0]/blogContent) : null
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:?]
	at com.dotmarketing.util.json.JSONTokener.<init>(JSONTokener.java:49) ~[dotcms_22.06_999999.jar:?]
	at com.dotmarketing.util.json.JSONObject.<init>(JSONObject.java:302) ~[dotcms_22.06_999999.jar:?]
	at com.dotcms.graphql.datafetcher.StoryBlockFieldDataFetcher.get(StoryBlockFieldDataFetcher.java:19) ~[dotcms_22.06_999999.jar:?]
	at com.dotcms.graphql.datafetcher.StoryBlockFieldDataFetcher.get(StoryBlockFieldDataFetcher.java:11) ~[dotcms_22.06_999999.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) ~[graphql-java-13.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:654) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:533) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:485) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:423) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:388) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:200) ~[graphql-java-13.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
```

**Expected behavior**
It should work with any block editor field

### PR DESCRIPTION
**Pull request by dsilvam**
Avoids throwing NPE when:
* Checking in a contentlet without story block field
* Retrieving a content with empty story block field from GraphQL

Includes postman test for this case.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/graphql/datafetcher/StoryBlockFieldDataFetcher.java [hunk 1]
```diff
@@ -16,7 +16,9 @@ public Map<String, Object> get(DataFetchingEnvironment environment) throws Excep
         final Map<String, Object> storyBlockMap = new HashMap<>();
 
         final String contFieldValue = contentlet.getStringProperty(variableName);
-        final JSONObject jsonContFieldValue = new JSONObject(contFieldValue);
+        final JSONObject jsonContFieldValue = contFieldValue!=null
+                ? new JSONObject(contFieldValue)
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/graphql/datafetcher/StoryBlockFieldDataFetcher.java:20]: Let's make `JSONObject` more robust if a null is sent in, have it return just an empty JSONObject

**Review by wezell — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/dotcms/graphql/datafetcher/StoryBlockFieldDataFetcher.java (hunk 1 above)
Comment (dsilvam) [reply dotCMS/src/main/java/com/dotcms/graphql/datafetcher/StoryBlockFieldDataFetcher.java]: @wezell Done. Validated at JSONObject level.

**Review by freddyucv — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
Lgtm
