### PR TITLE
Issue 20494 error retrieving content references in multilang setup

### LINKED ISSUE #20494: Error retrieving content references in multilingual setup
**Describe the bug**
You can't view/edit a piece of content when it has a reference in the non-default language on a page that is not available in the default language. For instance when de default language is EN and you have a piece of content on it that is available for EN + NL and the NL piece is placed on a page that is only available in NL then you can't open the piece of EN content.

**To Reproduce**
1. Go to demo.dotcms.com
2. Open the 'Booking date selector' code widget (which is located on the homepage) and create a Spanish version of it (note: it could be any content)
3. Save/publish the Spanish version of the content
4. Create a new Page Asset only in Spanish and put the Spanish 'Booking date selector' on it. This all works fine
5. Open the homepage in EN and open the 'Booking date selector' OR open the 'Booking date selector' in the content tab -> ERROR

**Expected behavior**
You should be able to edit the content

**The cause**
When calculating the references the multitrees are retrieved and the code looks for a page in the language of the content _that you are opening_, not the language of the content reference. 
https://github.com/dotCMS/core/blob/702102e2cbf772c99c4b414d09a15081d86a5708/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1195
I think there should be something like 'multitree.getLanguageId()', or if that does not exist you probably first need to look up the reference's language and use that. 

**Workaround**
A workaround is to create a default language version (EN in the example) for each page

### PR DESCRIPTION
**Pull request by dsilvam**
* Avoids failing when a referenced page (from multitree) in the Content References tab can't be found in the contentlet's lang. 
* Added "Persona" column to the Contentlet References result list
* Integration tests for both changes

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java [hunk 1]
```diff
@@ -1167,22 +1170,44 @@ private IHTMLPage loadPageByIdentifier ( String ident, boolean live, User user,
...
+                final IHTMLPage page = APILocator.getHTMLPageAssetAPI()
+                        .findByIdLanguageFallback(tree.getHtmlPage(), contentlet.getLanguageId(),
+                                false,
+                                APILocator.getUserAPI().getSystemUser(), false);
+
+                final Container container = APILocator.getContainerAPI()
+                        .getWorkingContainerById(tree.getContainer(),
+                                APILocator.getUserAPI().getSystemUser(), false);
+
+                if (InodeUtils.isSet(page.getInode()) && InodeUtils.isSet(container.getInode())) {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java:1184]: it is a very small thing but seems it is a shortcircuit it would be worthy to try this in two if such as 

```
final IHTMLPage page = APILocator.getHTMLPageAssetAPI()
                        .findByIdLanguageFallback(tree.getHtmlPage(), contentlet.getLanguageId(),
                                false,
                                APILocator.getUserAPI().getSystemUser(), false);

if (InodeUtils.isSet(page.getInode()) {
    final Container container = APILocator.getContainerAPI()
                        .getWorkingContainerById(tree.getContainer(),
                                APILocator.getUserAPI().getSystemUser(), false);
    if (InodeUtils.isSet(container.getInode())) {
        ......

```

Minor thing, but if the page inode is not set, you will save CPU time not asking for the container

Comment (dsilvam) [reply dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java:1184]: This is not new code @jdotcms , but makes sense to me. I will apply it

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java [hunk 2]
```diff
@@ -1167,22 +1170,44 @@ private IHTMLPage loadPageByIdentifier ( String ident, boolean live, User user,
...
+            } catch(DoesNotExistException e) {
+                Logger.debug(this, "Page not available in the requested language. This is ok");
             }
         }
         return results;
     }
 
+    private String getPersonaNameByMultitree(final MultiTree tree) throws DotSecurityException, DotDataException {
+        final String defaultPersona = Try.of(()->LanguageUtil.get(DEFAULT_PERSONA_NAME_KEY)).getOrElse("Default Visitor");
+        String personaTag = Try.of(()-> tree.getPersonalization()
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java:1201]: I think here you can return null,

if null return the defaultPersona.

I would also do the defaultPersona as a supplier to avoid the call if not needed

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java (hunk 1 above)
Comment (dsilvam) [reply dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java]: Done

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java (hunk 2 above)
Comment (dsilvam) [reply dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java:1206]: Done

**Review by erickgonzalez — APPROVED** [review]
