### PR TITLE
Issue 20110 push publishing is not respecting time zones and is basing publish time on the browser time

### LINKED ISSUE #20110: Push publishing is not respecting time zones and is basing publish time on the clients system (browser) time
**Describe the bug**
Push publishing is not respecting time zones. This is causing unexpected behaviour when push publishing bundles where your system time is ahead of server time. 

If your system time (e.g. the time set on your computer/laptop) is ahead of the servers time, regardless of whether the system time is set wrong or if you are in a time zone ahead of server time, your bundle will be set to publish in the future.

If your system time is behind server time, the bundle will publish immediately. This includes if you manually select a time in the future. If that time is behind server time, it will publish immediately.

The time on the receiver does not seem to matter. 

Ticket: https://dotcms.zendesk.com/agent/tickets/103734

Reproduced on dotCMS version 21.03

**To Reproduce**
There are multiple ways to reproduce the various behaviours.

1. Change your system time zone to ahead of UTC
2. Go to demo.dotcms.com
3. Create a 'dummy' push publishing endpoint. 
4. Try to push publish any content
5. Go to the publishing queue, this content will be set to publish in the future.

You can also reproduce incorrect behaviour by keeping your system time behind UTC, then attempting to publish something 'in the future', but still behind UTC. This content will publish immediately, despite being set to publish in the future.

For example, my local time was 9:30am, UTC was 1:30pm. I set something to publish at 11:40am, and it immediately tried to publish it. 

**Expected behavior**
Push publishing should account for time zones.

### PR DESCRIPTION
**Pull request by nollymar**
The timezone is now listed on the Publish popup and considered to format publish and expire dates

### CODE REVIEW

**Review by erickgonzalez — APPROVED** [review]

**Comment by dsilvam** [comment]
I would add a postman test for the new `timezones` map entry in the configuration helper

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/system/ConfigurationHelper.java [hunk 1]
```diff
@@ -135,9 +141,29 @@ private ConfigurationHelper() {
...
 	}
 
+    /**
+     * Returns a list of all available timezones
+     * @param locale
+     * @return
+     */
+	private List getTimeZones(final Locale locale){
+
+        final List<Map<String, Object>> timeZoneList = new ArrayList<>();
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/system/ConfigurationHelper.java:155]: great job, I would just add or mod a curl in order just to check that this field is always returned and is length >0

**Review by jdotcms — APPROVED** [review]

**Review by jcastro-dotcms — APPROVED** [review]

**Review by dsilvam — APPROVED** [review]
