### PR TITLE
fix(seo improvements): copy change for google serp preview

### LINKED ISSUE #26402: Copy Change for Google SERP Preview
[](https://mrkr.io/s/652475318a5f04745a5dcba8/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

Should be Google "Search Engine Results Page" not "Social Media Preview Tile"

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fblog-detail&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fblog-detail&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/652475318a5f04745a5dcbab_d852818454458ad7?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 118.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### PR DESCRIPTION
**Pull request by manuelrojas**
Refs: #26402

### Summary
🖼️🗣️🐛

This pull request enhances the UI and functionality of the meta tags for social media and search engines in the dot-edit-page portlet. It adds a `description` property to the social media tile options, improves the error handling and validation of the meta tags, and updates the previews and messages for the SEO tool component. It also modifies the `Language.properties` file and the `DotSelectSeoToolComponent` template accordingly.

> _`DotSelectSeoTool`_
> _Meta tags and messages_
> _Spring cleaning the UI_

### Walkthrough
*  Add a new property `description` to the social media tile options and display it in the UI ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-0b1cbca20fc4f4b1ccb288bb32c6dd4e26d1f4dc6d7647e530ca3c52dea1f1f5L159-R178), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-0b1cbca20fc4f4b1ccb288bb32c6dd4e26d1f4dc6d7647e530ca3c52dea1f1f5R186), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-f94705047ca30f9c4bcfd2c39193d16965fd3f0771d5de4618a35b85cd7d7e22L11-R11))
*  Modify the logic of the `getOgDescriptionErrors` method to check for different scenarios of missing or empty og:description and meta description tags, and return appropriate error messages ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-e2c6edc96a3d4a7581030dec6768557e11cfc76d6863da2ff346f2cb3efbc715R234-R235), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-e2c6edc96a3d4a7581030dec6768557e11cfc76d6863da2ff346f2cb3efbc715L244-R262), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-21db9723fa4c52389731b7575f1e19bd364aa992b7e549e22c08a33456994e94L5442-R5443))
*  Fix a typo in the error message key for the og:title meta tag ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-e2c6edc96a3d4a7581030dec6768557e11cfc76d6863da2ff346f2cb3efbc715L394-R411))
*  Add a new condition to the `getOgImageErrors` method to check for missing or empty og:image value and return a new error message ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-e2c6edc96a3d4a7581030dec6768557e11cfc76d6863da2ff346f2cb3efbc715R464-R471))
*  Modify the error message key for the twitter:title meta tag to be consistent with the other error messages ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-e2c6edc96a3d4a7581030dec6768557e11cfc76d6863da2ff346f2cb3efbc715L519-R546), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-21db9723fa4c52389731b7575f1e19bd364aa992b7e549e22c08a33456994e94L5479-R5484))
*  Modify the logic of the `ngOnInit` method in the `DotResultsSeoToolComponent` class to assign the title and description variables to the most relevant and valid values for the previews of the social media tiles and the search engine results page ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-6084f02c375b9edee18f429040e76a983a8469637f28dd29a9c8fa330774fb88L70-R82), [link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-6084f02c375b9edee18f429040e76a983a8469637f28dd29a9c8fa330774fb88L93-R102))
*  Add some HTML tags to the read-more messages for the linkedin summary and the google favicons to make them more readable and consistent ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-21db9723fa4c52389731b7575f1e19bd364aa992b7e549e22c08a33456994e94L5519-R5519))
*  Add a new language property for the search engine results page option ([link](https://github.com/dotCMS/core/pull/26410/files?diff=unified&w=0#diff-21db9723fa4c52389731b7575f1e19bd364aa992b7e549e22c08a33456994e94R5528))

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### CODE REVIEW

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-results-seo-tool/dot-results-seo-tool.component.ts [hunk 1]
```diff
@@ -67,11 +67,19 @@ export class DotResultsSeoToolComponent implements OnInit, OnChanges {
     seoMediaTypes = SEO_MEDIA_TYPES;
 
     ngOnInit() {
+        const title =
+            this.seoOGTags['og:title']?.slice(0, SEO_LIMITS.MAX_OG_TITLE_LENGTH) ||
+            this.seoOGTags['title']?.slice(0, SEO_LIMITS.MAX_TITLE_LENGTH);
```
Comment (zJaaal) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-results-seo-tool/dot-results-seo-tool.component.ts:72]: this can be `this.seoOGTags.title` right?

**Review by zJaaal — APPROVED** [review]

**Review by zJaaal — CHANGES_REQUESTED** [review]
can we add tests?

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/html/dot-seo-meta-tags.service.ts [hunk 2]
```diff
@@ -241,7 +243,22 @@ export class DotSeoMetaTagsService {
...
-        if (!ogDescription || descriptionOgElements.length === 0) {
+        if (
+            this.areAllFalsyOrEmpty([
+                ogDescription,
+                descriptionOgElements,
+                description,
+                descriptionElements
+            ])
+        ) {
+            result.push(
```
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/html/dot-seo-meta-tags.service.ts:254]: No need for this asserts with this changes?

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/html/dot-seo-meta-tags.service.ts
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/services/html/dot-seo-meta-tags.service.ts:1]: No need for tests changes for this?

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-select-seo-tool/dot-select-seo-tool.component.html [hunk 3]
```diff
@@ -8,7 +8,7 @@ <h5 class="dot-select-seo-tool__title" data-testId="select-seo-tool-title">
             {{ socialMediaTiles[socialMedia]?.label }}
         </h5>
         <span class="dot-select-seo-tool__details" data-testId="select-seo-tool-details">{{
-            'seo.rules.media.preview.tile' | dm
+            socialMediaTiles[socialMedia]?.description | dm
```
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-select-seo-tool/dot-select-seo-tool.component.html:11]: No tests update? 🤔

**Review by fmontes — APPROVED** [review]

**Review by zJaaal — APPROVED** [review]

**Review by KevinDavilaDotCMS — APPROVED** [review]
