### PR TITLE
fixes visitorSerializer #17372

### LINKED ISSUE #17372: Adding a persona without tags throws errors
The `VisitorSerializer` needs some null checking

```
14:05:22.459  INFO  reindex.ReindexThread - BulkRequests created : 2
14:05:37.934  WARN  mapper.JsonMappingExceptionMapper - Multiple entries with same key: title=Optional.empty and title=will at home (through reference chain: com.dotcms.rest.ResponseEntityView["entity"]->com.google.common.collect.RegularImmutableMap["viewAs"]->com.google.common.collect.RegularImmutableMap["visitor"])
com.fasterxml.jackson.databind.JsonMappingException: Multiple entries with same key: title=Optional.empty and title=will at home (through reference chain: com.dotcms.rest.ResponseEntityView["entity"]->com.google.common.collect.RegularImmutableMap["viewAs"]->com.google.common.collect.RegularImmutableMap["visitor"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:725) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2655) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:381) ~[jackson-core-2.9.8.jar:2.9.8]
```

### PR DESCRIPTION
**Pull request by wezell**

### CODE REVIEW

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/visitor/domain/VisitorSerializer.java [hunk 1]
```diff
@@ -16,16 +16,27 @@ public void serialize(Visitor visitor, JsonGenerator gen, SerializerProvider ser
...
       Persona persona = visitor.getPersona();
-      visitorBuilder.put("persona", ImmutableMap.of(
-          "keyTag", persona.getKeyTag(), 
-          "identifier",persona.getIdentifier(),
-          "tags",persona.getTags(),
-          "title",persona.getTitle()
-          )
-        );
+      ImmutableMap.Builder<String,Object> builder =ImmutableMap.builder();
+      if(persona.getKeyTag() !=null) {
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotcms/visitor/domain/VisitorSerializer.java]: I think this ifs are not necessary, because if you don't add the entry into the map then the attribute is not add into the json

**Review by jgambarios — APPROVED** [review]
