### PR TITLE
Issue 21408 fix password size validation annotations

### LINKED ISSUE #21408: fix password size validation annotations

### PR DESCRIPTION
**Pull request by freddyucv**
Fix the password size validation annotations
Also include curl-test

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/apps/ExportSecretForm.java [hunk 1]
```diff
@@ -8,15 +9,14 @@
...
+import com.dotcms.repackage.javax.validation.constraints.Max;
+import com.dotcms.repackage.javax.validation.constraints.Min;
+import com.dotcms.repackage.javax.validation.constraints.NotNull;
 
 public class ExportSecretForm extends Validated {
 
     @NotNull
-    @Min(14)
-    @Max(32)
+    @Size(min = 14, max=32, message="The password must be a string with a length of 14 and 32")
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/apps/ExportSecretForm.java:19]: "with a length between 14 and 32"

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/apps/ExportSecretForm.java (hunk 1 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/apps/ExportSecretForm.java]: done https://github.com/dotCMS/core/pull/21456/commits/c6b66f24fc7828606ff2281713c2d2d552d550fb

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM
