### PR TITLE
#19564 vanity url redirects and forwards must support param merge

### LINKED ISSUE #19564: 301 and 302 Vanity URL redirects do not pass querystrings
As reported in https://dotcms.zendesk.com/agent/tickets/102845

github issue: https://github.com/dotCMS/core/issues/18325

That issue is closed but the issue persists.

If you wish to pass a querystring parameter in dotcms 5.3x+ via a Vanity URL the only way to do it is via a 200 Forward.

301 and 302 Redirects do not pass the querystring.

**To Reproduce**
1. Create a Vanity URL
e.g.
**Uri**: /store/test(.*)
**Action**: 301 - Permanent Redirect
**Forward To**: /blog/test$1

2. Navigate to the 'from' URL: 
demo.dotcms.com/store/test?foo=bar

**Expected behavior**
Page should redirect to 
**demo.dotcms.com/blog/test?foo=bar**

**Actual Behavior**
If you use 301 or 302 Redirect it does not.

If you use 200 - Forward it DOES work, BUT the URL remains:
**demo.dotcms.com/store/test?foo=bar**

THE 'WORKING' CONFIGURATION
image

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
Per support request, we need to preserve the original query string passed on vanity URLs that get resolved with redirects

### CODE REVIEW

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotmarketing/filters/FiltersTest.java [hunk 1]
```diff
@@ -334,11 +338,41 @@ public void vanityUrlsShouldPassParams() throws Exception {
 
 
     }
-    
-    
-    
-    
-    
+
+    @Test
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotmarketing/filters/FiltersTest.java:342]: doc

**Review by freddyucv — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]

**Review by wezell — APPROVED** [review]
Third time is a charm! This looks good
