### PR TITLE
Issue 20446 very large images

### LINKED ISSUE #20446: Unable to load very large images
Loading very large images, e.g. images that are 30000x20000 pixels and 200mb on disk will cause dotCMS to churn and you will ultimately end up with an OOM exception

### PR DESCRIPTION
**Pull request by dsilvam**

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterApiImpl.java [hunk 1]
```diff
@@ -32,61 +48,244 @@ public String getVariableFromPath(final String path) {
...
+                            "subsample_w", new String[] {String.valueOf(maxSize)},
+                            "subsample_h", new String[] {String.valueOf(maxSize)},
+                            "subsample_hash", new String[] {hash},
+                            "filter", new String[] {"subsample"}
+            );
+            incomingImage = new SubSampleImageFilter().runFilter(incomingImage, params);
+            originalSize = getWidthHeight(incomingImage);
+        }
+        
+/*
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterApiImpl.java:222]: Can we remove this commented code?

Comment (dsilvam) [reply dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterApiImpl.java]: Done

File: dotCMS/src/main/java/com/dotmarketing/image/filter/HsbImageFilter.java [hunk 2]
```diff
@@ -50,9 +50,9 @@ public File runFilter(File file,  Map<String, String[]> parameters) {
 			BufferedImage dst = filter.filter(src, null);
 			ImageIO.write(dst, "png", resultFile);
 			dst.flush();
-		} catch (IOException e) {
-			Logger.error(this.getClass(), e.getMessage());
-		}
+	    } catch (Exception e) {
+	        throw new DotRuntimeException("unable to convert file:" +file + " : " +  e.getMessage(),e);
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/image/filter/HsbImageFilter.java:54]: May be add a log and throw the exception?

File: dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterAPI.java [hunk 3]
```diff
@@ -1,43 +1,120 @@
...
+
+    /**
+     * returns an image dimensions
+     * 
+     * @param image
+     * @return
+     */
+    Dimension getWidthHeight(File image);
+
+    /**
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterAPI.java:57]: this one looks such as orphan comment

Comment (dsilvam) [reply dotCMS/src/main/java/com/dotmarketing/image/filter/ImageFilterAPI.java:57]: Done

File: dotCMS/src/main/java/com/dotmarketing/image/filter/SubSampleImageFilter.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+
+public class SubSampleImageFilter extends ImageFilter {
+
+
+    public String[] getAcceptedParameters() {
+        return new String[] {"w (int) specifies width", "h (int) specifies height",};
+    }
+
+    public File runFilter(final File file, Map<String, String[]> parameters) {
+        int width = parameters.get(getPrefix() + "w") != null ? Integer.parseInt(parameters.get(getPrefix() + "w")[0])
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/image/filter/SubSampleImageFilter.java:17]: I'd cache whatever `parameters.get(getPrefix() + "w")` (and `parameters.get(getPrefix() + "h")`) in a couple of variables.

File: dotCMS/src/main/java/com/dotmarketing/image/filter/ResizeImageFilter.java [hunk 5]
```diff
@@ -1,33 +1,35 @@
...
+				"i (int) interpolation"
 		};
 	}
-	public File runFilter(File file,    Map<String, String[]> parameters) {
-		double w = parameters.get(getPrefix() +"w") != null?Integer.parseInt(parameters.get(getPrefix() +"w")[0]):0;
-		double h = parameters.get(getPrefix() +"h") != null?Integer.parseInt(parameters.get(getPrefix() +"h")[0]):0;
-		
+	public File runFilter(final File file,    Map<String, String[]> parameters) {
+	    
+		int w = parameters.get(getPrefix() +"w") != null?Integer.parseInt(parameters.get(getPrefix() +"w")[0]):0;
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/image/filter/ResizeImageFilter.java:21]: Cache variables.

File: dotCMS/src/main/java/com/dotmarketing/image/filter/HsbImageFilter.java (hunk 2 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/image/filter/HsbImageFilter.java:54]: Probably it will logged in an upper level when it caught.

File: dotCMS/src/main/java/com/dotmarketing/image/filter/SubSampleImageFilter.java (hunk 4 above)
Comment (dsilvam) [reply dotCMS/src/main/java/com/dotmarketing/image/filter/SubSampleImageFilter.java]: Done

File: dotCMS/src/main/java/com/dotmarketing/image/filter/ResizeImageFilter.java (hunk 5 above)
Comment (dsilvam) [reply dotCMS/src/main/java/com/dotmarketing/image/filter/ResizeImageFilter.java]: Done

**Review by freddyucv — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM
