### PR TITLE
fixes #12381

### LINKED ISSUE #12381: Relationships: Cannot sort contents to be related with new/existing one
We're able to relate contents, however, the dialog box that opens the contents a logged-in user does not allow sorting according to the searchable fields on the list headers. 

## Expected Behavior
A logged in user should be able to sort contents according to its searchable fields, as per the list headers suggest it can be done.

## Current Behavior
Clicking on a list header wipes out the entire dialog box, and even if you close/re-open it, contents are never going to be listed unless you entirely exit the Contents portlet and go back again.

## Possible Solution
Implement the fix as per this ticket: https://my.dotcms.com/tickets/detail.dot?id=5082497f-0da5-4f20-94d7-8aa36703638f

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Go to Content Search portlet and Add a new Blog entry.
2. Go to Relationships tab and click on Relate, for the Blog-Comments relationship.
3. Once the dialog box opens, you should be able to search all Comments under the selected Language.

screen shot 2017-08-21 at 10 12 25 am 2

4. On the list headers, click on "Title" so you can sort contents by title. All contents disappear. 

screen shot 2017-08-21 at 10 12 29 am 2

## Context
Despite this was reported on this ticket https://my.dotcms.com/tickets/detail.dot?id=5082497f-0da5-4f20-94d7-8aa36703638f the proposed fix was never committed and merged to master. 

## Your Environment

* dotCMS version used: 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App Server.
* Java Brand and version: Java 8u121.
* Database and version: Postgres, SQL Server
* Application module (if apply): N/A.

### PR DESCRIPTION
**Pull request by joseorsini**
Tested on Current Master + H2 Database. 

works as expected.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java [hunk 1]
```diff
@@ -759,9 +759,13 @@ else if( fieldbcontentname.startsWith("date") ){
...
 		}
 
-		if (!UtilMethods.isSet(orderBy)){
-			orderBy = "modDate desc";
-		}
+        if (!UtilMethods.isSet(orderBy)){
+            orderBy = "modDate desc";
+        }else{
+            if(orderBy.charAt(0)=='.'){
+                orderBy = st.getVelocityVarName() + orderBy;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java]: MINOR Introduce a new variable instead of reusing the parameter "orderBy". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1226)

**Review by jcastro-dotcms — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]
