### PR TITLE
Issue 21159 using content secutiry policy header

### LINKED ISSUE #21159: Forms CSP/Security: 'unsafe-eval' is required when using dotcms forms
**Describe the bug**

When using dotcms forms on pages, this uses eval() on the successCallback JS string when it's time to execute. This will be prevented from executing if `'unsafe-eval'` is not enabled for sites using CSP..

**To Reproduce**
1. Create a form contentlet, doing whatever for success callback
2. Add form to a page
3. Submit form
4. Error displays

**Expected behavior**
`eval()` shouldn't be needed. Executing the success callback without `eval()` would be ideal.

**Screenshots**

image

Context: https://github.com/dotCMS/core-web/blob/2e0b6195de6ee470833722ccdb074c9dfac1fd3c/libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-form/dot-form.tsx#L179

Edit: Being CSP conscious, the script tags being injected with dotcms forms should also come with a hash. As a workaround, I had to take the code generated by `content_form.vtl` so I could inject a generated nonce we are using.

image

### PR DESCRIPTION
**Pull request by freddyucv**
Use the ContentSecurityPolicy.header config properties to set the value for the Content-Security-Policy header

To use the Content Security Policy set the properties ContentSecurityPolicy.header in the config file
like default-src 'self'
To use nonce set like script-src {script-src nonce} or style-src {style-src nonce}
To use hash set like script-src {script-src hash}

### CODE REVIEW

**Review by wezell — CHANGES_REQUESTED** [review]
I like this change except for the random class, we do not need this.  We should always try to use what is already available to us in the JDK or in well-tested common utils rather than write our own implementations of things, e.g.

```
String key = org.apache.commons.lang.RandomStringUtils.randomAlphanumeric(20);
```

**Comment by freddyucv** [comment]
> I like this change except for the random class, we do not need this. We should always try to use what is already available to us in the JDK or in well-tested common utils rather than write our own implementations of things, e.g.
> 
> ```
> String key = org.apache.commons.lang.RandomStringUtils.randomAlphanumeric(20);
> ```

done https://github.com/dotCMS/core/pull/21337/files#diff-28c06d2a8e3b90515eebb6eda4dd60f70d823d8164052d79e956963669cf0cb6R52

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java [hunk 1]
```diff
@@ -100,7 +102,13 @@ protected void processException(final User user, final String name, final ParseE
     public final String eval() {
         try(ByteArrayOutputStream out = new ByteArrayOutputStream(4096)) {
             serve(out);
-            return new String(out.toByteArray());
+
+            if (ContentSecurityPolicyUtil.isConfig()) {
+                final String htmlCode = new String(out.toByteArray());
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java:107]: you should use a Enconding here

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java [hunk 2]
```diff
@@ -100,7 +102,13 @@ protected void processException(final User user, final String name, final ParseE
...
+                return ContentSecurityPolicyUtil.apply(htmlCode);
+            } else {
+                return new String(out.toByteArray());
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java:110]: same here

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+import com.dotmarketing.util.Config;
+import com.dotmarketing.util.PageMode;
+import com.dotmarketing.util.UtilMethods;
+import java.util.Map;
+import java.util.Map.Entry;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+import org.apache.commons.lang.RandomStringUtils;
+
+public class ContentSecurityPolicyUtil {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:16]: Doc

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+
+    final static Map<String, ContentSecurityPolicyResolver> contentSecurityPolicyResolvers;
+    public static final int RANDOM_STRING_LENGTH = 20;
+
+    private static String NONCE_REQUEST_ATTRIBUTE = "NONCE_REQUEST_ATTRIBUTE";
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:21]: it does not looks such as constant

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+    }
+
+    public static boolean isConfig() {
+        final String contentSecurityPolicyHeader = getContentSecurityPolicyHeader();
+
+        return UtilMethods.isSet(contentSecurityPolicyHeader);
+    }
+
+    private static String getContentSecurityPolicyHeader() {
+        return Config.getStringProperty(
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:93]: it seems to be handle in every request, we have seen in other context this could be clock, so it would be better to use the lazy

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+        return htmlCode.replaceAll("<style", String.format("<style nonce='%s'",nonce));
+    }
+
+    private static String calculateNonceHeaderToStyle(final String header) {
+        final String nonce = getNonceFromCurrentRequest();
+        return header.replace("{style-src nonce}", String.format("'nonce-%s'",nonce));
+    }
+
+    private static String getNonceFromCurrentRequest() {
+        final HttpServletRequest request = HttpServletRequestThreadLocal.INSTANCE.getRequest();
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:166]: this could be null, may need to check

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+        final String nonce = (String) request.getAttribute(NONCE_REQUEST_ATTRIBUTE);
+        return nonce;
+    }
+
+    @FunctionalInterface
+    interface HeaderResolver {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:172]: If this is not public, you may replace with Function<String, String> and the HtmlCodeResolver with Function2<String, String, String>

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+        String resolve(final String header);
+    }
+
+    @FunctionalInterface
+    interface HtmlCodeResolver {
+        String resolve(final String contentSecurityPolicyConfig, final String htmlCode);
+    }
+
+    private static class ContentSecurityPolicyResolver {
+        HeaderResolver headerResolver;
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:182]: seems such as this could be final

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java (hunk 1 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java:107]: UTF-8

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 3 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:77]: done https://github.com/dotCMS/core/pull/21337/commits/cd30c4562685c3ad46ac474252bb6f0396bcf387

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 4 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java]: done https://github.com/dotCMS/core/pull/21337/commits/b1ced9fd711e813176c2dad89b70d29818946963

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 5 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java]: done https://github.com/dotCMS/core/pull/21337/commits/b556eaf241e8a017d59a0927d77c4c025839bb2b

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 6 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java:214]: done https://github.com/dotCMS/core/pull/21337/commits/c8f185a995f8f27f3c0e841a257172acb0f7a94d#diff-28c06d2a8e3b90515eebb6eda4dd60f70d823d8164052d79e956963669cf0cb6R216

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 7 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java]: done https://github.com/dotCMS/core/pull/21337/commits/c8f185a995f8f27f3c0e841a257172acb0f7a94d#diff-28c06d2a8e3b90515eebb6eda4dd60f70d823d8164052d79e956963669cf0cb6R216

File: dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java (hunk 8 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/security/ContentSecurityPolicyUtil.java]: done https://github.com/dotCMS/core/pull/21337/commits/bffbe06951439bc17ef47dea074b0d441d470cc1

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java (hunk 1 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityModeHandler.java]: done https://github.com/dotCMS/core/pull/21337/commits/f13b003205986c038e04ef138375ec610766da14

**Review by jdotcms — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
