### PR TITLE
#22094 New upgrade task to update No HTML regex

### LINKED ISSUE #22094: No HTML RegEx Invalidates Period (.) When Used
**Describe the bug**
When you add the "No HTML" validation RegEx to a field in a content type then try to save a contentlet with a period in that field (.) the RegEx is triggered and the period is treated like HTML.  

**To Reproduce**
1. Go to demo.dotcms.com
2. Add the "No HTML" RegEx to a text field in a content type
3. Create a new contentlet of that type that contains a sentence with a period

**Expected behavior**
Periods alone would not trigger the "No HTML" RegEx invalidation.
**Screenshots**

Screen Shot 2022-04-27 at 7 50 12 AM
Screen Shot 2022-04-27 at 7 50 32 AM

Screen Shot 2022-04-27 at 7 50 44 AM

**Desktop (please complete the following information):**
 - Version 22.03

**Additional context**
As reported by a customer: https://dotcms.zendesk.com/agent/tickets/107136

### PR DESCRIPTION
**Pull request by nollymar**

### CODE REVIEW

**Review by alfredo-dotcms — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220512UpdateNoHTMLRegexValue.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+ * @author nollymar
+ */
+public class Task220512UpdateNoHTMLRegexValue implements StartupTask {
+
+    private static final String NEW_NOHTML_REGEX = "^[^<><|>]+$";
+    static final String OLD_NOHTML_REGEX = "[^(<[.\n"
+            + "]+>)]*";
+
+    @Override
+    public boolean forceRun() {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220512UpdateNoHTMLRegexValue.java:22]: shouldn't handle the connection close with annotation?

**Review by jdotcms — APPROVED** [review]

**Review by jcastro-dotcms — APPROVED** [review]
