### PR TITLE
#21652 Webp when Safari >=14

### LINKED ISSUE #21652: [WebP] : Image file using the WebP filter loads with white background in Safari
New versions of safari (14 and above) can render webp. We need to update our BinaryExporterServlet to respect the Safari version and only send a JPEG when it is < v14.

---

This was:

Reported via Support ticket: [106318](https://dotcms.zendesk.com/agent/tickets/106318)
Reproducible as of dotCMS 5.3.8.8, up to latest master (22.01)

Displaying a .PNG file on the an HTML Page in the front-end works as expected. However, if the `/webp/` filter is used, the very same image will display a white background in Safari.

**To Reproduce**
Please ask me for the specific image file to use for reproducing this problem:
1. Upload the image file provided by me.
2. Create an Advanced Template with the following data:
```html
<html>
    <header>
        <title>Test Template</title>
    </header>
    <body>
        <h1>This is a Test Template</h1>
        <div style='background-color: lightblue;'>
            <picture class="MenuItemDetail_hero__bg__2981O hidden lg:block self-end z-10 relative pointer-events-none">
                <source type="image/webp" srcset="https://demo.dotcms.com/{dA-LINK-TO-TEST-IMAGE}/600w/webp/75q">
                <img src="https://demo.dotcms.com/{dA-LINK-TO-TEST-IMAGE}/600w/webp/75q" alt="Alt text for this image">
            </picture>
        </div>
    </body>
</html>
```
3. Open up the page in the front-end using Firefox or Chrome. The image's background is transparent, which is expected.
4. However, in Safari, the image's background is blank.

**Expected behavior**
The WebP filter should work as expected in Safari as well.

**Additional context**
The only currently valid workaround is to remove the WebP filter. So, instead of doing this:
```
"https://demo.dotcms.com/{dA-LINK-TO-TEST-IMAGE}/600w/webp/75q"
```
Do this:
```
"https://demo.dotcms.com/{dA-LINK-TO-TEST-IMAGE}/600w"
```

### PR DESCRIPTION
**Pull request by dsilvam**
Fix condition for when delivering webp. Supported since Safari 14 and iOS 14

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/servlets/BinaryExporterServlet.java [hunk 1]
```diff
@@ -385,7 +385,9 @@ public void doGet(HttpServletRequest req, HttpServletResponse resp) throws Servl
 
       if(params.get("quality_q")!=null) {
       	final UserAgent userAgent = new UserAgent(req.getHeader("user-agent"));
-        if(userAgent.getBrowser() == Browser.SAFARI || userAgent.getOperatingSystem().getGroup() == OperatingSystem.IOS){
+        if((userAgent.getBrowser() == Browser.SAFARI
+				&& Integer.parseInt(userAgent.getBrowserVersion().getMajorVersion())<14)
+				|| userAgent.getOperatingSystem().getGroup() == OperatingSystem.IOS){
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotmarketing/servlets/BinaryExporterServlet.java:390]: ios 14 can support webp as well, we need to remove the condition.

https://caniuse.com/?search=webp

File: dotCMS/src/integration-test/java/com/dotmarketing/servlets/BinaryExporterServletTest.java [hunk 2]
```diff
@@ -190,6 +195,58 @@ public void requestGifFile()
...
+    public static Object[][] testCasesWebp() {
+        return new Object[][] {
+                { "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15", "image/webp" },
+                { "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15", "image/jpeg" },
+
+        };
+    }
+
+    @UseDataProvider("testCasesWebp")
+    @Test
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotmarketing/servlets/BinaryExporterServletTest.java:208]: doc?

**Review by freddyucv — APPROVED** [review]

**Review by jcastro-dotcms — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotmarketing/servlets/BinaryExporterServletTest.java (hunk 2 above)
Comment (dsilvam) [reply dotCMS/src/integration-test/java/com/dotmarketing/servlets/BinaryExporterServletTest.java:217]: Done

**Review by freddyucv — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]
