### PR TITLE
#20174 - fix postgre  columns on upgrade task

### LINKED ISSUE #20174: No "storage" table created when coming from an old version
When running an upgrade and the upgrade task https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210320AddHashRefColumnStorageTable.java gets executed, it returns `true` in this line https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210320AddHashRefColumnStorageTable.java#L21, which makes the task to get executed. 
The issue is that the `storage` table hasn't been created at this point and it fails to upgrade. 

**Expected:**
`storage` table needs to be created in an upgrade task when coming from an old version. 

Reproduced in master.

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
Correction on the postgres column definitions

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java [hunk 1]
```diff
@@ -38,8 +38,8 @@ public String getPostgresScript() {
                 + "    path        varchar(255) not null,\n"
                 + "    group_name varchar(255) not null,\n"
                 + "    hash       varchar(64) not null,\n"
-                + "    metadata   text not null,\n"
                 + "    mod_date   timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,\n"
+                + "    hash_ref   varchar(64), \n"
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java:42]: do the sql files need to be modified?

Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java:42]: This should be a New UT? since a customer could be on latest release and needs this fix, for example our internal servers.

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java:42]: > do the sql files need to be modified?

No the SQL files were fine

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java:42]: > This should be a New UT? since a customer could be on latest release and needs this fix, for example our internal servers.

ok. Then let's make it a new UT and remove the old one.

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java (hunk 1 above)
Comment (nollymar) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task210319CreateStorageTable.java:42]: It means, this UT hasn't made it to any release yet

**Review by erickgonzalez — APPROVED** [review]
