### PR TITLE
#21619 Changes on Config class 

### LINKED ISSUE #21619: ContentTypeFactoryImpl  Getting Config values cause unneeded load
In our containerized world, we do not need to support on the fly configuration changes or configuration reloading any longer.  Instead of relying on apache classes, file watchers, and other blocking patterns, we should just read in the configuration at startup as an immutable map and use it as needed.

For example, in the `ContentTypeFactoryImpl` we call this whenever the class is inited (which happens a lot as it is not a singleton).
```
  final boolean LOAD_FROM_CACHE=Config.getBooleanProperty("LOAD_CONTENTTYPE_DETAILS_FROM_CACHE", true);
```
It turns out, our Config class is not really that performant.  In this case, I see this a performance hotspot as java builds the exception's stack trace.

Screen Shot 2022-01-27 at 10 47 15 AM

There are multiple places in our code where you can see performance issues with our use of the class.
`org.apache.commons.configuration.AbstractConfiguration`

If we ever need a mechanism to update config on the fly in the future, we can write something then to do so by replacing the map, etc.

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
Isolating changes to investigate issues running CURL tests

### CODE REVIEW

**Review by nollymar — APPROVED** [review]

**Review by jcastro-dotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/contenttype/business/ContentTypeFactoryImpl.java [hunk 1]
```diff
@@ -626,7 +628,8 @@ private boolean dbDelete(final ContentType type) throws DotDataException {
     return true;
   }
 
-  final boolean LOAD_FROM_CACHE=Config.getBooleanProperty("LOAD_CONTENTTYPE_DETAILS_FROM_CACHE", true);
+  final Lazy<Boolean> LOAD_FROM_CACHE=Lazy.of(()->Config.getBooleanProperty(
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/contenttype/business/ContentTypeFactoryImpl.java:631]: good

**Review by jdotcms — APPROVED** [review]
