### PR TITLE
fix(seo): title and description truncation with ellipsis #26531

### LINKED ISSUE #26531: Truncated SEO Titles need Ellipsis
[](https://mrkr.io/s/653a962b14d46bc022f8b4e8/0)

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653a962b14d46bc022f8b4ef_7f8e757eb3a116a2?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 118.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### PR DESCRIPTION
**Pull request by valentinogiardino**
Fix SEO title and description truncation with ellipsis

### Proposed Changes
* Truncate SEO titles and descriptions with ellipsis after specified character limits.
* Ensure consistent handling of SEO_LIMITS for title and description truncation.

This PR fixes #26531

### Screenshots
Captura de pantalla 2024-07-18 a la(s) 14 41 56
Captura de pantalla 2024-07-18 a la(s) 14 42 10
Captura de pantalla 2024-07-18 a la(s) 14 42 22
Captura de pantalla 2024-07-18 a la(s) 14 48 29

This PR fixes: #26531

### CODE REVIEW

File: core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts [hunk 1]
```diff
@@ -70,13 +70,29 @@ export class DotResultsSeoToolComponent implements OnInit, OnChanges {
     noFavicon = false;
 
     ngOnInit(): void {
+        const truncateText = (text: string, limit: number) => {
```
Comment (oidacra) [inline core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts:73]: This can be converted to a utility, and there add unit tests to check if you have all you need.

File: core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts [hunk 2]
```diff
@@ -71,12 +71,14 @@ export class DotResultsSeoToolComponent implements OnInit, OnChanges {
 
     ngOnInit(): void {
         const title =
-            this.seoOGTags?.['og:title']?.slice(0, SEO_LIMITS.MAX_OG_TITLE_LENGTH) ||
-            this.seoOGTags?.title?.slice(0, SEO_LIMITS.MAX_OG_TITLE_LENGTH);
+            ellipsizeText(this.seoOGTags?.['og:title'], SEO_LIMITS.MAX_OG_TITLE_LENGTH) ||
+            ellipsizeText(this.seoOGTags?.title, SEO_LIMITS.MAX_OG_TITLE_LENGTH);
```
Comment (zJaaal) [inline core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts:75]: if think is easier to read if we do something like:

```javascript
const title = this.seoOGTags?.['og:title'] || this.seoOGTags?.title;

const ellipsizedTitle = ellipsizeText(title, SEO_LIMITS.MAX_OG_TITLE_LENGTH);
```

File: core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts [hunk 3]
```diff
@@ -71,12 +71,14 @@ export class DotResultsSeoToolComponent implements OnInit, OnChanges {
...
 
         const description =
-            this.seoOGTags?.['og:description']?.slice(0, SEO_LIMITS.MAX_OG_DESCRIPTION_LENGTH) ||
-            this.seoOGTags?.description?.slice(0, SEO_LIMITS.MAX_OG_DESCRIPTION_LENGTH);
+            ellipsizeText(
+                this.seoOGTags?.['og:description'],
+                SEO_LIMITS.MAX_OG_DESCRIPTION_LENGTH
+            ) || ellipsizeText(this.seoOGTags?.description, SEO_LIMITS.MAX_OG_DESCRIPTION_LENGTH);
```
Comment (zJaaal) [inline core-web/libs/portlets/edit-ema/ui/src/lib/dot-results-seo-tool/dot-results-seo-tool.component.ts:81]: Same as my comment above

File: core-web/libs/utils/src/lib/dot-utils.spec.ts [hunk 4]
```diff
@@ -67,3 +67,38 @@ describe('Dot Utils', () => {
...
+        const text = 'Thisisaverylongwordthatneedstruncation';
+        const truncated = 'Thisisaverylongw...';
+        expect(ellipsizeText(text, 17)).toEqual(truncated);
+    });
+
+    it('should handle edge cases where limit is 0', () => {
+        const text = 'Any text';
+        const truncated = '...';
+        expect(ellipsizeText(text, 0)).toEqual(truncated);
+    });
```
Comment (zJaaal) [inline core-web/libs/utils/src/lib/dot-utils.spec.ts:103]: what about negatives? or not numbers?

File: core-web/libs/utils/src/lib/dot-utils.ts [hunk 5]
```diff
@@ -94,3 +94,24 @@ export function getImageAssetUrl(contentlet: DotCMSContentlet): string {
...
+    }
+
+    if (text.length <= limit) {
+        return text;
+    }
+
+    const truncated = text.slice(0, limit);
+
+    return truncated.slice(0, truncated.lastIndexOf(' ')) + '...';
+}
```
Comment (zJaaal) [inline core-web/libs/utils/src/lib/dot-utils.ts:117]: Take a look at this function, remember to validate if it is negative or not a number.

```javascript
const truncate = (text, limit = 25) => {
    const regexString = `^.{0,${limit}}`; // This will only match any char from the start of the string to the limit

    const regex = new RegExp(regexString, 'g'); // Create the regex

    return text.match(regex)[0]; // Get the match 
};
```

Comment (zJaaal) [reply core-web/libs/utils/src/lib/dot-utils.ts:117]: Here are some test cases you can test:

```javascript
console.log(truncate('This is a test', 4)); // 'This'

console.log(truncate('This is a test', 5)); // 'This '

console.log(truncate('This is a test', 6)); // 'This i'

console.log(truncate('This is a test', 0)); // ''

console.log(truncate('This is a test', 30)); // 'This i a test'

```

**Review by zJaaal — CHANGES_REQUESTED** [review]

File: core-web/libs/utils/src/lib/dot-utils.ts (hunk 5 above)
Comment (valentinogiardino) [reply core-web/libs/utils/src/lib/dot-utils.ts]: I believe that if there are spaces in the text, the truncation should occur at the previous word rather than splitting words. It looks better to me this way.

**Review by zJaaal — APPROVED** [review]

**Review by oidacra — APPROVED** [review]

File: core-web/libs/utils/src/lib/dot-utils.ts [hunk 6]
```diff
@@ -94,3 +94,24 @@ export function getImageAssetUrl(contentlet: DotCMSContentlet): string {
...
 }
+
+/**
+ * This method is used to truncate a text with ellipsis.
+ * It ensures that the text is truncated at the nearest word boundary.
+ * @param text - The text to be truncated.
+ * @param limit - The maximum length of the truncated text.
+ * @returns The truncated text with ellipsis if it exceeds the limit, otherwise the original text.
+ */
+export function ellipsizeText(text: string, limit: number): string {
```
Comment (rjvelazco) [inline core-web/libs/utils/src/lib/dot-utils.ts:105]: We could use this to create an Angular Pipe!

**Review by rjvelazco — APPROVED** [review]
