### PR TITLE
#20194 Response with the same status that the remote response

### LINKED ISSUE #20194: Problems requesting token from a remote server
When you request a token to a remote server, but this with a invalid credentials, we are getting an error here, we need to improve this message 
image

**Expected behavior**
Need to catch this exception and show a better feedback to the end user at UI level

**Desktop (please complete the following information):**
Tested on release-21.04 // Postgres // FF

### PR DESCRIPTION
**Pull request by freddyucv**
Response according to the remote response

### CODE REVIEW

**Review by wezell — APPROVED** [review]
Looks good and makes sense

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/authentication/ApiTokenResource.java [hunk 1]
```diff
@@ -290,7 +291,10 @@ public final Response getRemoteToken(@Context final HttpServletRequest httpReque
                 }
             }
 
-            return Response.ok(response.readEntity(String.class)).build();
+            return Response
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/authentication/ApiTokenResource.java:294]: I think a test can be included

Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/authentication/ApiTokenResource.java:294]: it already have failing test

https://raw.githack.com/dotCMS/test-results/master/projects/core/current/curl/postgres/reports/html/ApiToken_Resource.html

**Review by nollymar — APPROVED** [review]
