### PR TITLE
fixes #14052 2nd try

### LINKED ISSUE #14052: [REST] Return proper status for ES API REST endpoint if no query is passed in
We're returning Error 500 if we hit the ES API REST endpoint if the request doesn't have a JSONObject as ES Query. Even passing in an empty string, or no data at all, it throws error 500. 

## Possible Solution
Return Error 400 Bad Request response if no query is passed in.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. On a browser, hit https://demo.dotcms.com/api/es/search.
2. An error 500 is thrown in log files and on browser.

Stacktrace: https://gist.github.com/joseorsini/d4eab540b159e10a564e5fa9ee705380

## Your Environment

* dotCMS version used: 4.3.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any supported application server.
* Java Brand and version: Any supported Java 8 version.
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

### PR DESCRIPTION
**Pull request by joseorsini**
Tested against master:

Notes to reviewer: 

- Exception is created manually so the ExceptionMapperUtil returns a JSONObject with the proper error messages. Passing in only a null entity and a hardcoded message will make the application to return an Error 400 page from application server itself.
- After further discussion with R&D, this ES API endpoint should be available for Enterprise-licensed environments.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/rest/elasticsearch/ESContentResourcePortlet.java [hunk 1]
```diff
@@ -40,14 +43,22 @@ public Response search(@Context HttpServletRequest request, @Context HttpServlet
 		User user = initData.getUser();
 		ResourceResponse responseResource = new ResourceResponse(initData.getParamsMap());
 
+		if(LicenseUtil.getLevel() < LicenseLevel.STANDARD.level){
+			final String noLicenseMessage = "Unable to execute ES API Requests. Please apply an Enterprise License";
+			final RuntimeException e1 = new RuntimeException(noLicenseMessage);
+			Logger.warn(this.getClass(), noLicenseMessage);
+			return ExceptionMapperUtil.createResponse(e1, Response.Status.BAD_REQUEST);
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/elasticsearch/ESContentResourcePortlet.java]: Man you can do something like:

```
Response
                .status(status)
                .entity(map("message", noLicenseMessage))
                .header("error-message", noLicenseMessage)
                .build();
```

**Review by jdotcms — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/dotcms/rest/elasticsearch/ESContentResourcePortlet.java (hunk 1 above)
Comment (joseorsini) [reply dotCMS/src/main/java/com/dotcms/rest/elasticsearch/ESContentResourcePortlet.java]: ok then, I'll update it first thing in the morning.

**Review by jdotcms — APPROVED** [review]

**Review by jgambarios — CHANGES_REQUESTED** [review]

**Review by jgambarios — APPROVED** [review]
