### PR TITLE
fix(WorkflowAPI) File upload rejects any file with .. in their name Refs: #33785

### LINKED ISSUE #33785: [DEFECT] File upload validation rejects filenames with '..' in workflow endpoint
## Description

The `IllegalTraversalFilePathValidator` is incorrectly rejecting legitimate filenames that contain '..' when uploading files through the workflow actions endpoint. This prevents users from uploading files with valid names like macOS screenshot timestamps.

## Steps to Reproduce

1. Send a POST request to `/api/v1/workflow/actions/default/fire/NEW`
2. Include a file in the formData with filename: `Screenshot 2025-03-18 at 4.09.02 p.m..png`
3. Observe the security validation error

## Current Behavior

The file upload is rejected with:
```
INFO  util.SecurityLogger - class com.dotcms.security.multipart.IllegalTraversalFilePathValidator : The filename: 'Screenshot 2025-03-18 at 4.09.02 p.m..png' is invalid
```

## Expected Behavior

The file should be accepted since:
- The '..' appears within the filename itself (part of "p.m."), not as a path component
- There are no path separators (/ or \) adjacent to the '..'
- This is a legitimate macOS screenshot filename pattern with time abbreviations

## Impact

- Users cannot upload macOS screenshots with default naming that includes "a.m." or "p.m."
- Blocks common content creation workflows using screenshots
- Affects any file with legitimate '..' in the name
- Creates poor user experience with unclear error messaging

## Technical Details

**Endpoint:** `POST /api/v1/workflow/actions/default/fire/NEW`  
**Request Type:** multipart/form-data with file upload  
**Component:** `com.dotcms.security.multipart.IllegalTraversalFilePathValidator`

**Root Cause:** The validator likely checks for '..' presence without context of whether it's part of a path traversal attempt or just part of the filename.

**Suggested Fix:** Update validation logic to:
1. Check if '..' is preceded or followed by path separators (/, \)
2. Allow '..' when it's part of the filename with spaces or other non-path characters
3. Consider normalizing the path first and checking if it escapes the intended directory
4. Validate against the actual path component, not the full filename

**Example Valid Filenames Being Rejected:**
- `Screenshot 2025-03-18 at 4.09.02 p.m..png` (macOS screenshot)
- `Meeting notes 3.15.24 ..draft.docx`
- `Report Q1..Q2 2024.pdf`

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
### Proposed Changes
* Handle more cases, allowing files with .. in the file name, but also preventing attacks

This PR fixes: #33785

This PR fixes: #33785

### CODE REVIEW

**Review by dario-daza — APPROVED** [review]

File: dotcms-integration/src/test/java/com/dotcms/security/multipart/SecureFileValidatorTest.java [hunk 1]
```diff
@@ -73,4 +71,19 @@ public void Test_Validate_Illegal_Path_ext()
         secureFileValidator.validate(filename);
     }
 
+
+    @Test
```
Comment (nollymar) [inline dotcms-integration/src/test/java/com/dotcms/security/multipart/SecureFileValidatorTest.java:82]: Can you add a comment to understand the expected output?

File: dotCMS/src/main/java/com/dotcms/security/multipart/IllegalTraversalFilePathValidator.java [hunk 2]
```diff
@@ -12,10 +12,29 @@ public class IllegalTraversalFilePathValidator implements SecureFileValidator {
...
+     */
+    private boolean containsPathSeparators(final String fileName) {
+        return fileName.contains("/") || fileName.contains("\\");
+    }
+
+    /**
+     * Checks for actual path traversal patterns, not just any occurrence of ".."
+     * Allows filenames like "kek .. lol.png" but blocks "../../file.png"
+     */
+    private boolean containsPathTraversal(final String fileName) {
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/security/multipart/IllegalTraversalFilePathValidator.java:33]: Does it work if there are more than 2 dots? for example: `lol.....png`, `test...again...png`, `.....png`?

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/security/multipart/IllegalTraversalFilePathValidator.java:33]: yes it does

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/security/multipart/IllegalTraversalFilePathValidator.java:33]: This code prevents using ".." to access upper-level directories; more than two dots  doesn't mean anything

File: dotcms-integration/src/test/java/com/dotcms/security/multipart/SecureFileValidatorTest.java (hunk 1 above)
Comment (fabrizzio-dotCMS) [reply dotcms-integration/src/test/java/com/dotcms/security/multipart/SecureFileValidatorTest.java:82]: done

**Review by nollymar — APPROVED** [review]
