### PR TITLE
#20913 get filters and apply them in the order sent

### LINKED ISSUE #20913: Respect the order of params passed to /dA
The /dA call does a good job of simplifying some of our image filters, but the order of operations are hard coded in the Servlet.  This means that if you try to `resize` AND apply `webp`, it will not work and the resulting image is `.png`

This should be a webp image:

https://demo.dotcms.com/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/270w/webp/diving.jpg

WebP only works if you use the quality param:

https://demo.dotcms.com/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/270w/50q/diving.jpg

What we need to do is respect the order of the param arguments and based upon them, run the filters in that order.

### PR DESCRIPTION
**Pull request by erickgonzalez**
Refactor on how to apply the filters when it's called by `/dA`, we need to apply them in the order they were sent.

So here we're getting the filters in order from the URI, after that when creating the path to apply the filters, check each filter to be appended in the right order.

Note: I was not able to found out a way to create a test for this.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java [hunk 1]
```diff
@@ -321,8 +321,12 @@ private void doForward(final HttpServletRequest request,
 
       final StringBuilder pathBuilder = new StringBuilder(path)
               .append(id).append("/byInode/true");
+        //This logic is to get the filters to apply in the order were sent
+        final boolean isFieldNameAtUri = id.split(StringPool.FORWARD_SLASH)[2].equalsIgnoreCase(fieldName);
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java:325]: is not dangerous to think it is always at least 2 elements?

File: dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java [hunk 2]
```diff
@@ -357,24 +361,43 @@ private void addImagePath(final int width,
...
+                            final String[] filters) {
         if (isImage) {
-
-            if (quality > 0) {
-                pathBuilder.append("/quality_q/" + quality);
-            } else {
-                pathBuilder.append(jpeg ? "/jpeg_q/75" : StringPool.BLANK);
-                pathBuilder.append(webp ? "/webp_q/75" : StringPool.BLANK);
-                pathBuilder.append(jpeg && jpegp ? "/jpeg_p/1" : StringPool.BLANK);
+            for(String filter : filters){
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java:367]: set to final

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java (hunk 1 above)
Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java:325]: yes, it always comes the id and the fieldName

File: dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java (hunk 2 above)
Comment (erickgonzalez) [reply dotCMS/src/main/java/com/dotmarketing/servlets/ShortyServlet.java:367]: it can't be final because it's being reuse on the next line:
`filter = StringPool.FORWARD_SLASH + filter;`

**Review by freddyucv — COMMENTED** [review]
any test?

**Review by nollymar — APPROVED** [review]

**Review by freddyucv — APPROVED** [review]
