### PR TITLE
#19827 Use default lang if one not provided

### LINKED ISSUE #19827: GraphQL API is requring language
If you ask containers from the page without passing the language:

```
query Page {
  page(url: "index") {
    containers {
      name
    }
  }
}
```

You get an error:

```
15:01:19.060  ERROR page.ContainersDataFetcher - null
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552) ~[?:1.8.0_211]
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_211]
	at com.dotcms.graphql.datafetcher.page.ContainersDataFetcher.get(ContainersDataFetcher.java:40) ~[dotcms_master_107f2eb.jar:?]
	at com.dotcms.graphql.datafetcher.page.ContainersDataFetcher.get(ContainersDataFetcher.java:1) ~[dotcms_master_107f2eb.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) ~[graphql-java-13.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.
```

You need to pass the language like:

```
{
  page(url: "index", languageId: "1") {
    containers {
      name
    }
  }
}
```

It should default to the default language.

### PR DESCRIPTION
**Pull request by dsilvam**
Use default lang if one not provided. 
Added postman test that request page's container without passing the languageId.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageDataFetcher.java [hunk 1]
```diff
@@ -43,7 +43,9 @@ public Contentlet get(final DataFetchingEnvironment environment) throws Exceptio
                     .getHttpServletResponse();
 
             final String url = environment.getArgument("url");
-            final String languageId = environment.getArgument("languageId");
+            final String languageId = UtilMethods.isSet((String) environment.getArgument("languageId"))
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageDataFetcher.java:46]: Cache argument in a String variable

**Review by jdotcms — APPROVED** [review]

**Review by freddyucv — APPROVED** [review]

**Review by nollymar — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]

**Comment by erickgonzalez** [comment]
Approving but check tests, it didn't run.
