### PR TITLE
Avoid to run the bundles when the tar.gzip file already exists

### LINKED ISSUE #20878: Not re-genarate the bundle tar.gzip file when retyr a PP
**Describe the bug**
After the PP performance chance in release-21.05, when try to retry a PP bundle the tar.gzip file is re-generate again.

**Expected behavior**
The tar.gzip file should not be re-generate when a PP bundle is retrying

### PR DESCRIPTION
**Pull request by freddyucv**
Avoid running the bundlers and create the Bundle tar.gzip file when it already exists.

We already have a test failing for this bug

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/publishing/PublisherAPIImpl.java [hunk 1]
```diff
@@ -79,36 +79,32 @@ final public PublishStatus publish ( PublisherConfig config, PublishStatus statu
...
+                            Logger.info(this, "Writing bundle.xml file");
+                            BundlerUtil.writeBundleXML(config, output);
+                        }
 
-                    // If the bundle exists and we are retrying to push the bundle
-                    // there is no need to run all the bundlers again.
-                    if (!bundleExists || !publishAuditAPI.isPublishRetry(config.getId())) {
+                        // If the bundle exists and we are retrying to push the bundle
+                        // there is no need to run all the bundlers again.
+                        //if (!bundleExists || !publishAuditAPI.isPublishRetry(config.getId())) {
```
Comment (erickgonzalez) [inline dotCMS/src/main/java/com/dotcms/publishing/PublisherAPIImpl.java:107]: this line can be removed

Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/publishing/PublisherAPIImpl.java]: done https://github.com/dotCMS/core/pull/20883/commits/597ac01ccceef14985485a785e5de9a4e0584623

**Review by jdotcms — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]
