### PR TITLE
Adding preview menu fix

### LINKED ISSUE #26195: Preview Menu Placement is Off
[](https://mrkr.io/s/650b2eec41bac6db3aab0b0a/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

The Preview Menu was meant to open below the line, and also it's loading pretty far to the right.

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fecotourism-in-costa-rica%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/650b2eec41bac6db3aab0b0d_ed6cdbbdf4e1650e?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### PR DESCRIPTION
**Pull request by manuelrojas**
### Summary
🆕🛠️✅

This pull request improves the alignment of the device selector menu in the SEO tab of the edit page portlet. It adds a new `target` parameter to the `openMenu` methods and events of the `DotDeviceSelectorSeoComponent` and the `DotTabButtonsComponent` classes. It also updates the `DotEditPageStateControllerSeoComponent` class and the test cases for the `DotTabButtonsComponent` to handle the new parameter.

> _We open the menu of doom_
> _With the target of our wrath_
> _We align the overlay of gloom_
> _With the tab that seals our path_

### Walkthrough
*  Add optional `target` parameter to `openMenu` method of `DotDeviceSelectorSeoComponent` to pass the target element to the overlay panel component ([link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-764ca6ad6e5980c9f3ddfceee590e38984f85ed0ac63dba184a37e2ef955c5c4L152-R153))
*  Update `menuOpenActions` property and `handleMenuOpen` method of `DotEditPageStateControllerSeoComponent` to reflect the new signature of `openMenu` method of `DotDeviceSelectorSeoComponent` and pass the `target` parameter to the corresponding menu opening actions ([link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-525d72b2f066845092b3f8e47374c999304f59f8d049c44bb98ff91fddcac347L94-R102), [link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-525d72b2f066845092b3f8e47374c999304f59f8d049c44bb98ff91fddcac347L249-R261))
*  Modify `openMenu` output property of `DotTabButtonsComponent` to include an optional `target` property with the target element and its closest tab container element ([link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-bf8bca39c1833ed819e57a1eb3902053bef01922de6f904b73c5a7e4ad6a5e53L31-R35))
*  Emit `openMenu` event with the `target` property in `onClickDropdown` method of `DotTabButtonsComponent` ([link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-bf8bca39c1833ed819e57a1eb3902053bef01922de6f904b73c5a7e4ad6a5e53L85-R92))
*  Update test cases in `dot-tab-buttons.component.spec.ts` to test the new functionality of `DotTabButtonsComponent` and the `openMenu` event emission with the `target` property ([link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-103bc995132680fbeaa0e1e9900a7b0d8918456776184e6d67884a4d7c1f1584R20), [link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-103bc995132680fbeaa0e1e9900a7b0d8918456776184e6d67884a4d7c1f1584L67-R80), [link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-103bc995132680fbeaa0e1e9900a7b0d8918456776184e6d67884a4d7c1f1584L76-R103), [link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-103bc995132680fbeaa0e1e9900a7b0d8918456776184e6d67884a4d7c1f1584L92-R115), [link](https://github.com/dotCMS/core/pull/26264/files?diff=unified&w=0#diff-103bc995132680fbeaa0e1e9900a7b0d8918456776184e6d67884a4d7c1f1584L129-R156))

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
image  |  image

### CODE REVIEW

**Review by oidacra — APPROVED** [review]

**Review by rjvelazco — APPROVED** [review]

**Review by zJaaal — APPROVED** [review]

**Review by hmoreras — APPROVED** [review]

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-device-selector-seo/dot-device-selector-seo.component.ts [hunk 1]
```diff
@@ -149,8 +149,8 @@ export class DotDeviceSelectorSeoComponent implements OnInit {
      * Opens the device selector menu
      * @param event
      */
-    openMenu(event: Event) {
-        this.overlayPanel.toggle(event);
+    openMenu(event: Event, target?: HTMLElement) {
```
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-device-selector-seo/dot-device-selector-seo.component.ts:152]: Does this method have tests?

**Review by fmontes — APPROVED** [review]

File: core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-device-selector-seo/dot-device-selector-seo.component.ts (hunk 1 above)
Comment (manuelrojas) [reply core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/seo/components/dot-device-selector-seo/dot-device-selector-seo.component.ts:152]: Yes, already does
