### PR TITLE
#20334 the domain set on the cookies on a weird path, setting to / to…

### LINKED ISSUE #20334: Setting COOKIES_HTTP_ONLY=TRUE or COOKIES_SECURE_FLAG=always/https causes cookie duplication
**Describe the bug**
Setting either of the properties `COOKIES_HTTP_ONLY=TRUE` or `COOKIES_SECURE_FLAG=always/https` will cause dotCMS to create duplicate cookies. 
This is reproducible on both master and LTS.
This causes 500 errors for sites that have a lot of cookies as the header gets overfilled and rejected. 

Ticket: https://dotcms.zendesk.com/agent/tickets/104029

**To Reproduce**
Using a clean demo starter
1. Set either `COOKIES_HTTP_ONLY=TRUE` or `COOKIES_SECURE_FLAG=always` for your environment
2. Add some cookies using the cookietool to `html_head.vtl` for the travel theme at `application/vtl/themes/travel/html_head.vtl`
For example, I added this:
```
$cookietool.add("testCookie1","testCookie1")
$cookietool.add("testCookie2","testCookie2")
```
3. Navigate to the demo homepage and open your browser tools. Check the cookies for the application and start navigating around the site. You will see these test cookies become duplicated. The number of duplications will vary greatly. 

 
**Expected behavior**
There should only be a singular copy of any given cookie.

**Additional context**
This occurs with either flag set, or both flags set. It does not occur when neither flag is set.

### PR DESCRIPTION
**Pull request by jdotcms**
The CookieTool now set the path to root, this avoids the dupes

### CODE REVIEW

**Review by nollymar — COMMENTED** [review]
A couple of tests on CookieTool methods can be implemented

**Comment by jdotcms** [comment]
> A couple of tests on CookieTool methods can be implemented

Done, thanks

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/integration-test/java/org/apache/velocity/tools/view/tools/CookieToolTest.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+import org.apache.velocity.tools.view.context.ViewContext;
+import org.junit.Assert;
+import org.junit.Test;
+import org.mockito.Mockito;
+
+import javax.servlet.http.Cookie;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+
+public class CookieToolTest {
```
Comment (erickgonzalez) [inline dotCMS/src/integration-test/java/org/apache/velocity/tools/view/tools/CookieToolTest.java:14]: Need to add this test to the MainSuite to make it run.

**Review by erickgonzalez — CHANGES_REQUESTED** [review]
