### PR TITLE
fix(ContentDriveSearch) Update Contentlet Count when a Hybrid search was applied Refs: #34009

### LINKED ISSUE #34009: [DEFECT] Backend API Issues Drive Search
## Description
Three backend API issues have been identified that need to be fixed.

### 1. POST api/v1/drive/search - Incorrect contentTotalCount
**Expected:** Correct total count of search results when searching for keywords
**Actual:** Receiving wrong `contentTotalCount` value in the response

### 2. POST api/v1/drive/search - Missing fullName in Owner Field
**Expected:** The `owner` field for folders should include the `fullName` property
**Actual:** The `fullName` property is missing from the `owner` field for folders

## Video Evidence

https://github.com/user-attachments/assets/dc14018c-c99c-462d-9b10-271154ed6430

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
### Proposed Changes
* Updating count when text hybrid search was applied

This PR fixes: #34009

This PR fixes: #34009

### CODE REVIEW

File: dotcms-integration/src/test/java/com/dotcms/browser/BrowserAPITest.java [hunk 1]
```diff
@@ -1401,7 +1402,7 @@ public void test_SmartPaginationPage1_25Folders1Contentlet() throws Exception {
         }
 
         // Create 100 contentlets
```
Comment (dario-daza) [inline dotcms-integration/src/test/java/com/dotcms/browser/BrowserAPITest.java]: Shall we change or delete the comment?

**Review by dario-daza — APPROVED** [review]

**Review by nollymar — APPROVED** [review]
