### PR TITLE
#22196 : Replacing deprecated LibSass with Dart SASS Compiler v1.54.4

### LINKED ISSUE #22196: Move To Dart Sass
Libsass is deprecated and not cutting it for us anymore.  We need to move to use dart sass.  This process would look like:

1. In our docker image build, wget the latest version of dart sass from github based on arch type.  Stick it somewhere knowable, e.g. under `WEB-INF/bin`.  Binaries can be found here: https://github.com/sass/dart-sass/releases/tag/1.50.0
2. Rewrite the `DotLibSassCompiler` to shell out and call dart sass under the covers.
  - we might need to pass the `--load-path=` option for each subfolder that is included in the sass compilation
3. return the resulting CSS
4. Remove jsass and libsass from our proj
### Things to note
1. If there is an error in the css style sheet, lets try to spit that error to the user if they are logged in.  We do this now with libsass.
3. We probably want to provide a config variable that if set can override the path to dart-sass binary.

### Things to test
1.  As a test, please make sure we can compile Bootstrap 5 out of the box.
2. The `DotLibSassCompiler` would break on compiling the latest foundation.  We need to test that the Dart impl can compile that successfully 
3. We need to insure that this runs on both intel linux and arm64 linux docker images

## Steps To Reproduce - Scenario 1
1. Start up dotCMS via Docker with our Demo Starter, and open up any page. All of them must load just fine, with all the CSS showing up as expected.

## Steps To Reproduce - Scenario 2
1. Start up dotCMS via Docker with the Empty Starter and a valid license.
2. Upload the Test Bundle [attached to my comment below](https://github.com/dotCMS/core/issues/22196#issuecomment-1234653561). It contains all the required Foundation 6 folders, the test Template, and the test HTML Page for testing.
3. Open up the `/test` page and make sure that you see the plain non-styled HTML Page first.
4. Go to **Site > Templates** and open up the `Foundation Template`. Un-comment the style sheet reference in line # 7.
5. Go back to the `/test` page and make sure that you're seeing the CSS styling showing up.

## Steps To Reproduce - Scenario 3
1. Coordinate with @manuel-miranda to set up an AWS Graviton instance with the Demo Starter. All test pages in there must load just fine.
2. After that, ask Manuel to reset the environment to use the Empty Starter, upload a valid license, and upload [the same test bundle from my comment below](https://github.com/dotCMS/core/issues/22196#issuecomment-1234653561). Make sure it works as well.

### PR DESCRIPTION
**Pull request by jcastro-dotcms**
### Proposed Changes
* Replacing deprecated LibSass with Dart SASS Compiler v1.54.4, which works by shelling out and calling the SASS scripts that perform the actual SCSS compilation.

### Checklist
- [x] Tests

### Additional Info
** Test with as many CSS Frameworks as possible. **

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/DartSassCompiler.java [hunk 1]
```diff
@@ -0,0 +1,215 @@
...
+
+    /**
+     * Generates the CLI call to the Dart SASS compiler based on the location of the library in dotCMS, and the
+     * specified configuration parameters that define the behavior of the compiler.
+     *
+     * @return An array containing the parts that make up the compile command.
+     */
+    private String[] buildCompilationCommand() {
+        final List<String> compileInstructions = new ArrayList<>();
+        final String location = this.commandStrategyResolver.getStrategy().get().apply();
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/DartSassCompiler.java:168]: Very good

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotcms/csspreproc/CSSPreProcessServletTest.java [hunk 2]
```diff
@@ -0,0 +1,249 @@
...
+        when(mockRequest.getSession(false)).thenReturn(mockSession);
+        when(mockResponse.getOutputStream()).thenReturn(mockServletOutputStream);
+        when(mockResponse.getWriter()).thenReturn(new PrintWriter(mockServletOutputStream));
+        when(mockSession.getAttribute(WebKeys.CMS_SELECTED_HOST_ID)).thenReturn(defaultSiteId);
+    }
+
+    /**
+     * Mock ServletOutputStream for testing purposes only.
+     */
+    private class MockServletOutputStream extends ServletOutputStream {
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/integration-test/java/com/dotcms/csspreproc/CSSPreProcessServletTest.java:218]: Just curious if we have something like this implemented for some other test. If so, it might be a good idea of refactoring to its own public class and reuse it accordinly.

File: dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/CompilerOptions.java [hunk 3]
```diff
@@ -0,0 +1,323 @@
...
+public class CompilerOptions implements Serializable {
+
+    private final boolean verbose;
+    private final boolean expandedCss;
+    private final boolean errorInCss;
+    private final boolean stopOnError;
+    private final boolean deprecationWarnings;
+    private final boolean deprecationWarningsFromDependencies;
+
+    private static final String VERBOSE = "dartsass.compiler.verbose";
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/CompilerOptions.java:48]: Maybe this should be part as an attribute if the `SassCommands` enum defined below.

File: dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/config/SassCommandStrategyResolver.java [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+                    Logger.error(this, String.format("Dart SASS lib for Mac OS is not available for the specified " +
+                                                             "arch '%s'", SystemUtils.OS_ARCH));
+                }
+            }
+            return Boolean.FALSE;
+        }
+
+        @Override
+        public String apply() {
+            final String location = DART_SASS_LOCATION.get().endsWith(File.separator) ? DART_SASS_LOCATION.get() :
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/config/SassCommandStrategyResolver.java:121]: Shouldn't this `endsWith` evaluation be part of `DART_SASS_LOCATION` definition?

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM

**Review by wezell — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/CompilerOptions.java (hunk 3 above)
Comment (jcastro-dotcms) [reply dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/CompilerOptions.java:48]: Done!

File: dotCMS/src/integration-test/java/com/dotcms/csspreproc/CSSPreProcessServletTest.java (hunk 2 above)
Comment (jcastro-dotcms) [reply dotCMS/src/integration-test/java/com/dotcms/csspreproc/CSSPreProcessServletTest.java:218]: Done!

File: dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/config/SassCommandStrategyResolver.java (hunk 4 above)
Comment (jcastro-dotcms) [reply dotCMS/src/main/java/com/dotcms/csspreproc/dartsass/config/SassCommandStrategyResolver.java:121]: Resolved with Victor

File: dotCMS/src/integration-test/java/com/dotcms/MainSuite.java [hunk 5]
```diff
@@ -64,11 +55,7 @@
 import com.dotcms.publishing.manifest.ManifestReaderFactoryTest;
 import com.dotcms.rendering.velocity.directive.DotParseTest;
 import com.dotcms.rendering.velocity.servlet.VelocityServletIntegrationTest;
-import com.dotcms.rendering.velocity.viewtools.DotTemplateToolTest;
-import com.dotcms.rendering.velocity.viewtools.FileToolTest;
-import com.dotcms.rendering.velocity.viewtools.JSONToolTest;
-import com.dotcms.rendering.velocity.viewtools.MessageToolTest;
-import com.dotcms.rendering.velocity.viewtools.XmlToolTest;
+import com.dotcms.rendering.velocity.viewtools.*;
```
Comment (wezell) [inline dotCMS/src/integration-test/java/com/dotcms/MainSuite.java:58]: As a general rule, we should not use wildcard imports.

File: dotCMS/src/main/java/com/dotcms/csspreproc/DotCSSCompiler.java [hunk 6]
```diff
@@ -1,41 +1,40 @@
...
-import com.dotmarketing.util.InodeUtils;
-import com.dotmarketing.util.StringUtils;
-import com.dotmarketing.util.UUIDGenerator;
+import com.dotmarketing.util.*;
 import com.liferay.util.FileUtil;
+import com.liferay.util.StringPool;
+
+import javax.servlet.http.HttpServletRequest;
+import java.io.*;
+import java.util.*;
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/csspreproc/DotCSSCompiler.java:20]: Wildcard imports

**Review by wezell — CHANGES_REQUESTED** [review]
see comments.  Looks good outside of the import statements

**Comment by wezell** [comment]
Also, we need to test this branch running on Amazon's Graviton instances to make sure it works.

File: dotCMS/src/integration-test/java/com/dotcms/MainSuite.java (hunk 5 above)
Comment (jcastro-dotcms) [reply dotCMS/src/integration-test/java/com/dotcms/MainSuite.java]: Done!

**Review by nollymar — APPROVED** [review]

**Comment by jcastro-dotcms** [comment]
> Also, we need to test this branch running on Amazon's Graviton instances to make sure it works.

@wezell worked with @manuel-miranda on setting up a Graviton instance, and the new Dart SASS implementation works in there as expected as well.

**Review by jdotcms — APPROVED** [review]
