### PR TITLE
#22349 Avoid using API into UT

### LINKED ISSUE #22349: Missing database migration tasks when migrating from <=5.1.6
**Describe the bug**
After migrating a site from <=5.1.6 to current LTS release, the database is missing several columns. 
Presumably there are missing database migration tasks.

**To Reproduce**
1. do a clean install of 5.1.6 and dump the database
2. using the 5.1.6 database, start dotcms on current 5.3.8, 21.06 or 22.03 to run the migrations
3. observe sql errors in the dotcms log due to missing database columns e.g.
```
ERROR business.RelationshipFactoryImpl - Error getting relationships with typeValue: news-comments
com.dotmarketing.exception.DotDataException: ERROR: column "mod_date" does not exist
  Position: 179{
  "SQL": ["select inode, parent_structure_inode, child_structure_inode, parent_relation_name, child_relation_name, relation_type_value, cardinality, parent_required, child_required, fixed, mod_date from relationship where lower(relation_type_value) = ?"],
```

**Current Workaround**
Manually applying the following changes to the 5.1.6 database prior to running dotCMS on newer versions seems to solve the issues.

Before running 5.3.8 migrations, run:
```sql
ALTER TABLE dot_cluster ADD cluster_salt CHARACTER VARYING(256);
```

Before running 21.06 migrations, run:
```sql
ALTER TABLE dot_cluster ADD cluster_salt CHARACTER VARYING(256);
ALTER TABLE sitelic ADD startup_time BIGINT;
```

Before running 22.03 migrations, run:
```sql
ALTER TABLE dot_cluster ADD cluster_salt CHARACTER VARYING(256);
ALTER TABLE sitelic ADD startup_time BIGINT;
ALTER TABLE structure ADD icon VARCHAR(255);
ALTER TABLE structure ADD sort_order INTEGER;
ALTER TABLE relationship ADD mod_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE company ADD default_language_id BIGINT;
```
Tested on Postgres only

[clean dotcms 5.1.6 database](https://github.com/dotCMS/core/files/8836856/dotcms-5.1.6.sql.gz)

### PR DESCRIPTION
**Pull request by freddyucv**
### Proposed Changes

Avoid using API into a UT

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java [hunk 1]
```diff
@@ -99,15 +101,24 @@ private String replaceAllContainerRelativePath(
...
                 .filter((String idOrPath) -> !FileAssetContainerUtil.getInstance().isFullPath(idOrPath))
                 .collect(Collectors.toList());
     }
 
+    private static Set<String> getContainersIdentifierOrPath(final Set<ContainerUUID> containerUUIDS) {
+
+        return containerUUIDS
+                .stream()
+                .map(ContainerUUID::getIdentifier)
+                .collect(Collectors.toSet());
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java:119]: There is an unnecessary call to `collect()` since on line 108 is going back to a stream. Basically I would remove this method and copy-paste the its body, except for the termination method, to the calling method (`getRelativePaths()(`)

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/DotTemplateTool.java [hunk 2]
```diff
@@ -227,6 +234,59 @@ public static TemplateLayout getTemplateLayout(String drawedBodyAsString) {
...
+    public static Set<ContainerUUID> getTemplateContainers(final String drawedBodyAsString) {
+
+        try {
+            return getContainers(drawedBodyAsString);
+        } catch (IOException e) {
+            return DesignTemplateUtil.getColumnContainersFromVelocity(drawedBodyAsString);
+        }
+    }
+
+    @NotNull
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/DotTemplateTool.java:246]: remove

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java [hunk 3]
```diff
@@ -99,15 +101,24 @@ private String replaceAllContainerRelativePath(
     }
 
     private List<String> getRelativePaths(final String drawedBody) {
-        final TemplateLayout templateLayoutFromJSON = DotTemplateTool.getTemplateLayout(drawedBody);
+        final Set<ContainerUUID> templateContainers = DotTemplateTool.getTemplateContainers(
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java:104]: Let's use only private methods of this UT. If you need to copy paste code into this UT and make then private methods go ahead.

**Review by dsilvam — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java (hunk 3 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java]: done https://github.com/dotCMS/core/pull/22604/commits/e0ffb54258b3a929d89c7089ffca177a18823ea0#diff-36b521520ed8ced8db845910ef888502f0dbedb7c83cc53b7bb39cb9d7de60d2L237

done https://github.com/dotCMS/core/pull/22604/commits/e0ffb54258b3a929d89c7089ffca177a18823ea0#diff-b8921f877ae173e9ff875d93630f0f026b4b96f3d23e0a98d3b768208be93399R137

File: dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/DotTemplateTool.java (hunk 2 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/DotTemplateTool.java]: done

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java (hunk 1 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java]: done https://github.com/dotCMS/core/pull/22604/commits/e0ffb54258b3a929d89c7089ffca177a18823ea0#diff-b8921f877ae173e9ff875d93630f0f026b4b96f3d23e0a98d3b768208be93399R119

File: dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java [hunk 4]
```diff
@@ -1,19 +1,28 @@
...
 import com.dotcms.rendering.velocity.viewtools.DotTemplateTool;
 import com.dotmarketing.common.db.DotConnect;
 import com.dotmarketing.common.db.Params;
 import com.dotmarketing.db.DbConnectionFactory;
 import com.dotmarketing.exception.DotDataException;
 import com.dotmarketing.exception.DotRuntimeException;
 import com.dotmarketing.portlets.containers.business.FileAssetContainerUtil;
-import com.dotmarketing.portlets.templates.design.bean.TemplateLayout;
+import com.dotmarketing.portlets.templates.design.bean.ContainerUUID;
+import com.dotmarketing.portlets.templates.design.util.DesignTemplateUtil;
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java:12]: We still need to get rid of these two dependencies. Let's either copy what's needed and make it internal/private to the UT

Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task05380ChangeContainerPathToAbsolute.java]: done 
https://github.com/dotCMS/core/pull/22604/commits/43ccd6f6d034c348870f47b42896b5e2e68dce1b https://github.com/dotCMS/core/pull/22604/commits/36739572f0e4510c216908e3b820e1e095ca9efa

**Review by dsilvam — APPROVED** [review]
