### PR TITLE
#20499 Fixing problem of concurrent logins on Windows

### LINKED ISSUE #20499: Problems trying to login from a PC if you are using mssql as db
We are getting an exception when you try to log in using a PC on an instance with MsSQL as DB. We get this exception and you are unable to login. 

Here the error: https://gist.github.com/bryanboza/e40090d38b2380e02c440f9ac69faa4a

**Expected behavior**
We need be able to login from any device using any of the supported browsers 

**Desktop (please complete the following information):**
Tested on release-21.05 // Postgres // FF

### PR DESCRIPTION
**Pull request by nollymar**
A synchronized fragment was included to avoid concurrent updates on `user_` table for the same user during the log in process

### CODE REVIEW

**Review by wezell — CHANGES_REQUESTED** [review]
This sync is too broad - if we are going to sync, we need to sync on a striped lock of the userId and also do a double "isUserLoggedIn" check inside the sync.

**Review by erickgonzalez — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/cms/login/factories/LoginFactory.java [hunk 1]
```diff
@@ -38,68 +44,46 @@
...
+                    String userName = user.getEmailAddress();
+                    Company comp = com.dotmarketing.cms.factories.PublicCompanyFactory.getDefaultCompany();
+                    if (comp.getAuthType().equals(Company.AUTH_TYPE_ID)) {
+                    	userName = user.getUserId();
                     }
-            	}
-            	else
-            		Logger.info(LoginFactory.class, "Unable to retrieve user from LDAP/CAS with id: " + decryptedId);
-            }
+                    return doLogin(userName, null, true, request, response, true);
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotmarketing/cms/login/factories/LoginFactory.java:74]: I think we need just sync this call here, right< I mean the code before it just getter from database (I think)

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/cms/login/factories/LoginFactory.java (hunk 1 above)
Comment (nollymar) [reply dotCMS/src/main/java/com/dotmarketing/cms/login/factories/LoginFactory.java:74]: yes, we were discussing that. But at the end, we thought we could keep it this way
