### PR TITLE
#21419 surrounding the code with a try catch in case of messed up json

### LINKED ISSUE #21419: Site Browser: Unable to open some folders
**Describe the bug**
An exception is thrown trying to open some folders in a receiver: https://gist.github.com/nollymar/99205cd6e86a543ed895f5656269d85f

Screen Shot 2021-12-15 at 10 30 45 AM

This issue happens with a custom dataset

On the other hand, if I try to push those folders from the sender, it fails as well with a similar exception: 

```
Failed to publish because an error occurred: An error occurred when processing Contentlet in 
'/data/shared/assets/bundles/01FPZ7XAKQPNB2VRDWPXHV50WT/live/dotcms.com/1/0-d2b30470-06df-4611-be63-8a076501c133.content.xml' 
with ID 'c633f85c-57af-4c21-af02-eb54401c0242': 'Unable to populate contentlet from table columns for
 ID='c633f85c-57af-4c21-af02-eb54401c0242', Inode='a6dbd962-b5c2-4441-a022-d4be05389a02', 
Content-Type 'dba3b94b-9e42-485a-bcf9-2af8fad5ac3b': Unable to obtain property value for field 'text_area1' 
in Contentlet with ID='c633f85c-57af-4c21-af02-eb54401c0242', Inode='a6dbd962-b5c2-4441-a022-d4be05389a02',
 Content Type 'dba3b94b-9e42-485a-bcf9-2af8fad5ac3b': com.google.gson.stream.MalformedJsonException: 
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10 path $'
```

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
On 21.12 we're introducing a change that converts KeyValues into Map
So the corresponding keyValue JSON is returned in the contentlet as a Map
This change prevents that any messed-up JSON breaks the app.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/ContentletTransformer.java [hunk 1]
```diff
@@ -278,9 +279,19 @@ private static Object getObjectValue(Map<String, Object> originalMap, Field fiel
...
+                && value instanceof String) {
+            final String asString = value.toString();
+            try {
+                value = com.dotmarketing.portlets.structure.model.KeyValueFieldUtil
+                        .JSONValueToHashMap(asString);
+            } catch (Throwable e) {
+                Logger.warn(ContentletTransformer.class, () -> String
+                        .format("Failed to convert keyValue field `%s` to an actual json. An Empty will be returned instead. ",
+                                field.getVelocityVarName()));
+                value = new HashMap<>();
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/ContentletTransformer.java:293]: if this value won't modified, use Collections.emptyMap()

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/ContentletTransformer.java]: you got it. Done

**Review by nollymar — APPROVED** [review]
