### PR TITLE
Fix #24174: Context Menu broken on Favorite Pages Panel

### LINKED ISSUE #24174: UI - Favorite Page portlet: Create context menu for workflow action on right click - listing table
### Parent Issue
#22343

### PR DESCRIPTION
**Pull request by zJaaal**
### <samp>🤖 Generated by Copilot at 84c5e10</samp>

This pull request introduces a favorite pages feature to the dot-pages component, allowing users to quickly access their preferred pages. It also modifies the menu logic to support the new feature and ensure a consistent user experience.

## Related Issue
Fixes #24174

# Explanation of Changes

### <samp>🤖 Generated by Copilot at 84c5e10</samp>

*  Add a new feature to mark pages as favorites and access them from a separate tab (`core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-page-listing/dot-page-listing.component.html`, `core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-page-listing/dot-page-listing.component.ts`, `core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-page-listing/dot-page-listing.service.ts`, `core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-page-listing/dot-page-listing.module.ts`, `core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-page-listing/dot-page-listing.component.spec.ts`)

### Original

https://user-images.githubusercontent.com/63567962/236890159-db648888-34b2-4297-81e0-d7ad519c2373.mov

### Update

https://user-images.githubusercontent.com/63567962/236890036-89475f9f-4872-4ab0-b229-bbb9018922b6.mov

### CODE REVIEW

File: core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts [hunk 1]
```diff
@@ -103,7 +103,10 @@ export class DotPagesComponent implements OnInit, OnDestroy {
      */
     @HostListener('window:click')
     closeMenu(): void {
-        if (this.domIdMenuAttached.includes('pageActionButton')) {
+        if (
+            this.domIdMenuAttached.includes('pageActionButton') ||
+            this.domIdMenuAttached.includes('favoritePageActionButton')
```
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts:108]:
```suggestion
            this.shouldShowMenu()
```

```
private shouldShowMenu(): boolean {
    return this.domIdMenuAttached.includes('pageActionButton') || this.domIdMenuAttached.includes('favoritePageActionButton')
}
```

File: core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts [hunk 2]
```diff
@@ -140,7 +143,11 @@ export class DotPagesComponent implements OnInit, OnDestroy {
             )
             .subscribe((actionMenuDomId: string) => {
                 const target = this.element.nativeElement.querySelector(`#${actionMenuDomId}`);
-                if (target && actionMenuDomId.includes('pageActionButton')) {
+                if (
+                    target &&
+                    (actionMenuDomId.includes('pageActionButton') ||
+                        actionMenuDomId.includes('favoritePageActionButton'))
```
Comment (fmontes) [inline core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts:149]:
```suggestion
                    this.shouldShowMenu()
```

**Review by fmontes — CHANGES_REQUESTED** [review]

**Comment by zJaaal** [comment]
I tried to add a test to be sure that this behavior is working correctly as @alfredo-dotcms requested, but the current architecture is too complicated to be tested and I couldn't find an easy way to test this.

**Review by alfredo-dotcms — APPROVED** [review]
