### PR TITLE
#20139 Changing user serialization when it is used in a dojo data store

### LINKED ISSUE #20139: Cant filter by roles
Description: 
The System Roles screen is showing an error when clicking on the role item itself.

1. Go to  System -> Roles & Tools 
2. Click on The role "Scripting User"
3. An Error message pops up and No filtering is happening
4. The exception seems to be a javascript problem perhaps some of the items on the map that is sent from the back have changed somehow. I assume that since there are no visible exceptions in the logs. 
5. Additionally whenever I click on the Front-End user I get empty rows (See screenshot 2)

**Screenshots**
Screenshot - 1 Error Reported
Screen Shot 2021-03-23 at 17 58 58

Screenshot - 2 No info displayed.
Screen Shot 2021-03-23 at 18 00 24

### PR DESCRIPTION
**Pull request by nollymar**
The `additional_info` field is parsed as a string representation of the json object to make it compatible with dojo data stores

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/business/ajax/RoleAjax.java [hunk 1]
```diff
@@ -184,26 +190,55 @@ public int compare(Map<String, Object> o1, Map<String, Object> o2) {
 	//Retrieves a list of roles mapped to the given list of roles
 	public Map<String, List<Map<String, Object>>> getUsersByRole(String[] roleIds) throws NoSuchUserException, DotDataException, DotSecurityException, IllegalAccessException, InvocationTargetException, NoSuchMethodException {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/business/ajax/RoleAjax.java:191]: set to final

File: dotCMS/src/main/java/com/dotmarketing/business/ajax/RoleAjax.java [hunk 2]
```diff
@@ -184,26 +190,55 @@ public int compare(Map<String, Object> o1, Map<String, Object> o2) {
...
+            throws IllegalAccessException, InvocationTargetException, NoSuchMethodException {
+        final Map<String, Object> userMap = user.toMap();
+        //Additional info is sent as a json object to avoid parsing errors with dojo data store
+        final Map<String, String> additionalInfo = (Map<String, String>) userMap
+                .get("additionalInfo");
+        try {
+            userMap.put("additionalInfo",
+                    additionalInfo != null ? mapper
+                            .writeValueAsString(additionalInfo)
+                            : "{}");
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/business/ajax/RoleAjax.java:231]: this could be a constants such as EMPTY_JSON

**Review by jdotcms — APPROVED** [review]

**Review by dsilvam — APPROVED** [review]
