### PR TITLE
#21345 Fix DNSUtilUnitTest so it passes on amazon servers

### LINKED ISSUE #21345: Fix DNSUtilUnitTest so it passes on amazon servers
reverse dns test is expecting an ip address but when running on amazon servers it returns an actual domain e.g. ip-192-168-0-100.compute.internal.
Change test to allow this format,   Test is still not guaranteed to pass on any environment and may need to be further looked at.

### PR DESCRIPTION
**Pull request by freddyucv**

### CODE REVIEW

**Review by spbolton — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/test/java/com/dotmarketing/util/DNSUtilUnitTest.java [hunk 1]
```diff
@@ -38,10 +37,13 @@ public void notExistsIP() throws IOException {
      * When: Use with any IP
      * Should: return the same IP
      *
-     * @throws IOException
      */
     @Test()
     public void anyIP() throws IOException {
-        assertEquals("192.168.0.100",DNSUtil.reverseDns("192.168.0.100"));
+        String name = DNSUtil.reverseDns("192.168.0.100");
+        System.out.println(name);
```
Comment (nollymar) [inline dotCMS/src/test/java/com/dotmarketing/util/DNSUtilUnitTest.java:44]: why is this System.out.print required?

**Review by nollymar — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]
