### PR TITLE
Issue 22756 update categories take 2

### LINKED ISSUE #22756: Removing Categories through REST API
**Describe the bug**
Whenever REST API call made to clear/remove categories it returns 500

**To Reproduce**
Example. 

News has category **type** so Today news has two categories sport, entertainment so when trying to remove all categories with **type:{}** It returns 500
/api/v1/workflow/actions/fire
{ 
   "actionName": "Save",
   "comments": "saving content",
   "contentlet": {
      "contentType":"News",
        "identifier": "f3fd1b2042418d84592334b3b9a27627",
        "inode": "22540f01-7322-4c79-bb1a-e57810a85f0b",
        "type":{},
      "title":"blkjjhj Second Content", 
      "languageId": "1"
  }
}.

Logs:

`ERROR workflow.WorkflowResource: Exception on firing, workflow action: ceca71a0-deee-4999-bd47-b01baa1bcfc8, inode: null
java.lang.NullPointerException: null
at com.dotmarketing.portlets.categories.business.CategoryAPIImpl.findByVariable_aroundBody72(CategoryAPIImpl.java:787) ~[dotcms_22.03.2_999999.jar:?]
at com.dotmarketing.portlets.categories.business.CategoryAPIImpl$AjcClosure73.run(CategoryAPIImpl.java:1) ~[dotcms_22.03.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]`

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
### Proposed Changes
Quite a few things were fixed here
Since our checkin method takes a list of categories and that's what will be saved for the contentlet being passed. 
Any operation to differentiate what categories must be removed and replaced must happen prior to reaching out to that method. So the populator now

* Load all categories that belong already into the contentlet
* Organize the categories per field
* Replaces the existing categories with the new ones being passed 
* Deals with different forms or null. Like String "Null" and JSONObject.NULL

### CODE REVIEW

File: dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java [hunk 1]
```diff
@@ -2290,5 +2290,71 @@ public static ContentType newContentTypeFieldTypesGalore(final String contentTyp
...
+    public static ContentType newContentTypeWithMultipleCategoryFields(final String contentTypeName,
+            final Set<String> workflowIds) {
+        final CategoryAPI categoryAPI = APILocator.getCategoryAPI();
+        final List<Category> categories = Try.of(
+                        () -> categoryAPI.findTopLevelCategories(APILocator.systemUser(), false))
+                .getOrElseThrow(DotRuntimeException::new);
+        return newContentTypeWithMultipleCategoryFields(contentTypeName, workflowIds, categories);
+    }
+
+    @WrapInTransaction
```
Comment (nollymar) [inline dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java:2302]: why a WrapInTransaction is required here?

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 2]
```diff
@@ -332,14 +336,47 @@ private void processSeveralHostsOrFolders(final Contentlet contentlet,
...
+     * Meaning that if this method generates an empty list, The categories in the contentlet will be wiped-out. An empty Optional means nothing should be sent down into the checkin pipeline
+     * @param contentlet
+     * @param user
+     * @param respectFrontendRoles
+     * @return Empty Optional means no categories were found if something comes back within the Optional that's what must be applied there.
+     * If an empty Collection of categories is returned that means we need to wipe out the categories from the contentlet
+     * @throws DotDataException
+     * @throws DotSecurityException
+     */
+    @CloseDBIfOpened
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:371]: Why a CloseDBIfOpened is required here?

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 3]
```diff
@@ -383,53 +434,158 @@ List<Category> categories(final Contentlet contentlet, final User user, final bo
...
+     * We need to be able to reconstruct the contents on the second field. Cuz the list of categories expected by the checkin method
+     * Persists what is passed to it. It doesn't do any internal arithmetic to reconstruct the other categories.
+     * We need to do such logic here. And that is why we need to be able to fetch the exising categories
+     * @param contentlet
+     * @param user
+     * @return
+     * @throws DotDataException
+     * @throws DotSecurityException
+     */
+    Map<CategoryField, Set<Category>> fetchExistingCategories(final Contentlet contentlet, final User user)
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:540]: Shouldn't this method be private?

File: dotCMS/src/curl-test/Workflow Resource Tests.json [hunk 4]
```diff
@@ -14784,17 +14785,166 @@
 					"response": []
 				},
 				{
-					"name": "update-contentlet-remove-category",
+					"name": "update-contentlet-add-category-ignore-fields",
```
Comment (nollymar) [inline dotCMS/src/curl-test/Workflow Resource Tests.json:14788]: Could you please add a description to the new tests implemented here?

File: dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java [hunk 5]
```diff
@@ -2290,5 +2290,71 @@ public static ContentType newContentTypeFieldTypesGalore(final String contentTyp
...
+    public static ContentType newContentTypeWithMultipleCategoryFields(final String contentTypeName, Set<String> workflowIds, final List<Category> parents) {
+
+        ContentType contentType = null;
+        try {
+            try {
+                contentType = APILocator.getContentTypeAPI(APILocator.systemUser()).find(contentTypeName);
```
Comment (jdotcms) [inline dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java:2308]: Would be better use Try.of().getOrNull

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 6]
```diff
@@ -349,32 +386,46 @@ public List<Category> getCategories (final Contentlet contentlet, final User use
      * @param respectFrontendRoles
      * @return
      */
-    List<Category> categories(final Contentlet contentlet, final User user, final boolean respectFrontendRoles) {
-        List<Category> categories = new ArrayList<>();
-        final List<com.dotcms.contenttype.model.field.Field> fields = contentlet.getContentType()
-                .fields(CategoryField.class);
-        for (final com.dotcms.contenttype.model.field.Field field: fields) {
+    Optional<List<Category>> internalFetchCategories(final Contentlet contentlet, final User user,
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:389]: since both methods uses the Close db you can just resume the close db in this private method

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 7]
```diff
@@ -349,32 +386,46 @@ public List<Category> getCategories (final Contentlet contentlet, final User use
...
+            if (object instanceof Collection) {
                 final Collection<?> list = (Collection<?>) object;
-                final String joinedCategories = list.stream().map(Object::toString).collect(
-                        Collectors.joining(","));
-                buildUpCategories(categories, joinedCategories, user, respectFrontendRoles);
+                if(list.isEmpty()){
+                    //upfront en empty list must be interpreted as an attempt to wipe out categories from the current field.
+                    builder.put(field, ImmutableSet.of());
+                } else {
+                    final String joinedCategories = list.stream().map(Object::toString).collect(Collectors.joining(","));
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:409]: you can use StringPool.COMMA

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 8]
```diff
@@ -383,53 +434,158 @@ List<Category> categories(final Contentlet contentlet, final User user, final bo
...
-     * @param categories
      * @param stringValue
      * @param user
      * @param respectFrontendRoles
      */
-    private void buildUpCategories(final List<Category> categories, final String stringValue,
-            final User user, boolean respectFrontendRoles) {
-        if (UtilMethods.isSet(stringValue)) {
+    private Set<Category> getCategoriesFromStringValue(final String stringValue, final User user, boolean respectFrontendRoles) {
+        Set<Category> categories = new HashSet<>();
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:479]: create the set after throw the exception

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java [hunk 9]
```diff
@@ -383,53 +434,158 @@ List<Category> categories(final Contentlet contentlet, final User user, final bo
...
+        final Category parent = categoryAPI.find(categoryField.values(), user,
+                false);
+
+        if (categoryAPI.canUseCategory(parent, user, false)) {
+            return categories.stream()
+                    //in order to make sure we include all categories We need to take into account also the actual parent and verify it against the current category
+                    .filter(category -> category.equals(parent) || categoryAPI.isParent(category, parent, user, false))
+                    .collect(Collectors.toSet());
+        }
+        return null;
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:588]: and empty set could be better?

File: dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java (hunk 5 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java:2308]: good observation. I was just reusing code from other methods in this class

Comment (fabrizzio-dotCMS) [reply dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java:2308]: done

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 2 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:371]: I'm deprecating getCategories in favor of `fetchCategories` and.. since they both do they same I simply repeated the pattern. Though if you think about it we now have a method that loads the existing categories which makes use of the db

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 6 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:389]: true. But .. please note that the old method `getCategories` is getting deprecated in favor of a new on.
done

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 7 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:409]: true and done

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 8 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:479]: done

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 3 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:540]: yeah 
changed

File: dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java (hunk 9 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/MapToContentletPopulator.java:588]: I made it return null to be able to differentiate the case. Actually the statement that filters can be empy 
I making a validation to ignore when null

File: dotCMS/src/curl-test/Workflow Resource Tests.json (hunk 4 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/curl-test/Workflow Resource Tests.json:14791]: done!

File: dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java (hunk 1 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/integration-test/java/com/dotcms/datagen/TestDataUtils.java:2302]: all other methods in this class have a `WrapInTransaction`

**Review by nollymar — APPROVED** [review]

**Review by alfredo-dotcms — APPROVED** [review]
