### PR TITLE
#22004 Adding validation to support optional binary fields on import

### LINKED ISSUE #22004: Blank Binary Field Causes Error on Import
**Describe the bug**
When importing contentlets with a binary field, if the binary field has a null value, dotCMS throws an error in the logs and nothing is imported. Note, the content can be imported fine if the binary field is removed from the CSV when imported.
**To Reproduce**
1. Go to demo.dotcms.com
2. Create a CT with a text field and a binary field that is not required.
3. Create some contentlets of that type in a CSV with only a text value and a null value in the binary field column, then try to import those contentlets without any key fields selected

**Expected behavior**
A null value in the binary column of a CSV would not effect its ability to be imported successfully. 

**Desktop (please complete the following information):**

 - Version, 5.3.8.10, 22.03

**Additional context**
Related to a customer issue: https://dotcms.zendesk.com/agent/tickets/107012

### PR DESCRIPTION
**Pull request by nollymar**

### CODE REVIEW

File: dotCMS/src/integration-test/java/com/dotcms/util/ImportUtilTest.java [hunk 1]
```diff
@@ -2284,4 +2285,79 @@ public void importFile_importBinaryFieldUsingURL_failed_URLsareNotValid()
...
+            assertTrue(savedData.size() == 1);
+            assertNull(savedData.get(0).getBinary(BINARY_FIELD_NAME));
+
+        } finally {
+            try {
+                if (null != contentType) {
+                    contentTypeApi.delete(contentType);
+                }
+            } catch (Exception e) {
+                e.printStackTrace();
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotcms/util/ImportUtilTest.java:2359]: should the test fail in this case?

**Review by freddyucv — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotcms/util/ImportUtilTest.java (hunk 1 above)
Comment (nollymar) [reply dotCMS/src/integration-test/java/com/dotcms/util/ImportUtilTest.java:2359]: nope, because that's just a cleanup

**Review by fabrizzio-dotCMS — APPROVED** [review]
