### PR TITLE
issue-226350-newrelic

### LINKED ISSUE #22635: Server hang on startup with NewRelic agent
ByteBuddy annotation logic is too over agressive and it is impacting other agents like New Relic slowing down and failing start up.

Only classes that contain annotated methods we are interested in should be transformed.

This can be done with the following logic in ByteBuddyFactory

 builder.type(ElementMatchers.declaresMethod(
                            isAnnotatedWith(WrapInTransaction.class)
                                    .or(isAnnotatedWith(CloseDB.class))
                                    .or(isAnnotatedWith(CloseDBIfOpened.class))
                                    .or(isAnnotatedWith(LogTime.class))
                    ))

### PR DESCRIPTION
**Pull request by spbolton**
ByteBuddy annotation logic is too over agressive and it is impacting other agents like New Relic slowing down and failing start up.

Only classes that contain annotated methods we are interested in should be transformed.

This can be done with the following logic in ByteBuddyFactory

builder.type(ElementMatchers.declaresMethod(
isAnnotatedWith(WrapInTransaction.class)
.or(isAnnotatedWith(CloseDB.class))
.or(isAnnotatedWith(CloseDBIfOpened.class))
.or(isAnnotatedWith(LogTime.class))
))

Note use env var DOTCMS_BYTEBUDDY_DEBUG=true to see the transformed classes as they transform and any errors.    Only classes containing the annotations should now be attempted to load and new relic agent should show in log if added.  Even without new relic agent startup should be slightly quicker and may fix some other issues as we are being more specific.   I do not think it is an issue and probably same behavior as before byte buddy but worth noting that the annotations do not automatically propagate to subclasses on methods.   This means that a method on a superclass  that has one of these annotations will probably have issues unless the subclass method does not also have the annotation.

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java [hunk 1]
```diff
@@ -56,71 +54,57 @@ public static void premain(final String arg, final Instrumentation inst) throws
...
             }
 
-            builder.with(bootFallbackLocationStrategy).type(ElementMatchers.nameStartsWith("com.dotcms"))
-                            .or(ElementMatchers.nameStartsWith("com.dotmarketing"))
-                            .or(ElementMatchers.nameStartsWith("com.liferay"))
-                            .transform(new AgentBuilder.Transformer.ForAdvice()
-                                            .withExceptionHandler(Advice.ExceptionHandler.Default.RETHROWING)
-                                            .advice(isMethod().and(isAnnotatedWith(CloseDB.class)),
-                                                            CloseDBAdvice.class.getName()))
+            builder.type(ElementMatchers.declaresMethod(
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java:83]: should we have both sets of filters - package names AND class names for even faster startup?

Comment (spbolton) [reply dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java:83]: @wezell I have specific excludes of some things we know we want to ignore.  It is possible we would speed up a bit if we add more filters on name/package, there is no real different with class name and package name with this respect it is just using the name passed and at these ignores no reflection is being done and adding individual classes would get unwieldy.     If it gets through the ignores it my take slightly longer to check the isAnnotatedWith but this check is quicker than trying to transform the class.   We could use a whitelist on name but I am concerned that it may cause us problems later and maybe with plugins.   It seems to be quick starting up with this change, but we could possibly improve.   One way could be using what Quarkus uses called Jandex which creates an index of classes, annotations and generic types at build time and you can query it very quickly at runtime without reflection.  We may not even have the usual reflection hit here anyway as the class is being redefined at the point of initial loading so it actually has all the info it needs at that point and once transformed does not need to use reflection anymore.  I  Don't want to go too far on solving the performance here at the moment and add complexity if it is not making any difference but we do have options.

`.ignore(nameStartsWith("net.bytebuddy."))
                    .ignore(nameStartsWith("com.dotcms.repackage."))
                    .ignore(nameStartsWith("com.dotcms.business.bytebuddy"))`

Comment (spbolton) [reply dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java]: @wezell I have added a commit that does do the extra whitelist filtering as we had before and improved the logging; we could add config to this if we need to.

File: dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java [hunk 2]
```diff
@@ -30,6 +34,24 @@
...
 
     private static final AtomicBoolean agentLoaded = new AtomicBoolean(false);
+    private static final Map<Class<? extends Annotation>, Class<?>> adviceMap = Map.of(
+            WrapInTransaction.class, WrapInTransactionAdvice.class,
+            CloseDB.class, CloseDBAdvice.class,
+            CloseDBIfOpened.class, CloseDBIfOpenedAdvice.class
+    );
+
+
+    private static final Set<String> packageIgnore = Set.of(
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/business/bytebuddy/ByteBuddyFactory.java:44]: does this need to be larger as well?  e.g. include
```
org.apache, 
com.google
```

?

**Review by wezell — APPROVED** [review]
This looks good and significantly improves startup time, can be merged.

**Review by jdotcms — APPROVED** [review]
