### PR TITLE
fix(TailLog) Support sub folders  Refs: #34131

### LINKED ISSUE #34131: Log Files view does not display log files from subdirectories
## Description

The Log Files view in the Maintenance portlet no longer displays log files from subdirectories. In version 5.3.9, log files were displayed recursively from subfolders, but in 24.12.27 (and later), only files from the main log folder are shown.

This contradicts our [documentation](https://dev.dotcms.com/docs/log-file-viewing#TAIL_LOG_LOG_FOLDER) which states:
> "the Log Files tab will display all log files found in **and below** the specified folder"

## Steps to Reproduce

1. Configure `TAIL_LOG_LOG_FOLDER=/srv/logs`
2. Create a subdirectory structure:
   - `/srv/logs/dotcms.log`
   - `/srv/logs/imports/import.log`
3. Navigate to **Maintenance → Log Files**
4. Observe the dropdown only shows `dotcms.log`, not `imports/import.log`

## Expected Behavior

All `.log` files in the configured folder **and its subdirectories** should be displayed in the Log Files dropdown.

## Actual Behavior

Only log files in the root of `TAIL_LOG_LOG_FOLDER` are displayed. Files in subdirectories are not shown.

## Root Cause

The bug is in `com.liferay.util.FileUtil.listFileHandles()` method at line 585.

**Current (buggy) code:**
```java
if(includeSubDirs && null != subFolders && containsParentFolder(file, subFolders)) {
    files.add(file.getParentFile());  // ❌ Returns the FOLDER instead of the FILE
} else {
    files.add(file);
}
```

**Original (correct) code:**
```java
if(includeSubDirs && containsParentFolder(file, subFolders)) {
    files.add(file);  // ✅ Correctly returned the FILE
} else {
    files.add(file);
}
```

When a log file is in a subdirectory, the method incorrectly returns `file.getParentFile()` (the folder) instead of `file` (the actual log file).

This was an unintended side effect of security fixes applied at that time.

## Proposed Fix

Change line 585 in `dotCMS/src/main/java/com/liferay/util/FileUtil.java` from:
```java
files.add(file.getParentFile());
```
to:
```java
files.add(file);
```

## Affected Versions

- 24.12.27 LTS (confirmed)
- All versions after commit `4057fc6eeb` (Dec 2022)

## Customer Impact

This issue is blocking a customer upgrade from 5.3.9 to 24.12.27 as it significantly reduces their ability to troubleshoot issues.

## References

- Freshdesk Ticket: https://dotcms.freshdesk.com/a/tickets/34289
- Documentation: https://dev.dotcms.com/docs/log-file-viewing#TAIL_LOG_LOG_FOLDER

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
### Proposed Changes
* When TailLogViewer was modernized, we broke sub-folder support. This PR reintroduces such
* Deprecated the old method used to get files recursively, as it is confusing what it actually does internally
* Replaced the old method with modern equivalents and added tests
* The New TailLogResource needed a few updates to now support complex file paths, including folders, etc. 
* Changes to sanitize the complex file paths without losing functionality
* Changes to MaintenanceResource to support download using complex paths 

This PR fixes: #34131

This PR fixes: #34131

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java [hunk 1]
```diff
@@ -143,6 +148,36 @@ private EventOutput sendError(final String errorMessage){
         return eventOutput;
     }
 
+    /**
```
Comment (erickgonzalez) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java]: Why did you have to create a new file sanitizer? shouldn't be better to improve our current one?

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java]: Excellent question, the reason is that the log viewer can now take a path like "folder/file.log"
And the old sanitizer eliminates the "/" as an invalid character.
The new sanitizer validates that a path like that is still valid and not harmful

Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java]: There are two new things here: this sanitizer dismantles the path and applies the old sanitizer to every single part of the path. And there is also the method isValidFilePath that validates the "folder/file" path is not harmful

File: dotCMS/src/test/java/com/dotmarketing/util/FileUtilTest.java [hunk 2]
```diff
@@ -42,6 +42,117 @@ public void test_file_name_sanitizer() throws Exception {
...
+            "temp/cache/session_123.dat",
+            "uploads/images/photo.jpg"
+        };
+
+        for (String validPath : validPaths) {
+            assertTrue("Should accept valid path: " + validPath,
+                FileUtil.isValidFilePath(validPath));
+        }
+
+        // Test invalid file paths - directory traversal
```
Comment (dario-daza) [inline dotCMS/src/test/java/com/dotmarketing/util/FileUtilTest.java]: This test is doing different validations. Do you think there’s value in splitting it into multiple and more focused tests to make failures easier to understand?

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java (hunk 1 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java]: I'm keeping the old one as it was, as I see value in preserving the old behavior.
Besides, it is used in many other places, and this is a very particular case where we want to accept a complex path

File: dotCMS/src/test/java/com/dotmarketing/util/FileUtilTest.java (hunk 2 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/test/java/com/dotmarketing/util/FileUtilTest.java]: Actually, I prefer a single, focused test that calculates various scenarios. No great gain in separating it

File: dotCMS/src/main/java/com/dotmarketing/util/FileUtil.java [hunk 3]
```diff
@@ -224,6 +226,106 @@ public static String getIconExtension(String x) {
...
+
+    /**
+     * Process a file path that may contain subdirectories
+     * Validates first, then sanitizes each component
+     *
+     * @param filePath Path like "subfolder/file.log"
+     * @return Processed safe path
+     * @throws IllegalArgumentException if path is invalid
+     */
+    public static String processFilePath(final String filePath) {
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotmarketing/util/FileUtil.java]: why is this method for? I couldn't find any usage in the codebase

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java [hunk 4]
```diff
@@ -143,6 +148,36 @@ private EventOutput sendError(final String errorMessage){
...
+     * Sanitizes a file path by decomposing it into individual components and sanitizing each part separately.
+     * This provides enhanced security by ensuring that both directory names and file names are properly cleaned
+     * to prevent directory traversal attacks and other malicious file path manipulations.
+     *
+     * @param fileName the file path to sanitize, can include directory components
+     * @return the sanitized file path with all components individually cleaned
+     */
+    private String sanitizeFilePath(final String fileName) {
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/taillog/TailLogResource.java]: I would move this sanitizeFilePath to FileUtil and include some tests

**Review by dario-daza — APPROVED** [review]

**Review by wezell — APPROVED** [review]
Let's go!
