### PR TITLE
dotCMS/core#19723 Only 10 parent related contents retrieved when editing a child content

### LINKED ISSUE #19723: Only 10 parent related contents retrieved when editing a child content
Reported via Support: [103067](https://dotcms.zendesk.com/agent/tickets/103067)
Reproducible in dotCMS 20.11

Legacy relationships only list 10 related parent items in the relationship tab when editing a child contentlet.
This issue doesn't impact new relationship fields, unless this configuration property is set to `false`:
```
GET_RELATED_CONTENT_FROM_DB=false
```

**To Reproduce**
1. Set this configuration property to `false`:
 ```
GET_RELATED_CONTENT_FROM_DB=false
```
2. Create a many-to-many relationship between 2 content types. Create a relationship field pointing to children items on the parent content type and another relationship field pointing to parent items on the child content type.
3. Add more than 10 contentlets for the parent content type.
4. Add a new contentlet for the child content type.
5. Relate more than 10 parent contentlets on the child contentlet and save the child contentlet.
6. Flush the relationship cache.
7. Edit again the child contentlet: only 10 parent contentlets are listed for the relationship field.

**Expected behavior**
If there are more than 10 related parent contentlets, they should be listed when editing a child contentlet.

### PR DESCRIPTION
**Pull request by swicken-dotcms**
…1dd76f8ae489f6038fdf3523a70e341efb310) into core.

### CODE REVIEW

**Comment by dsilvam** [comment]
Let's add an integration test

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java [hunk 1]
```diff
@@ -1595,6 +1595,11 @@ public Identifier getRelatedIdentifier(Contentlet contentlet,String relationship
 
             SearchResponse response;
             final boolean DONT_PULL_PARENTS = Boolean.FALSE;
+
+            if (limit <= 0) {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java:1599]: rather than setting a parameter mutable I would rename the limit param by limitParam and use limit such as
```
final int limit = limitParam <= 0? MAX_LIMIT: limitParam;
```

**Review by jdotcms — APPROVED** [review]

**Review by nollymar — APPROVED** [review]

**Comment by nollymar** [comment]
I would include an IT to test this change

**Review by nollymar — CHANGES_REQUESTED** [review]
I would include an IT to test this change

**Review by erickgonzalez — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java (hunk 1 above)
Comment (swicken-dotcms) [reply dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java]: requested changes made
