### PR TITLE
#20722 : Validating if the contentlet.getHostId returns a valid S…

### LINKED ISSUE #20722: [Reindex] : Perform Site check before Folder check
Reported during customer upgrade.
Reproducible in all versions of dotCMS.

During the upgrade process for a customer -- coming from dotCMS 4.3.3 -- the full ES Reindex returned errors with several contents. For example:
```
"An error occurred when mapping properties of Contentlet with ID '6d0ccc3a-cb2d-4470-a5a5-2216f90ff23f': Parent folder '/' in Site '88d50eff-98c9-4659-88a7-c71db9118b5e' was not found via API. Please check that the specified value points to a valid folder."
```
After taking a deeper look at the actual data with @manuel-miranda , we figured out that the ID `88d50eff-98c9-4659-88a7-c71db9118b5e` is NOT a Site, but a simple contentlet. This is wrong as Contentlets can only live under System Host, a Site, or a folder. We noticed tat we are validating this scenario, but it's being called after validating the Contentlet's folder. Such a validation should happen after the Site has been validated.

We haven't been able to determine how the customer ended up with Contentlets pointing to an invalid Site.

**To Reproduce**
1. Create a simple Content Type with two fields: `Site or Folder`, and `Text`.
2. Create two sample contents of such a type pointing to `SYSTEM HOST`.
3. Go to the database, in the `identifier` table, and change the `host_inode` column to any Identifier that **IS NOT A VALID SITE**.
4. Kick off a full reindex, and you should get an error like this:
```
"An error occurred when mapping properties of Contentlet with ID '{CONTENTLET-ID}: Parent folder '/' in Site 'SITE-ID' was not found via API. Please check that the specified value points to a valid folder."
```

**Expected behavior**
The ES Reindex should indicate a problem with an invalid Site, and NOT an invalid folder.

**Additional context**
Misleading error messages take a toll on troubleshooting times for Support tickets.

### PR DESCRIPTION
**Pull request by jcastro-dotcms**
…ite before checking the contentlet's folder.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]
Changes look good, but the tests didn't run please check before the merge.

File: dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java [hunk 1]
```diff
@@ -274,19 +272,20 @@ public String toJson(final Contentlet contentlet) throws DotMappingException {
                         contentlet.getContentTypeId());
                 throw new DotDataException(errorMsg);
             }
-			final Folder contentFolder = APILocator.getFolderAPI().findFolderByPath(contentIdentifier.getParentPath(), contentIdentifier.getHostId(), systemUser, false);
+            final Host contentSite = APILocator.getHostAPI().find(contentIdentifier.getHostId(), systemUser, DONT_RESPECT_FRONTEND_ROLES);
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java:275]: A test is missing here

**Review by nollymar — APPROVED** [review]
