### PR TITLE
#19412 filtering non compatible permissions per given parent permissi…

### LINKED ISSUE #19412: "Permission Individually" on a folder defaults to all permissions of its parent, not just the inheritable ones
Reported via Support: [102509](https://dotcms.zendesk.com/agent/tickets/102509), and [102535](https://dotcms.zendesk.com/agent/tickets/102535)
Reproducible in dotCMS 5.3.4, 5.3.8.

Some folders are having problems showing their contents in the **Site Browser** intermittently. When checking their permissions, the portlet is not showing the actual list, only a handful of them. For example, before clicking the `PERMISSION INDIVIDUALLY` button, you see this:

perms-before

Only 3 roles are displayed. But, after clicking it, you get the full list of roles and their respective permissions:

perms-after

The only workaround for the customer is to flush all caches constantly. We're not 100% sure, but it seems like having a considerable number of role permissions for a folder might be causing this behavior.

**To Reproduce**
The Support Team has access to a test instance where this can be further tested. Please ask Jose Castro for the details.

**Expected behavior**
Permissions must be consistent and cached correctly in order to keep folders from not showing their contents.

**Additional context**
A similar problem is being reproduced in the internal dotCMS Authoring instance.

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
we have discovered the cause of the additional permissions making it into the list of permissions displayed when hitting individual permissions.  
The permissions must be verified to have at least one entry containing one permission compatible with the parent permissionable type.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java [hunk 1]
```diff
@@ -1521,102 +1522,136 @@ public void permissionIndividuallyByRole(Permissionable parent, Permissionable p
...
-                                        permission.getRoleId(), permission.getPermission(), true));
-                    }
-                } else {
-                    newSetOfPermissions
-                            .add(new Permission(permission.getType(),
-                                    permissionable.getPermissionId(),
-                                    permission.getRoleId(), permission.getPermission(), true));
-                }
-            }
+			final String finalPermissionableType = permissionableType;
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java:1567]: This `finalPermissionableType` is not needed, right? You can filter using the `permissionableType` as it doesn't change once assigned

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java (hunk 1 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java:1567]: it's necessary since it is accessed within a forEach that requires only effective final variables to be used there
