### PR TITLE
#20677 adding the login as to the current user

### LINKED ISSUE #20677: Users without the 'Login As' Role are still able to select Login As and see all Users
As reported in https://dotcms.zendesk.com/agent/tickets/104775 v5.2.8.3
Tested in current Demo - v21.06

**Describe the bug**
Users without 'Login As' are still able to select Login As and see all Users. They cannot complete the login as process - they just see all users.

**To Reproduce**
1. Login to dotCMS as a USer without Login As permissions
2. Select the user button at the top right of the screen and click 'Login As'
3. All users can be seen.

SCREENSHOTS:

1. Login to dotCMS as a User who does not have the 'Login As' Role:

image

2. Select the user button at the top right. Login As is there: 

image

3. Click 'Login As' - all users can be seen:

image

### PR DESCRIPTION
**Pull request by jdotcms**
Adding logic to limited the ability of doing login as only to the users with login as role assigned

### CODE REVIEW

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java [hunk 1]
```diff
@@ -342,6 +352,15 @@ public final Response loginAs(@Context final HttpServletRequest request, @Contex
 				.rejectWhenNoUser(true)
 				.init();
 
+		final RoleAPI roleAPI     = APILocator.getRoleAPI();
+		final Role    loginAsRole = roleAPI.loadRoleByKey(Role.LOGIN_AS);
+		if (!Try.of(()->roleAPI.doesUserHaveRole(initData.getUser(), loginAsRole)).getOrElse(false)) {
+
+			Logger.debug(this, "The user: " + initData.getUser().getUserId()
+					+ " does not have the LOGIN AS role, can not execute this action");
+			throw new DotSecurityException("Must have the Login As role to execute this action");
```
Comment (jcastro-dotcms) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java:361]: Add User ID to error message

**Review by jcastro-dotcms — CHANGES_REQUESTED** [review]

**Review by jcastro-dotcms — APPROVED** [review]

File: dotCMS/src/curl-test/UserResource.postman_collection.json [hunk 2]
```diff
@@ -311,6 +311,64 @@
 				"description": "* <b>Given scenario:</b> Get All the Users from the system.\n     * <b>Expected result:</b> The Total field should be greaterThan 0, so at least 1 user must be returned."
 			},
 			"response": []
+		},
+		{
```
Comment (nollymar) [inline dotCMS/src/curl-test/UserResource.postman_collection.json:315]: please add a description to this test

**Review by dsilvam — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]

**Review by nollymar — APPROVED** [review]
