### PR TITLE
#22522 sharing the conn pool between http clients and limitating the …

### LINKED ISSUE #22522: Remote URL access should be run in a threadpool
Customers often use the `$json` or `$import` tools to pull content from 3rd party APIs and display it on their pages.  The issue with this is that if the remote API/content is down or becomes non- accessible, then tomcat threads back up and instances can crash - as there are no tomcat connector threads available to service incoming requests.

In order to avoid this we should run all calls using the CircuitBreakerURL in a configurable threadpool of, say 100, threads and then reject any subsequent requests.  This would mean that if a remote url is down on high traffic pages, then only 100 tomcat connector threads would be hung up at any one time.  By default we run tomcat with `600` connector threads so by limiting the number of remote calls to 100 threads would still allow 500 threads to still be available for other requests.

### PR DESCRIPTION
**Pull request by jdotcms**
sharing the connections pool between http clients and limit the number of concurrent connections

### CODE REVIEW

**Comment by wezell** [comment]
I think I'd like to see this PR with only the limiting of the threads and without the change to `HttpClientConnectionManager` and `PoolingHttpClientConnectionManager`.  Moving to use a `PoolingHttpClientConnectionManager` for arbitrary outbound connections seems like a premature optimization and could have some unusual side effects and cause unneeded issues.  We have had no issues or complaints regarding the speed of the current closable connections and I think we should leave it as is for now.  If we were writing a dedicated client for some webservice where performance was at a premium, I would probably think differently.

File: dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java [hunk 1]
```diff
@@ -192,12 +217,15 @@ public void setWriteListener(WriteListener writeListener) {
...
-    
-    
-    
-    
-    
     public void doOut(final HttpServletResponse response) throws IOException {
+
+        if (threadIdConnectionCountSet.size() >= circuitBreakerMaxConnTotal.get()) {
+
+            Logger.info(this, "The maximum number of connections has been reached, size: " + threadIdConnectionCountSet.size());
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java:224]: Please log the url that is trying to be accessed

File: dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java [hunk 2]
```diff
@@ -192,12 +217,15 @@ public void setWriteListener(WriteListener writeListener) {
...
+            throw new RejectedExecutionException("The maximum number of connections has been reached.");
+        }
+
+        threadIdConnectionCountSet.add(Thread.currentThread().getId());
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java:228]: Does it make sense to add the current thread in the try?

Comment (wezell) [reply dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java:228]: also, under load, it might be possible to exceed the `circuitBreakerMaxConnTotal` by a few.  This might be acceptable rather than syncing

**Review by wezell — CHANGES_REQUESTED** [review]

**Comment by jdotcms** [comment]
> I think I'd like to see this PR with only the limiting of the threads and without the change to `HttpClientConnectionManager` and `PoolingHttpClientConnectionManager`. Moving to use a `PoolingHttpClientConnectionManager` for arbitrary outbound connections seems like a premature optimization and could have some unusual side effects and cause unneeded issues. We have had no issues or complaints regarding the speed of the current closable connections and I think we should leave it as is for now. If we were writing a dedicated client for some webservice where performance was at a premium, I would probably think differently.

Agree, I have removed the customization of the pool

**Review by wezell — COMMENTED** [review]
What does this print out in velocity when there are no more connections?  Anything? 
```
$import.read("https://www.google.com/")

```

**Review by wezell — APPROVED** [review]
This looks good

**Review by nollymar — APPROVED** [review]
