### PR TITLE
Fix(CLI/Core): Improvements on the Content Type resource to remove the complete dependency on ids 

### LINKED ISSUE #28264: CLI: Do not require identifiers when updating content type fields
There is a couple of improvements suggested when updating content type fields using the CLI: 
 

- [ ] Updating fields, we should not require the contentType.id in the fields properties - it is known because the fields are a property of the content type

- [ ]  Updating a field should not require the field.id - it should be enough to use the varName.

### PR DESCRIPTION
**Pull request by jgambarios**
On this PR, we have multiple changes:
1. Improvements on postman tests
2. Better error handling when saving fields without the required data.
3. Modified the `FieldFactory` to include logic that does not allow modifying the variable name.
4. Small refactors requested by sonarlint to reduce the complexity of some methods.
5. Fixed issue identifying what fields need to be deleted.
6. Improving Content type resource using the `idOrVar` path param, ignored until now, and also added better error handling related to that parameter. 

Refs: #28264

This PR fixes: #28264

### CODE REVIEW

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeHelper.java [hunk 1]
```diff
@@ -35,6 +35,7 @@
 import java.util.List;
 import java.util.Locale;
 import java.util.Map;
```
Comment (fabrizzio-dotCMS) [inline dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeHelper.java:37]: There are a couple of private fields in this class that could be removed. They are not used 
 private final WebResource webResource;
 private final ContentTypeUtil contentTypeUtil;

**Review by fabrizzio-dotCMS — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/contenttype/model/type/ContentType.java [hunk 2]
```diff
@@ -286,6 +287,27 @@ public Map<String, Field> fieldMap() {
...
+     * @return A map of fields with the generated key as the key
+     */
+    @JsonIgnore
+    @Value.Lazy
+    public Map<String, Field> fieldMap(Function<Field, String> keyGenerator) {
+        Map<String, Field> fmap = new HashMap<>();
+        for (Field f : this.fields()) {
+            fmap.put(keyGenerator.apply(f), f);
+        }
+        return ImmutableMap.copyOf(fmap);
```
[the remark this answers is not in the document]
Comment (jgambarios) [reply dotCMS/src/main/java/com/dotcms/contenttype/model/type/ContentType.java]: Done

File: dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeHelper.java (hunk 1 above)
Comment (jgambarios) [reply dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeHelper.java:34]: Done
