### PR TITLE
Issue 20669 adding upgrade task to fix dot asset title

### LINKED ISSUE #20655: DotAsset Title is presented different on two search types
**Describe the bug**
On the Release branch 21.07, a fresh install loaded with an empty starter presents a contentlet of type dot-asset on the content-search screen. First with the title `a083e942-5fb0-47ef-9619-6f8f40593474` which corresponds to the identifier. Then if a  filter is applied on the type drop-down box selecting dot-Asset the same contentlet is presented with the title `company_logo.png` which corresponds to the file name. 

Clearing the cache does not solve the issue. However, hitting save or publish does.

**To Reproduce**
1. Get a fresh install of the release branch 21.07, all brand new. empty db.. etc..  
2. Go to Content-Search screen locate an entry with the title `a083e942-5fb0-47ef-9619-6f8f40593474` You can double-click to verify the image. But do not hit save or publish. Just close the dialog.
2. Click on 'The Type Drop-down and select dot-asset
3. The Contentlet displayed is the same asset but the title shown is the file name this time.

**Expected behavior**
The title of the asset should be the same at all times

**Screenshots**
Screen Shot 2021-07-13 at 07 52 42

Screen Shot 2021-07-13 at 07 53 06

Related to https://github.com/dotCMS/core/issues/19394

### PR DESCRIPTION
**Pull request by nollymar**
~These changes fix existing dotAssets' title. The identifier is replaced by the file name~

As discussed here: https://github.com/dotCMS/core/issues/20655#issuecomment-883643029 https://github.com/dotCMS/core/issues/20655#issuecomment-884425231 : 

- The `Contentlet.getTitle()` method was refactored to always return a value.
- The `title` field is saved only if there is an explicit `title` in the map 
- The `title` field in database was set to `null` for all pieces of content to force a regeneration.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Review by dsilvam — APPROVED** [review]

**Review by jcastro-dotcms — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task210719CleanUpTitleFieldTest.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+    }
+
+    @Test
+    public void testExecuteUpgrade() throws DotDataException {
+
+        final Task210719CleanUpTitleField upgradeTask = new Task210719CleanUpTitleField();
+        upgradeTask.executeUpgrade();
+
+        final List results = new DotConnect()
+                .setSQL("select inode from contentlet where title <> null").loadObjectResults();
```
Comment (wezell) [inline dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task210719CleanUpTitleFieldTest.java:28]: this should be something like
```
return new DotConnect().setSQL("select count(inode) as test from contentlet where title is not null").getInt("test")>0;
```
Otherwise, you are pulling back every contentlet object in the system.

**Review by wezell — CHANGES_REQUESTED** [review]
take a look

File: dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task210719CleanUpTitleFieldTest.java (hunk 1 above)
Comment (nollymar) [reply dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task210719CleanUpTitleFieldTest.java]: Good suggestion! Done!
