### PR TITLE
fix(indexer): Fix concurrency issues in ReindexThread (#30083)

### LINKED ISSUE #30083: Startup timeouts due to indexer concurrency issues
We are seeing more frequent cases of dotcms timing out when starting for the postman tests.  Checking the logs it seems the ReindexThread is stopping immediately after it is starting.  

On analysis there appears to be some concurrency issues with the state management in the ReindexThread, in particular the thread instance variable is not volatile breaking the double checked locking and also the setting of the state to RUNNING after the thread is submitted there is a chance that the thread checks the state and does not see the updated state before it checks and therefore immediately exits.    

```
[DOTCMS]18:54:15.622  INFO  framework.OSGISystem - Started : OSGi System Framework
[DOTCMS]18:54:15.622  INFO  reindex.ReindexThread - --- ReindexThread Running (every 60000 millis)
[DOTCMS]18:54:15.626  INFO  reindex.ReindexThread - ---  ReindexThread is starting, background indexing will begin
[DOTCMS]18:54:15.626  WARN  reindex.ReindexThread - ---  ReindexThread is stopping, background indexing will not take place
[DOTCMS]18:54:15.626  INFO  db.DotCMSInitDb - Building Initial Index
[DOTCMS]18:54:15.715  INFO  business.ESIndexAPI - createIndex : Trying to create index: cluster_5af6005ee4.working_20240919185415 with shards: 0
[DOTCMS]18:54:15.715  INFO  util.AdminLogger - class com.dotcms.content.elasticsearch.business.ESIndexAPI : createIndex : Trying to create index: cluster_5af6005ee4.working_20240919185415 with shards: 0
[ES][2024-09-19T18:54:15,914][INFO ][o.o.c.m.MetadataCreateIndexService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415] creating index, cause [api], templates [], shards [1]/[1]
[ES][2024-09-19T18:54:15,928][INFO ][o.o.c.r.a.AllocationService] [29f44040ad50] updating number_of_replicas to [0] for indices [cluster_5af6005ee4.working_20240919185415]
[ES][2024-09-19T18:54:16,161][INFO ][o.o.c.r.a.AllocationService] [29f44040ad50] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[cluster_5af6005ee4.working_20240919185415][0]]]).
[DOTCMS]18:54:16.192  INFO  business.ESIndexAPI - createIndex : Index created: cluster_5af6005ee4.working_20240919185415 with shards: 1
[DOTCMS]18:54:16.192  INFO  util.AdminLogger - class com.dotcms.content.elasticsearch.business.ESIndexAPI : createIndex : Index created: cluster_5af6005ee4.working_20240919185415 with shards: 1
[ES][2024-09-19T18:54:16,290][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] create_mapping [_doc]
[DOTCMS]18:54:16.313  INFO  business.ESIndexAPI - createIndex : Trying to create index: cluster_5af6005ee4.live_20240919185415 with shards: 0
[DOTCMS]18:54:16.313  INFO  util.AdminLogger - class com.dotcms.content.elasticsearch.business.ESIndexAPI : createIndex : Trying to create index: cluster_5af6005ee4.live_20240919185415 with shards: 0
[ES][2024-09-19T18:54:16,326][INFO ][o.o.c.m.MetadataCreateIndexService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415] creating index, cause [api], templates [], shards [1]/[1]
[ES][2024-09-19T18:54:16,328][INFO ][o.o.c.r.a.AllocationService] [29f44040ad50] updating number_of_replicas to [0] for indices [cluster_5af6005ee4.live_20240919185415]
[ES][2024-09-19T18:54:16,387][INFO ][o.o.c.r.a.AllocationService] [29f44040ad50] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[cluster_5af6005ee4.live_20240919185415][0]]]).
[DOTCMS]18:54:16.405  INFO  business.ESIndexAPI - createIndex : Index created: cluster_5af6005ee4.live_20240919185415 with shards: 1
[DOTCMS]18:54:16.405  INFO  util.AdminLogger - class com.dotcms.content.elasticsearch.business.ESIndexAPI : createIndex : Index created: cluster_5af6005ee4.live_20240919185415 with shards: 1
[ES][2024-09-19T18:54:16,419][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] create_mapping [_doc]
[ES][2024-09-19T18:54:16,583][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,586][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:16,645][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,648][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:16,714][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,716][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:16,779][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,782][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:16,854][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,859][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:16,955][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:16,964][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,045][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,048][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,118][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,121][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,190][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,193][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,256][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,258][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,320][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,324][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[ES][2024-09-19T18:54:17,384][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.working_20240919185415/WEnsLqdBQOq5bYUSm1uM-g] update_mapping [_doc]
[ES][2024-09-19T18:54:17,387][INFO ][o.o.c.m.MetadataMappingService] [29f44040ad50] [cluster_5af6005ee4.live_20240919185415/gVzj2ZqjRn67pYkNB05g8Q] update_mapping [_doc]
[DOTCMS]18:54:20.445  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:22.446  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:24.448  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:26.449  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:28.450  INFO  db.DotCMSInitDb - Records left to index : 3
[ES][2024-09-19T18:54:30,005][INFO ][o.o.i.i.ManagedIndexCoordinator] [29f44040ad50] Performing move cluster state metadata.
[ES][2024-09-19T18:54:30,006][INFO ][o.o.i.i.MetadataService  ] [29f44040ad50] ISM config index not exist, so we cancel the metadata migration job.
[ES][2024-09-19T18:54:30,007][INFO ][o.o.i.i.ManagedIndexCoordinator] [29f44040ad50] Performing ISM template migration.
[ES][2024-09-19T18:54:30,008][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] Doing ISM template migration 1 time.
[ES][2024-09-19T18:54:30,009][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] Use 2024-09-19T17:53:30.003Z as migrating ISM template last_updated_time
[ES][2024-09-19T18:54:30,009][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] ISM templates: {}
[ES][2024-09-19T18:54:30,010][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] Policies to update: []
[ES][2024-09-19T18:54:30,013][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] Failure experienced when migrating ISM Template and update ISM policies: {}
[ES][2024-09-19T18:54:30,041][INFO ][o.o.c.s.ClusterSettings  ] [29f44040ad50] updating [plugins.index_state_management.template_migration.control] from [0] to [-1]
[ES][2024-09-19T18:54:30,044][INFO ][o.o.i.i.m.ISMTemplateService] [29f44040ad50] Successfully update template migration setting
[DOTCMS]18:54:30.451  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:32.452  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:34.455  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:36.457  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:38.458  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:40.459  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:42.460  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:44.461  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:46.462  INFO  db.DotCMSInitDb - Records left to index : 3
[DOTCMS]18:54:48.463  INFO  db.DotCMSInitDb - Records left to index : 3
```

### PR DESCRIPTION
**Pull request by spbolton**
Fixes concurrency issues and prevents race conditions that cause the indexer from hanging or shutting down immediately after startup.

This PR resolves #30083 (Startup timeouts due to indexer concurrency issues).

This PR fixes: #30083

### CODE REVIEW

**Review by dcolina — APPROVED** [review]
👍🏽

**Review by dcolina — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java [hunk 1]
```diff
@@ -116,15 +117,15 @@ private enum ThreadState {
...
 
 
-    private AtomicReference<ThreadState> state = new AtomicReference<>(ThreadState.STOPPED);
+    private final AtomicReference<ThreadState> state = new AtomicReference<>(ThreadState.STOPPED);
 
 
-    private final static String REINDEX_THREAD_PAUSED = "REINDEX_THREAD_PAUSED";
-    private final static Lazy<SystemCache> cache = Lazy.of(() -> CacheLocator.getSystemCache());
+    private static final String REINDEX_THREAD_PAUSED = "REINDEX_THREAD_PAUSED";
+    private static final Lazy<SystemCache> cache = Lazy.of(CacheLocator::getSystemCache);
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:124]: cachelocator class has a lot of static and might not be loaded here.  This could potentially force its loading out of order?  Not sure but seems safer to stick with the `()->`notation?

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java [hunk 2]
```diff
@@ -315,35 +360,44 @@ public static void unpause() {
...
-        if (state == ThreadState.PAUSED) {
+        if (currentState == ThreadState.PAUSED) {
             Logger.info(ReindexThread.class, "--- Unpausing reindex thread ");
             cache.get().remove(REINDEX_THREAD_PAUSED);
-            getInstance().state(ThreadState.RUNNING);
-        } else if (state == ThreadState.STOPPED) {
+            instance.state.compareAndSet(ThreadState.PAUSED, ThreadState.RUNNING);
+        } else if (currentState == ThreadState.STOPPED) {
             Logger.info(ReindexThread.class, "--- Recreating ReindexThread from stopped");
             OSGISystem.getInstance().initializeFramework();
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:373]: We probably should remove this line at some point?  not sure why it is here.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java [hunk 3]
```diff
@@ -315,35 +360,44 @@ public static void unpause() {
...
-            submitter.submit(thread);
-            getInstance().state(ThreadState.RUNNING);
-        }
+                                    .rejectedExecutionHandler(new ThreadPoolExecutor.DiscardOldestPolicy())
+                                    .build());
 
+            try {
+                submitter.submit(instance.reindexThreadRunnable);
+                // Set state to RUNNING only after successful submission
+                instance.state.compareAndSet(ThreadState.STOPPED, ThreadState.RUNNING);
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:390]: Will this ever be `ThreadState.PAUSED` and need to be set to running?  Seems like we should just set to running no matter what.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java [hunk 4]
```diff
@@ -315,35 +360,44 @@ public static void unpause() {
...
+            } catch (RejectedExecutionException e) {
+                // Handle RejectedExecutionException specifically
+                Logger.error(ReindexThread.class, "Failed to submit reindex thread: RejectedExecutionException", e);
+                instance.state.set(ThreadState.STOPPED);
```
Comment (wezell) [inline dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:394]: This seems like new logic - are we sure we want to STOP here on exception?  Does the `DiscardOldestPolicy` even throw?

**Review by wezell — COMMENTED** [review]
Added some comments - it is important to note that this is like touching a third rail.

I like a lot of these changes and where you are going with this Steve but my question to you would be what is the smallest PR that resolves the issue we are seeing now?

We will need to test a reindex in a cluster (3 node) with more content than the starter provides - something like 10000 pieces of content.

**Comment by wezell** [comment]
Important note - none of our ITs run against or expect a cluster to exist. This specifically needs to be tested by hand in a clustered configuration - 3 nodes - and test reindex starts, stops, switchovers, manual stops and manual switchovers.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java (hunk 1 above)
Comment (spbolton) [reply dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:124]: The case we had before where we could not convert was a very particular and  case related to a method being being passed in as the argument of the method reference,  and not just the fact it has statics.   I will do a quick trace to confirm If the initialization of the CacheLocator class could be modified due to this, but I don't think it will change the order of operations in a negative way here.    I don't want us to be afraid of using method references because we do not understand their impact because of one exception to the rule.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java (hunk 3 above)
Comment (spbolton) [reply dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:390]: The concurrency should not allow changing the state while in this method and we hare already checked for the paused state.   It should be fine how it is but the only reason to do the compareAndSet would be to check the output of the method to confirm that the state did in fact remain in the expected state and there was not some other code that changed it while processing here.    Without any check we probably are better to just set the state as a paused change would not get picked up here and the state would remain as paused even though the thread had been created.   I will fix this.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java (hunk 1 above)
Comment (wezell) [reply dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:124]: I'm all about method references where they make sense and 9 times out of 10 they do. I am just scared by our old code and all their static initializers.

File: dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java (hunk 4 above)
Comment (spbolton) [reply dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexThread.java:394]: Yes, this is the exception that gets thrown when an item cannot be added to the queue.   But I see the point and in the case where we already have a reindex in process and we have another queued up.  It also looks like our submitter already catches and rethrows the RejectedExecutionException so there is no point in separately handling the catch.    Unfortunately this makes it difficult to know whether an exception to submit was due to a capacity issue or some unrelated issue so currently we have to assume that the thread is working correctly ignore any failure here,  on the flip side if there is an execption thrown the indexer thread may have a temporary error and we will not retry assuming that we are still in a RUNNING state.

**Review by jdotcms — APPROVED** [review]

**Comment by spbolton** [comment]
Modified this PR to a single change to hopefully fix the immediate issue and a follow up refactor work to fixup the general state management issues here https://github.com/dotCMS/core/issues/30083
https://github.com/dotCMS/core/pull/30110 as this will require more testing before it can be merged.

**Comment by spbolton** [comment]
@wezell Can we push in just this change, I think it will help on its own with the one issue here and we can spend some more time of general concurrency and state management issues in the new Issue I have created.

**Review by dcolina — APPROVED** [review]

**Comment by spbolton** [comment]
Fixed sonarqube reported issue.
We were creating a "new Thread" that was not actually doing anything.   We never started this thread object, it was working because thread itself extends Runnable so when passed to the Executor with submit it was just calling the run method of the "Runnable" we sent into the thread constructor.   The thread name we set would not be used anywhere in the executor.  We can just pass the original runnable getInstance().ReindexThreadRunnable directly into the submit method with the same effect.   Creating the new Thread is both confusing and unecessary

**Review by wezell — APPROVED** [review]
Looks great.
