### PR TITLE
Issue 22477 fixing bug when try to promote a variant

### LINKED ISSUE #22477: promote contentlet version
To promote a variant we need to create a copy of all Contentlet with a version in the Variant in the DEFAULT variant.

Also we need to make these new copies being the ones for the DEFAULT variant LIVE Version for each Contentlet.

Also and need a endpoint to promote a Variant.

URL: `/v1/variants/<variant_id>/_promote`

### PR DESCRIPTION
**Pull request by freddyucv**
We need to Override inside the DEFAULT Variant all the MultiTree of all the pages that has any MultiTree inside the Variant that is being promoted.

### Proposed Changes
*Get all the Multi Tree for the Variant 

https://github.com/dotCMS/core/pull/24802/files#diff-6b9c195cdec7e7bc927ed858f326518137ab896c29e1d05108f72898d006baf7R169

* Delete all the MultiTree for the pages that has any MultiTree in the Variant being promoted

https://github.com/dotCMS/core/pull/24802/files#diff-6b9c195cdec7e7bc927ed858f326518137ab896c29e1d05108f72898d006baf7R169

* Copy all the MultiTree from the Variant inside the DEFAULT Variant

https://github.com/dotCMS/core/pull/24802/files#diff-6b9c195cdec7e7bc927ed858f326518137ab896c29e1d05108f72898d006baf7R176

* Create a method to get all the MultiTree from a specific Variant

https://github.com/dotCMS/core/pull/24802/files#diff-f698237fb026280029791519155b4ddc3392a550d80caab63c43371a73b96ea0R518

* Create a method to delete all the MultiTree for a specific Variant

https://github.com/dotCMS/core/pull/24802/files#diff-f698237fb026280029791519155b4ddc3392a550d80caab63c43371a73b96ea0R158

### CODE REVIEW

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/MultiTreeAPITest.java [hunk 1]
```diff
@@ -1805,7 +1728,11 @@ public void after_override_multitrees_should_keep_other_pages_contentlet_referen
     /**
      * Method to Test: {@link MultiTreeAPI#copyMultiTree(String, List, String)}}
      * When:
+<<<<<<< HEAD
```
Comment (victoralfaro-dotcms) [inline dotCMS/src/integration-test/java/com/dotmarketing/factories/MultiTreeAPITest.java:1731]: Resolve conflicts.

**Review by victoralfaro-dotcms — APPROVED** [review]

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/MultiTreeAPITest.java (hunk 1 above)
Comment (freddyucv) [reply dotCMS/src/integration-test/java/com/dotmarketing/factories/MultiTreeAPITest.java]: done https://github.com/dotCMS/core/pull/24802/commits/627d2ffee9c612ddb41d266b0a23dc1440c04ec6
