### PR TITLE
#20270 adding site options support

### LINKED ISSUE #20270: [Content Types] : The "Site or Folder" field dropdown randomly disappears
Reported via Support: [103962](https://dotcms.zendesk.com/agent/tickets/103962)
Reproducible in dotCMS 5.3.8.4 ( branch `release-5.3.8.4`), and probably latest master.

Several Content Types stop displaying the `Site or Folder` dropdown from the Content Type Edit Modal randomly.

**To Reproduce**
1. Reach out to Jose Castro for details on the required data.
2. Set up a dotCMS 5.3.8.4 instance.
3. Reach out to Jose Castro in order to find the failing Content Type.

**Expected behavior**
The `Site or Folder` field must show up in the Edit Modal all the time.

**Additional context**
The customer needs this feature to work in order to continue with their authoring tasks.

### PR DESCRIPTION
**Pull request by jdotcms**
The DotTransformerBuilder is not doing the hydrated for Sites, with this change we can config in order to include the hosts with extra info

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/strategy/SiteViewStrategy.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+    @Override
+    protected Map<String, Object> transform(final Contentlet contentlet,
+                                            final Map<String, Object> map, final Set<TransformOptions> options, final User user) throws DotDataException {
+
+        if (Host.HOST_VELOCITY_VAR_NAME.equals(contentlet.getContentType().variable())) {
+
+            final Host host = new Host(contentlet);
+            map.putAll(host.getMap());
+        }
+        return map;
```
Comment (fabrizzio-dotCMS) [inline dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/strategy/SiteViewStrategy.java:45]: not sure if it's gonna be needed but we could also have here an options to render the site as an exploded field 
@Override
    protected Map<String, Object> transform(final Contentlet contentlet,
                                            final Map<String, Object> map, final Set<TransformOptions> options, final User user) throws DotDataException {
```
        if (Host.HOST_VELOCITY_VAR_NAME.equals(contentlet.getContentType().variable())) {
    
        } if(options.contains(SITE_AS_MAP)){
            final Host host = new Host(contentlet);
            map.put("hostId",host.getHostIdentifier());
            map.put("hostName",host.getHostName());
    
```

**Review by fabrizzio-dotCMS — APPROVED** [review]

**Review by nollymar — APPROVED** [review]

**Review by erickgonzalez — APPROVED** [review]
