### PR TITLE
#19511 Publish page even when it has expired content or publish content

### LINKED ISSUE #19511: Contentlets with future publish date prevent Page Asset from being published.
As reported in Zendesk ticket: https://dotcms.zendesk.com/agent/tickets/102757
Reported on Version 5.2.1 - replicated on Demo - 5.3.9

**Describe the bug**
If a contentlet with a future publish date is added to a Page Asset it prevents the Page from being published. 

**To Reproduce**

1. Create new Content Type and a contentlet w/future publish date.
2. Create container and template for the content type.
3. Create a page and manually add the contentlet that has a future pub date (and one that does NOT have a future pub date.)
4. Try to publish - it will not. The contentlets do not show up on the end user page.

Error in log:
`[29/10/20 17:11:24:262 GMT] ERROR business.WorkflowAPIImpl: There was an unexpected error: The content cannot be published because it is scheduled to be published on future date.`

**Expected behavior**
Page should publish but the future-publish-date contentlet should remain hidden from end users until publish date. 

**Screenshots**
NEW CONTENTLET
image

CONTAINER
image

TEMPLATE
image

CONTENTLET WITH FUTURE PUB DATE
image

CONTENTLET WITHOUT FUTURE PUB DATE
image

ADD BOTH TO PAGE
image

CANNOT PUBLISH PAGE - PAGE IS NOT UPDATED FOR END USERS
image

### PR DESCRIPTION
**Pull request by freddyucv**
Catch exception when the page has expired or publish contents to allow publish the page

### CODE REVIEW

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java [hunk 1]
```diff
@@ -108,4 +127,284 @@ public void test_publishHTMLPage_should_remove_cached_page() throws Exception {
             }
         }
     }
+
+    @Test
```
Comment (dsilvam) [inline dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java:131]: javadoc missing

File: dotCMS/src/main/java/com/dotmarketing/factories/PublishFactory.java [hunk 2]
```diff
@@ -529,4 +572,26 @@ public static List getUnpublishedRelatedAssetsForPage ( IHTMLPage htmlPage, List
...
+					.map(user -> user.getUserId())
+					.collect(Collectors.toList());
+
+			final SystemMessageBuilder messageBuilder = new SystemMessageBuilder()
+					.setMessage(message)
+					.setSeverity(MessageSeverity.ERROR)
+					.setType(MessageType.SIMPLE_MESSAGE)
+					.setLife(TimeUnit.SECONDS.toMillis(5));
+
+			systemMessageEventUtil.pushMessage(messageBuilder.create(), usersId);
```
Comment (dsilvam) [inline dotCMS/src/main/java/com/dotmarketing/factories/PublishFactory.java:592]: I think this notification should be sent to the user publishing the page @wezell @john-thomas-dotcms

**Review by dsilvam — CHANGES_REQUESTED** [review]

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (freddyucv) [reply dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java:144]: done https://github.com/dotCMS/core/pull/19988/commits/f79d75c145af00145cb048876e2203676ea9ebff#diff-24b0137583832badba6e63eace14ba2057709a12b1a03fa401cca8f95708b5a2R138

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java [hunk 3]
```diff
@@ -108,4 +127,284 @@ public void test_publishHTMLPage_should_remove_cached_page() throws Exception {
...
+
+        contentletVersionInfo = APILocator.getVersionableAPI().getContentletVersionInfo(
+                htmlPageAsset.getIdentifier(), htmlPageAsset.getLanguageId()).get();
+
+        Assert.assertNotNull(contentletVersionInfo.getLiveInode());
+
+        assertExpiredContentErrorMessage(contentlet_1, systemMessageEventUtilMock);
+    }
+
+    @Test
```
[the remark this answers is not in the document]
Comment (freddyucv) [reply dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java:325]: done https://github.com/dotCMS/core/pull/19988/commits/f79d75c145af00145cb048876e2203676ea9ebff#diff-24b0137583832badba6e63eace14ba2057709a12b1a03fa401cca8f95708b5a2R239

File: dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java [hunk 4]
```diff
@@ -108,4 +127,284 @@ public void test_publishHTMLPage_should_remove_cached_page() throws Exception {
...
+        new MultiTreeDataGen()
+                .setContainer(container)
+                .setPage(htmlPageAsset)
+                .setContentlet(contentlet_2)
+                .nextPersisted();
+
+        final User systemUser = APILocator.systemUser();
+
+        final List relatedNotPublished = new ArrayList();
+        PublishFactory.getUnpublishedRelatedAssetsForPage(htmlPageAsset, relatedNotPublished,
```
[the remark this answers is not in the document]
Comment (freddyucv) [reply dotCMS/src/integration-test/java/com/dotmarketing/factories/PublishFactoryTest.java]: done https://github.com/dotCMS/core/pull/19988/commits/f79d75c145af00145cb048876e2203676ea9ebff#diff-24b0137583832badba6e63eace14ba2057709a12b1a03fa401cca8f95708b5a2L279

File: dotCMS/src/main/java/com/dotmarketing/factories/PublishFactory.java (hunk 2 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/factories/PublishFactory.java]: done https://github.com/dotCMS/core/pull/19988/commits/f79d75c145af00145cb048876e2203676ea9ebff#diff-4756d2f625956877924d160f0ccde15c4f48b7d3eb3ada335bfeb7bc993978b6R581

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java [hunk 5]
```diff
@@ -0,0 +1,17 @@
+package com.dotmarketing.business;
+
+import com.dotmarketing.portlets.contentlet.model.Contentlet;
+
+public class ExpiredContentletPublishStateException extends PublishStateException {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java:5]: Add doc

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+    private Contentlet contentlet;
+
+    public ExpiredContentletPublishStateException(final Contentlet contentlet) {
+        super("\"The content cannot be published because the expire date has already passed.\"");
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java:9]: remove the double quotes such as
```
super ("The content cannot be published because the expire date has already passed.")
```

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java (hunk 6 above)
Comment (jcastro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java:9]: Also, add a property that would allow users/devs to identify what specific Contentlet was not published.

File: dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+
+/**
+ * Throw when try to publish a page with a content with a future publish date
+ */
+public class FutureContentletPublishStateException extends PublishStateException{
+
+    private Contentlet contentlet;
+
+    public FutureContentletPublishStateException(final Contentlet contentlet) {
+        super("The content cannot be published because it is scheduled to be published on future date.");
```
Comment (jcastro-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java:13]: Add a property that would allow users/devs to identify what specific Contentlet was not published.

**Review by jcastro-dotcms — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java (hunk 6 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java:9]: this property already exists

https://github.com/dotCMS/core/pull/19988/files/f79d75c145af00145cb048876e2203676ea9ebff#diff-bec1c25354d60d340e39396f824da23ba8de789736846051e3dad19dfb2a82a8R6

File: dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java (hunk 7 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java:13]: already exists

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java (hunk 6 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java]: done https://github.com/dotCMS/core/pull/19988/commits/30658f7295ec9788fbc12fcd61c2f3b3bf07e272

File: dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java (hunk 7 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/business/FutureContentletPublishStateException.java:13]: done https://github.com/dotCMS/core/pull/19988/commits/30658f7295ec9788fbc12fcd61c2f3b3bf07e272

File: dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java (hunk 5 above)
Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/business/ExpiredContentletPublishStateException.java:8]: done https://github.com/dotCMS/core/pull/19988/commits/2fc994beba25b2cfd7a60a719ae3d662fbd6a8c7#diff-bec1c25354d60d340e39396f824da23ba8de789736846051e3dad19dfb2a82a8R5

**Review by jcastro-dotcms — APPROVED** [review]
