### PR TITLE
#13315 fixed

### LINKED ISSUE #13315: TemplateAPI.getContainersInTemplate not working
With the change to how containers are mapped to pages - by only the multitree table, the method

`TemplateAPI.getContainersInTemplate`

stopped working.

### PR DESCRIPTION
**Pull request by wezell**
#13315

### CODE REVIEW

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/design/util/DesignTemplateUtil.java [hunk 1]
```diff
@@ -254,8 +254,17 @@ private static void addFooterCode(Document templateBody, String headCode){
 	}
 
 	private static String getPageWithValue(Document templateDrawedBody){
-		Element globalContainer = templateDrawedBody.getElementsByAttributeValue(NAME_ATTRIBUTE, MAIN_DIV_NAME_VALUE).get(0);
-		return globalContainer.attr(ID_ATTRIBUTE);
+	    Elements globalContainers = templateDrawedBody.getElementsByAttributeValue(NAME_ATTRIBUTE, MAIN_DIV_NAME_VALUE);
+        if(null!=globalContainers && globalContainers.size()>0){
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/design/util/DesignTemplateUtil.java]: MINOR Use isEmpty() to check whether the collection is empty or not. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1155)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/design/util/DesignTemplateUtil.java [hunk 2]
```diff
@@ -254,8 +254,17 @@ private static void addFooterCode(Document templateBody, String headCode){
...
+	        Element globalContainer = globalContainers.get(0);
+	        return globalContainer.attr(ID_ATTRIBUTE);
+	    }
+        else {
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/design/util/DesignTemplateUtil.java]: MINOR Move this "else" on the same line that the previous closing curly brace. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARightCurlyBraceSameLineAsNextBlockCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 3]
```diff
@@ -258,43 +258,51 @@ public Template saveTemplate(Template template, Host destination, User user, boo
...
-	        return null;
-	    }
-	}
+        List<Container> containers = new ArrayList<>();
+
+        for (Contentlet page : pages) {
+            Set<String> containerId =
+                    MultiTreeFactory.getMultiTrees(page.getIdentifier())
+                    .stream()
+                    .map(mtree -> mtree.getContainer())
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Specify a type for: 'mtree' [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2211)
MINOR Replace this lambda with a method reference. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1612)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 4]
```diff
@@ -28,16 +36,21 @@
...
 import java.util.LinkedList;
 import java.util.List;
 import java.util.Map;
+import java.util.Set;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
+import java.util.stream.Collectors;
+
+import com.liferay.portal.model.User;
+import com.liferay.util.StringPool;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'com.liferay.util.StringPool'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 5]
```diff
@@ -28,16 +36,21 @@
...
+import com.liferay.util.StringUtil;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'com.liferay.util.StringUtil'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 6]
```diff
@@ -6,17 +6,25 @@
 import com.dotcms.repackage.org.apache.oro.text.regex.MatchResult;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'com.dotcms.repackage.org.apache.oro.text.regex.MatchResult'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 7]
```diff
@@ -6,17 +6,25 @@
...
 import com.dotcms.repackage.org.apache.oro.text.regex.Perl5Compiler;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'com.dotcms.repackage.org.apache.oro.text.regex.Perl5Compiler'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 8]
```diff
@@ -28,16 +36,21 @@
 import com.dotmarketing.util.Logger;
 import com.dotmarketing.util.UtilMethods;
 import com.dotmarketing.util.WebKeys;
-import com.liferay.portal.model.User;
-import com.liferay.util.StringPool;
-import com.liferay.util.StringUtil;
 
+import java.util.ArrayList;
 import java.util.Date;
+import java.util.HashSet;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'java.util.HashSet'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 9]
```diff
@@ -258,43 +258,51 @@ public Template saveTemplate(Template template, Host destination, User user, boo
...
+    @Override
+    public List<Container> getContainersInTemplate(Template template, User user, boolean respectFrontendRoles)
+            throws DotDataException, DotSecurityException {
 
-    		if (!permissionAPI.doesUserHavePermission(template, PermissionAPI.PERMISSION_READ, user, respectFrontendRoles)) {
-    			throw new DotSecurityException("You don't have permission to read the source file.");
-    		}
+        // 100 pages should be more than enough to get all the containers on a given template
+        // Trying to avoid the case where 10000 pages might use the same template
+        List<Contentlet> pages = APILocator.getHTMLPageAssetAPI().findPagesByTemplate(template, user, respectFrontendRoles, 100);
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MAJOR Assign this magic number 100 to a well-named constant, and use the constant instead. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS109)

File: dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java [hunk 10]
```diff
@@ -6,17 +6,25 @@
 import com.dotcms.repackage.org.apache.oro.text.regex.MatchResult;
 import com.dotcms.repackage.org.apache.oro.text.regex.Perl5Compiler;
 import com.dotcms.repackage.org.apache.oro.text.regex.Perl5Matcher;
+
 import com.dotmarketing.beans.Host;
 import com.dotmarketing.beans.Identifier;
+import com.dotmarketing.beans.MultiTree;
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java]: MINOR Remove this unused import 'com.dotmarketing.beans.MultiTree'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

File: dotCMS/src/main/java/com/liferay/portlet/PortletURLImpl.java [hunk 11]
```diff
@@ -193,11 +193,17 @@ public void setEncrypt(boolean encrypt) {
 	}
 
 	public String toString() {
-		StringBuffer sb = new StringBuffer();
 
-		sb.append(PortalUtil.getPortalURL(_req, _secure));
+        String ctxPath = (_portletReq != null) ?
+            ctxPath = (String)_portletReq.getPortletSession().getAttribute(
```
Comment (jenkins-dotcms) [inline dotCMS/src/main/java/com/liferay/portlet/PortletURLImpl.java]: MAJOR Extract the assignment out of this expression. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AAssignmentInSubExpressionCheck)
MAJOR Remove this useless assignment to local variable "ctxPath". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1854)

**Review by dsilvam — APPROVED** [review]

**Review by jgambarios — APPROVED** [review]
