### PR TITLE
Issue 20013 timezone issue

### LINKED ISSUE #20013: Potential Timezone Bug
**Describe the bug**
dotcms not handling Time Zone CST properly or Postgres no longer accepts CST as a valid timezone as it could mean a timezone in China or the Americas

**To Reproduce**
1. log into dotcms and go to Configuration
2. Select CST as timezone and click save
3. postgres will eventually choke so watch the pg_logs or dotcms log will tell ya too

**Expected behavior**
backend becomes unresponsive and eventually site degrades
This bug brought down two customers because of this. 
I suspect the values / params we send to the backend of dotcms (db) need to be updated

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a 
**Smartphone (please complete the following information):**
n/a

**Additional context**
See Jason Thompson in Engineering if you need more details.

### PR DESCRIPTION
**Pull request by victoralfaro-dotcms**
Using new class that checks if the database, so far Postgres, is OK when setting the a new default Timezone to the server.
If a failure is detected in time, the server Timezone i reverted to its previous state and the default user is not saved.

### CODE REVIEW

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java [hunk 1]
```diff
@@ -196,12 +195,13 @@ public static void updateUsers(java.lang.String languageId,
 	throws PortalException, SystemException,com.dotmarketing.exception.DotRuntimeException {
 		try{		
 			CompanyManager companyManager = CompanyManagerFactory.getManager();
-			//companyManager.updateUsers(languageId, timeZoneId, skinId, dottedSkins, roundedSkins, resolution);
-			companyManager.updateDefaultUser(languageId, timeZoneId, skinId, dottedSkins, roundedSkins, resolution);
-			
-			
-			
-			TimeZone.setDefault(TimeZone.getTimeZone(timeZoneId));
```
Comment (wezell) [inline dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:204]: Do we still need this line?  I think we do, right?

File: dotCMS/src/integration-test/java/com/dotmarketing/common/db/DBTimeZoneCheckTest.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
+package com.dotmarketing.common.db;
+
+import org.junit.BeforeClass;
+import org.junit.Test;
+import com.dotcms.util.IntegrationTestInitService;
+
+import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.assertFalse;
+
+public class DBTimeZoneCheckTest {
```
Comment (wezell) [inline dotCMS/src/integration-test/java/com/dotmarketing/common/db/DBTimeZoneCheckTest.java:10]: The test should be added to the integration suite.

**Review by wezell — CHANGES_REQUESTED** [review]
take a look

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java (hunk 1 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:204]: @wezell I think not. That happens at https://github.com/dotCMS/core/pull/20114/files#diff-a7359e9c2e1536f6d9fad70abb0e8d2262413aefe781c6df5822d25e7012e137R42.

Comment (wezell) [reply dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:204]: humm, what happens if the `timeZoneValid` return valid but the company/user fails to save for some reason? The server could get into a state whereby the server timezone and the company timezone don't match?  I think I like the `timeZoneValid` to not be the one to set the system timezone as it is intended to only be a test.

**Review by wezell — CHANGES_REQUESTED** [review]
see comments

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+import com.dotmarketing.exception.DotRuntimeException;
+import com.dotmarketing.util.Logger;
+import com.zaxxer.hikari.HikariDataSource;
+import io.vavr.control.Try;
+
+public class DBTimeZoneCheck {
+    private static Class driverClass;
+
+    public static Class resolveDriverClass(final HikariDataSource dataSource) throws ClassNotFoundException {
+        if (driverClass == null) {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:18]: I think this should be thread safe

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+            statement.executeQuery().next();
+
+            return true;
+        } catch (Exception e) {
+            Logger.error(DBTimeZoneCheck.class, "Timezone + '" + timezone + "' failed : " + e.getMessage(), e);
+            TimeZone.setDefault(defaultTimeZone);
+
+            return false;
+        } finally {
+            if (connection != null) {
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:57]: You can use

CloseUtils.closeQuietly(connection)

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+
+            final TimeZone testingTimeZone = TimeZone.getTimeZone(timezone);
+            if (!testingTimeZone.getID().equalsIgnoreCase(timezone)) {
+                throw new DotRuntimeException("Invalid Timezone: " + timezone);
+            }
+            TimeZone.setDefault(testingTimeZone);
+
+            connection = DriverManager.getConnection(hikari.getJdbcUrl(), hikari.getUsername(), hikari.getPassword());
+
+            final PreparedStatement statement = connection.prepareStatement("SELECT * FROM inode WHERE idate > ?");
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:46]: I think you have to close not only the connection but also the Statement and the ResultSet, you can declare them at the begin with the connection and pass at the end, comma separated to the CloseUtils

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java (hunk 1 above)
Comment (jdotcms) [reply dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:204]: ok do you mean we have to do a soft set, and rollback to the previous at the end, so if the soft set is good, we can proceed and set in whatever we want right
I guess if it is the case we can rename the method to isTimeZoneValid and set the time zone in the if

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    private static final AtomicReference<Class> DRIVER_REF = new AtomicReference<>(null);
+
+    /**
+     * Driver class loaded to avoid call the loading method.
+     * @param dataSource
+     * @return
+     * @throws ClassNotFoundException
+     */
+    private static Class resolveDriverClass(final HikariDataSource dataSource) throws ClassNotFoundException {
+        DRIVER_REF.compareAndSet(null, Class.forName(dataSource.getDriverClassName()));
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:28]: Level

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+            resultSet = statement.executeQuery();
+            resultSet.next();
+
+            return true;
+        } catch (Exception e) {
+            Logger.error(DBTimeZoneCheck.class, "Timezone + '" + timezone + "' failed : " + e.getMessage(), e);
+
+            return false;
+        } finally {
+            Try.run(() -> TimeZone.setDefault(defaultTimeZone))
```
Comment (jdotcms) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:68]: Very Nice

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java (hunk 1 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:204]: You are right. Timezone set restored and also unsetting at `finally` code block and method has been renamed.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 3 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java]: Done.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 4 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java]: Done.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 5 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java]: Done.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+
+            final TimeZone testingTimeZone = TimeZone.getTimeZone(timezone);
+            if (!testingTimeZone.getID().equalsIgnoreCase(timezone)) {
+                throw new DotRuntimeException("Invalid Timezone: " + timezone);
+            }
+            TimeZone.setDefault(testingTimeZone);
+
+            connection = DriverManager.getConnection(hikari.getJdbcUrl(), hikari.getUsername(), hikari.getPassword());
+
+            statement = connection.prepareStatement("SELECT * FROM inode WHERE idate > ?");
```
Comment (erickgonzalez) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:56]: why not use DotConnect??

**Review by erickgonzalez — CHANGES_REQUESTED** [review]

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java [hunk 9]
```diff
@@ -196,12 +197,14 @@ public static void updateUsers(java.lang.String languageId,
 	throws PortalException, SystemException,com.dotmarketing.exception.DotRuntimeException {
 		try{		
 			CompanyManager companyManager = CompanyManagerFactory.getManager();
+			if (!DBTimeZoneCheck.isTimeZoneValid(timeZoneId)) {
+				throw new PortalException(String.format("Invalid Timezone %s", timeZoneId));
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:201]: I am not sure if a PortalException is the better option here, maybe something like a IllegalArgumentException could be better

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+        PreparedStatement statement = null;
+        ResultSet resultSet = null;
+        final TimeZone defaultTimeZone = TimeZone.getDefault();
+        try {
+            final HikariDataSource hikari = (HikariDataSource) DbConnectionFactory.getDataSource();
+            resolveDriverClass(hikari);
+
+            final TimeZone testingTimeZone = TimeZone.getTimeZone(timezone);
+            if (!testingTimeZone.getID().equalsIgnoreCase(timezone)) {
+                throw new DotRuntimeException("Invalid Timezone: " + timezone);
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:50]: maybe a custom exception here?, something like InvalidTimeZoneException it can extends from DotRuntimeException

Comment (freddyucv) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:50]: ALgo add when the exception is throw in the doc

**Review by freddyucv — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 8 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:56]: Using `DotConnect` we cannot if the recent default Tiemzone set was going to lead to a failure from the driver.

File: dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java (hunk 9 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/liferay/portal/ejb/CompanyManagerUtil.java:201]: The problem is if it's not a `PortalException` or `SystemExecption` the upper calling resource class will wrap any other exception in a `SystemException` causing the error message displayed to the user to include the exception fully qualified name like this: `java.lan.IllegalArgumentException: Invalid timezone CST`.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 7 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:68]: 👌🏼

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+import java.util.concurrent.atomic.AtomicReference;
+
+import com.dotcms.util.CloseUtils;
+import com.dotmarketing.db.DbConnectionFactory;
+import com.dotmarketing.exception.DotRuntimeException;
+import com.dotmarketing.util.Logger;
+import com.zaxxer.hikari.HikariDataSource;
+import io.vavr.control.Try;
+
+public class DBTimeZoneCheck {
```
[the remark this answers is not in the document]
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java:18]: Done.

File: dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java (hunk 10 above)
Comment (victoralfaro-dotcms) [reply dotCMS/src/main/java/com/dotmarketing/common/db/DBTimeZoneCheck.java]: Done.

**Review by dsilvam — APPROVED** [review]
