### PR TITLE
#20257 js issue fix and small improvements on the logging

### LINKED ISSUE #20257: Content Type Product breaks when rendering on the Contentlet edit dialog.
Under certain circumstances, I get the following warn on my logs 

`14:27:06.005  WARN  directive.DotParse -  - at com.dotcms.rendering.velocity.directive.DotParse.throwNotResourceNotFoundException(DotParse.java:181) @ url:GET//demo.dotcms.com/c/portal/layout | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:04-14-2021 02:26:43 CST  ref:http://localhost:8080/dotAdmin/  ?p_p_id=content&p_p_action=1&p_p_state=maximized&p_p_mode=view&_content_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_content_cmd=edit&inode=45d90b05-c1eb-48dd-98ad-171c63445175&in_frame=true&frame=detailFrame&container=true&angularCurrentPortlet=content`

This seems the cause of a javascript property breaking the fron-end 
`<%=field.variable()%>tinyPropOverride =  <%= com.dotcms.rendering.velocity.util.VelocityUtil.getInstance().parseVelocity(field.fieldVariablesMap().get("tinymceprops").value(),ctx) %>;`

Because of the velocity evaluation returning an empty string. 

This only happens with Products 
but it isnt always the case.

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
This prevents a rare issue that breaks the javascript on the contentlet edit window.
More specifically on function named enableWYSIWYG(textAreaId, confirmChange) 
Where a js prop is created based on the evaluation of a velocity script. When the evaluation returns an empty string the javascript breaks and the dialog loads blank. 

Additionally to that, there are a couple of small log improvements

### CODE REVIEW

**Review by dsilvam — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java [hunk 1]
```diff
@@ -123,7 +123,7 @@ private void writeFocalPointMeta(final Contentlet contentlet, final String field
            return parseFocalPoint(
                    (String) metadata.getCustomMeta().get(FOCAL_POINT));
        }catch (Exception e){
-          Logger.error (FocalPointAPIImpl.class, "Metadata Error retrieving focal point from custom metadata", e);
+          Logger.debug (FocalPointAPIImpl.class, "Metadata Error retrieving focal point from custom metadata", e);
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java:126]: is debug level enough? maybe warnAndDebug?

File: dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java [hunk 2]
```diff
@@ -135,7 +135,7 @@ private void writeFocalPointMeta(final Contentlet contentlet, final String field
             final String[] value = fpPattern.split(focalPoint);
             return Optional.of(new FocalPoint(Float.valueOf(value[0]), Float.valueOf(value[1])));
         } catch (Exception e) {
-            Logger.error(FocalPointAPIImpl.class, "Error parsing FP Metadata ", e);
+            Logger.debug(FocalPointAPIImpl.class, "Error parsing FP Metadata ", e);
```
Comment (nollymar) [inline dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java:138]: same question here

**Review by nollymar — APPROVED** [review]

File: dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java (hunk 1 above)
Comment (fabrizzio-dotCMS) [reply dotCMS/src/main/java/com/dotmarketing/image/focalpoint/FocalPointAPIImpl.java:126]: Thing is.. This is handled and looks horrible in our logs... It gives the wrong impression that the page is broken when it isn't. So I am trying to silence it.
