### PR TITLE
#21486 adding width and height to the basic metadata which  are calcu…

### LINKED ISSUE #21486: [GraphQL] : Second Binary field in a Content Type is not loading the expected metadata
Reported via Support: [106158](https://dotcms.zendesk.com/agent/tickets/106158)
Reproducible as of dotCMS 21.06.4, up to latest master (21.12)

We use Tika to load the metadata for the value of a **Binary Field** in a Content Type. However, if you have an additional **Binary Field**, the expected metadata is not being loaded correctly for it.

**ADDITIONAL NOTE: We're also having some class casting problems in the following methods:**
https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L87-L89

https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L115-L117

https://github.com/dotCMS/core/blob/eec3da4778d96d31884c8b53a22c73663722b6cd/dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java#L119-L121

**Where the values return as `Integer` objects sometimes, and then as `Long` values later. This causes that the value returned to the user defaults back to zero all the time.**

**To Reproduce**
Reach out to me for the data set and specific STR. However, for reproducing this in our Demo Site:
1. Create a Content Type named `TwoColumnImageBlock` with three fields:
1.1. Title: `Text`
1.2. Image: `Binary` / `User Searchable` / `Show in List`
1.3. Mobile Image: `Binary`
2. Create a new content of such a type, and upload two different images to each binary field.
3. In the **Dev Tools > GraphQL** portlet, enter the following query:
```
query IMAGE_WIDTH {
  TwoColumnImageBlockCollection {
    image {
      idPath
      size
      width
      height
    }
  }
}
```
The `size`, `width` and `height` properties return as expected.
4. Now, query the second Binary field:
```
query IMAGE_WIDTH {
  TwoColumnImageBlockCollection {
    mobileImage {
      idPath
      size
      width
      height
    }
  }
}
```
5. The `size`, `width` and `height` properties all return zero as their value.

**Expected behavior**
Metadata should be available in all Binary Fields.

**Additional context**
After discussing this behavior with @fabrizzio-dotCMS , it seems like metadata generation for the non-first Binary field is not working as it should. Unfortunately, there's currently no workaround for this issue.

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
Recently (When running a GraphQL query) a customer found that all the "non-first indexed" binaries in their content types came back without width and height. Which by design were only present on the first indexed binary which has the full metadata. 
This PR separates in a clearer way where the full metadata and basic metadata calculation take place. And adds the width and height to the basic metadata. 

The width and height calculation can be switched via interfaces 
But the default Class provides a way on which it is not necessary to read the whole file.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

File: dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java [hunk 1]
```diff
@@ -113,15 +126,33 @@ public boolean isImage(){
...
 
     public long getModDate(){
-        return Try.of(()->(long)getFieldsMeta().get(MOD_DATE_META_KEY.key())).getOrElse(0L);
+        final Object value = getFieldsMeta().get(MOD_DATE_META_KEY.key());
+        if(value instanceof Number){
+            final Number numericValue = (Number) value;
+            return numericValue.longValue();
+        }
+        Logger.debug(Metadata.class, ()->String.format("Invalid non numeric value found on metadata.modDate `%s` returning 0 ",value));
+        return 0;
```
Comment (freddyucv) [inline dotCMS/src/main/java/com/dotcms/storage/model/Metadata.java:155]: we repeat this code several time, can we create a method with this logic and reuse it?

File: dotCMS/src/integration-test/java/com/dotcms/storage/FileMetadataAPITest.java [hunk 2]
```diff
@@ -297,9 +297,23 @@ private void validateBasic(final Metadata metaData){
...
+        }
+        assertTrue(metaData.getModDate() > 0);
+        assertTrue(metaData.getLength() > 0);
+        assertTrue(metaData.getSize() > 0);
+
+        assertNotNull(metaData.getSha256());
+        assertNotNull(metaData.getTitle());
+        assertNotNull(metaData.getFieldName());
+        assertNotNull(metaData.getContentType());
+        assertNotNull(metaData.getFieldName());
```
Comment (freddyucv) [inline dotCMS/src/integration-test/java/com/dotcms/storage/FileMetadataAPITest.java:313]: why are we just checking NotNull?, can we check the expecetd value?

**Review by freddyucv — APPROVED** [review]

**Review by nollymar — APPROVED** [review]
