### PR TITLE
Fixing DependencyManager tes

### LINKED ISSUE #19627: Remove commented assert in DependencyManagerTest
Looks like some other test is making these asserts to fail:

https://github.com/dotCMS/core/blob/18da0a95054ffa7f4abe2de896425d86e5524c9a/dotCMS/src/integration-test/java/com/dotcms/publisher/util/DependencyManagerTest.java#L293

For now they are commented out but it's needed to determine what's going on and fix it.

### PR DESCRIPTION
**Pull request by freddyucv**
Fixing test in Dependency Manager

### CODE REVIEW

File: dotCMS/src/integration-test/java/com/dotcms/junit/MainBaseSuite.java [hunk 1]
```diff
@@ -31,10 +34,33 @@ public MainBaseSuite(Class<?> klass, RunnerBuilder builder) throws Initializatio
...
+        public Description getDescription() {
+            return this.runner.getDescription();
+        }
+
+        @Override
+        public void run(RunNotifier notifier) {
+            try {
+                this.runner.run(notifier);
+            } finally {
+                DbConnectionFactory.closeSilently();
```
Comment (jdotcms) [inline dotCMS/src/integration-test/java/com/dotcms/junit/MainBaseSuite.java:62]: good

**Review by jdotcms — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM

**Review by dsilvam — APPROVED** [review]
